### ISSUE TITLE
Support for 7z v15

### ISSUE THREAD

**Issue by atamariya** [UniversalMediaServer/UniversalMediaServer#1004]
The older version of jbinding does not support 7z v15 and throws up UNSUPPORTEDMETHOD. Upgrade to latest alpha should resolve this.

https://sourceforge.net/p/sevenzipjbind/discussion/757965/thread/555d6f1b/

**Comment by atamariya** [comment]
@Sami32 Since you're working on docs, you can add this for archive browsing on linux.

`sudo apt-get install p7zip`

**Comment by Sami32** [comment]
To be honest i discovered 7zip-jbinding oldness some weeks ago but didn't report it because the final 2.01 version is not ready yet and we are using the "allplateforms" version.

@atamariya I'm just trying to, with my limited skill. Thanks, i will ;-)

**Comment by Sami32** [comment]
@atamariya Done.

Since you are more skilled than me on Linux, if you could check [here](https://github.com/Sami32/UniversalMediaServer/edit/patch-6/INSTALL.txt?pr=/UniversalMediaServer/UniversalMediaServer/pull/964) or [there](https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Linux-install-instructions) and tell me if something is wrong i'll appreciate :-)

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/987/files

**Comment by SurfaceS** [comment]
#1992 fixed this
