### ISSUE TITLE
Substitution of SRT tags option

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1009]
Option permitting to ignore the SRT balises: `<b> </b> <i> </i> <u> </u> </font> <font color="....">`

@valib What do you think about adding this new subtitle option in the renderer configuration file ?
I'm not sure what should be the best best way for implementing that: Regex expression using the string `replaceAll` (_java.lang.String_) or using the Java class _java.util.regex.Pattern_ or a HTML parser ?

**Comment by valib** [comment]
@Sami32 what does it mean balises? And how your issue should exactly work?

**Comment by Nadahar** [comment]
Balises is French for tags. I still have no idea what the suggestion is though,

**Comment by ExSport** [comment]
@Sami32 Ignoring SRT tags? What do you mean exactly with this? I don't get the meaning and for what it probably should be useful.

**Comment by Sami32** [comment]
@valib Sorry, i didn't saw that the examples wasn't displayed because not set as "code". I just modified it in my first post. My bad... i guess the english word is maybe "HTML tags" ?

External SRT subtitles could be parsed/cleaned from HTML tags before being streamed if this option is enabled.
Since many renderers support SRT but not tags, this would make the subtitles more readable without the need to edit them manually.

**Comment by Nadahar** [comment]
@Sami32 What you're really asking is for an automatic "convertion" of HTML subtitles into SRT format? That sounds over simplistic to me, HTML is more than just the tags, and SRT files must be properly formatted with numbering, timings and text to work. Newline is also an issue when it comes to HTML as it's seen as just "normal whitespace" while it looks to me like it's a part of the syntax for SRT. On top of this there is character encoding to get right.

Is there a specific HTML (or XML) format you have in mind? I can't quite see why subtitles would be available in plain HTML.. or even make sense since there's no syntax for time stamps in "HTML" itself.

**Comment by Sami32** [comment]
> 3
> 00:00:56,220 --> 00:00:58,155
> <i>Go, man, go!</i>
> 
> 4
> 00:01:05,530 --> 00:01:06,830
> <i>Damn it! Damn it!
> Engine's dead!</i>
>

**Comment by Nadahar** [comment]
@Sami32 Ah, you want to strip the formatting?

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1014

**Comment by Nadahar** [comment]
#1018
