### ISSUE TITLE
Group media by month instead of dates

### ISSUE THREAD

**Issue by atamariya** [UniversalMediaServer/UniversalMediaServer#1081]
In Cache/Library view, I'd like to group media by month instead of days in a month. e.g. one entry for sept 2016, another for oct 2016 instead of multiple dates for each. Can somebody help me with the SQL?
![Currently showing dates](https://cloud.githubusercontent.com/assets/7592594/19931295/f75b211c-a131-11e6-94e3-d0e6754ce43e.png)

@UniversalMediaServer\developers
Edit: @Nadahar this is useful for large pics library where we tend to remember month or year than anything else.

**Comment by Nadahar** [comment]
@atamariya ```GROUP BY```. The ```GROUP BY``` expression must then transform the date information into something containing only year and month. The details depend on how the date is stored., If it's a standard ```DATETIME``` type there's probably SQL functions to do it, but if it's just a string you'd have to use substring or something like that.

You probably want to make this a names "calculated column" using the ```AS``` keyword and just reference this by name in the ```GROUP BY``` so that you don't have to do the "calculation" twice. You'll need to use this field as output as well as for grouping. You can't output the original date field since that's made logically invalid by the grouping, so you must keep in mind that the format should be in a form that you can handle further in Java with locale sensitive formatting. Use ```PMS.getLocale()``` to get the correct locale for formatting.

**Comment by Nadahar** [comment]
@atamariya Taking a look at the database, there's no applicable field to do this by IMO. The only thing available is the filesystem modified value, and it's hard to see how that would give a meaningful presentation to the user.

Given that you'd want to use this field though, this would be the SQL:
```SQL
SELECT 
  EXTRACT(YEAR FROM MODIFIED) AS YEAR, 
  EXTRACT(MONTH FROM MODIFIED) AS MONTH,
  COUNT(ID) as COUNT
FROM FILES
  GROUP BY YEAR, MONTH
  ORDER BY YEAR, MONTH 
```
The ```COUNT``` column isn't needed, I just added it to give the query a bit more interesting output. Just drop that the actual SQL.

**Comment by Nadahar** [comment]
When making the sub-query (the query for the child) the ```WHERE``` expression's "boundries" (>= and <) would have to be set with something like (pseudo code):
```java
GregorianCalendar boundry = new GregorianCalendar(groupYear, groupMonth -1, 1);
TimeStamp fromTS = new TimeStamp(boundry.getTimeInMillis());
boundry.add(Calendar.MONTH, 1);
TomeStampe toTS = new TimeStamp(boundry.getTimeInMillis());
```

**Comment by atamariya** [comment]
@Nadahar My question is in context of UMS. MediaLibrary class implements these SQLs. Perhaps I should rephrase my question - what would be the best way to implement the feature in the current codebase?

`MediaLibraryFolder mlfAudioDate = new MediaLibraryFolder(Messages.getString("PMS.12"), new String[]{"SELECT FORMATDATETIME(MODIFIED, 'd MMM yyyy') FROM FILES F, AUDIOTRACKS A WHERE F.ID = A.FILEID AND F.TYPE = 1 ORDER BY F.MODIFIED DESC", "select FILENAME, MODIFIED from FILES F, AUDIOTRACKS A where F.ID = A.FILEID AND F.TYPE = 1 AND FORMATDATETIME(MODIFIED, 'd MMM yyyy') = '${0}' ORDER BY A.TRACK ASC, F.FILENAME ASC"}, new int[]{MediaLibraryFolder.TEXTS, MediaLibraryFolder.FILES});`

I've tried the following, but it's not ideal:

 **`SELECT FORMATDATETIME(MODIFIED, 'MMM yyyy') AS MONTH FROM FILES F, AUDIOTRACKS A WHERE F.ID = A.FILEID AND F.TYPE = 1 GROUP BY MONTH`**

In four years, nobody has touched this code. So I'm hoping against hope if somebody remembers anything around this.

**Comment by Nadahar** [comment]
@atamariya My context is also UMS, but I didn't know that you only meant to modify the existing query.

This "works":
```java
		MediaLibraryFolder mlfAudioDate = new MediaLibraryFolder(
			Messages.getString("PMS.12"), new String[]{

			"SELECT FORMATDATETIME(MODIFIED, 'MMM yyyy') FROM " +
				"FILES F, AUDIOTRACKS A " +
				"WHERE F.ID = A.FILEID AND F.TYPE = 1 " +
				"ORDER BY F.MODIFIED DESC",

			"SELECT FILENAME, MODIFIED FROM " +
				"FILES F, AUDIOTRACKS A " +
				"WHERE F.ID = A.FILEID AND F.TYPE = 1 AND FORMATDATETIME(MODIFIED, 'MMM yyyy') = '${0}' " +
				"ORDER BY A.TRACK ASC, F.FILENAME ASC"},

				new int[]{MediaLibraryFolder.TEXTS, MediaLibraryFolder.FILES}
		);
```
...but I don't know where to begin to describe how terrible it is to do that. It is extremely inefficient to do it this way, and will always give English date formats.

The first query is bad because it doesn't group (and thus returns a lot of duplicate rows) and because it returns a ```String``` when the actual information could be much better stored in a ```long``` (which could be properly formatted before being displayed).

The second query is the worst though, ```FORMATDATETIME(MODIFIED, 'MMM yyyy') = '${0}'``` will force a full table scan because it has to process every row before it can be compared. This could so easily have been done like I suggested above, comparing numberic values with ```>=``` and ```<``` is quick and efficient, and proper indexes could be created to make it very fast.

However, when testing this it doesn't look like the speed of the query is the biggest problem, UMS spends a lot of time "discovering" these resources found by the query, so much time that Kodi times out when I try this on any month but those with very few tracks in them. Additionally, as stated above, I doubt the user will expect to find things by modified date, I'd have no idea how to find a music file from it's modified date.

**Comment by atamariya** [comment]
@Nadahar So it's just another of those half-baked solution which probably nobody is using. Then there's no point in fixing it. I'll comment it out too. I was just thinking it might work well for photos where pics taken around same time will fall under one bucket.

A sidenote: discovery is a non-issue for me as I use caching!! And I prefer Library view as it allows shuffling better while still grouping similar items.

**Comment by Nadahar** [comment]
@atamariya I prefer using a Media Library too, at least when it comes to audio or images. I don't know how many are using it, I just know that it's very ineffective the way it is. The last solution I posted will work as a copy-paste replacement for existing code, and it won't be any worse than the code that's already there. Without studying the other SQL's listed there I'm guessing they are all more or less equally inefficiant. It basicly has to do with the class structure, there's no way to make this proper using ```MediaLibraryFolder```. The reason is simply that it doesn't allow you to apply any kind of logic that you can't express in the SQL, and it only allows passing one parameter to the sub SQL and that is the same string that is shown to the user as the folder name. That just doesn't cut it.

It would be easy, by using different subclasses for each type, with just a little bit of code in each subclass, to make them perform, sort and function properly.
