### ISSUE TITLE
FLAC 1.3.2 update (optimization & FLAC in MP4)

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1140]
https://sourceforge.net/projects/flac/files/flac-src/flac-1.3.2.tar.xz/download
@SubJunk Here my FLAC 1.3.2 static build, without SSE2 instructions set, for Windows XP users and above.

[flac132_without_SSE2.exe.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/697097/flac132_without_SSE2.exe.txt)

**Comment by Nadahar** [comment]
@Sami32 Why without SSE2? This has been standard on CPU's since 2000 (2003 for AMD)...

**Comment by Sami32** [comment]
@Nadahar Because the last time 1.3.1, and the versions used before in UMS,  AFAIK, the FLAC version was without SSE2, for old CPU support i guess (like mine :stuck_out_tongue_winking_eye: )

**Comment by Nadahar** [comment]
Anyone that knows how much that impacts transcoding performance? SSE2 has been around since Pentium 4, so you need a Pentuim 3 to need this.... My guess is we have exactly **one** user that needs this, and that is @Sami32... another question is if these ancient CPUs can transcode at all.

**Comment by Sami32** [comment]
@Nadahar Yes, they can ;-)

**Comment by Sami32** [comment]
@SubJunk Or the original one:
http://downloads.xiph.org/releases/flac/flac-1.3.2-win.zip

As it include the new MP4 in FLAC container possibility.

**Comment by SubJunk** [comment]
I'm happy to update it but we should decide whether to do the SSE2 build or not... Does anyone else have an opinion on it @UniversalMediaServer/developers ?

**Comment by atamariya** [comment]
In what case is flac.exe used? Never encountered that.

**Comment by Nadahar** [comment]
@atamariya There's some "special solution" for the PS3 where FLACs are muxed into a video file with tsMuxeR. The reason is that the PS3 can decode high quality FLAC when part of a video stream but now when sent as audio. Not very logical I know, but knowing Sony there's probably some greedy reason why they thought that was a good idea. It's the transcoding engine called "High Quality Audio".

**Comment by atamariya** [comment]
@Nadahar can't the same be achieved via ffmpeg? It'll be one less binary to manage then.

**Comment by Nadahar** [comment]
@atamariya I don't know the details of this, I've never had any use for it. It's one of those "special adaptations" inherited from PMS where everything was about optimizing the PS3 experience. I think the idea is that it's not transcoded, only muxed, and that tsMuxeR need flac.exe for some reason. It might very well be doable with FFmpeg. I guess it's one of those features that nobody really cares much about but won't remove because you can bet there are some users that would miss it.

I'd rather just remove it if I were to do anything to it, as it only gives meaning for one particular renderer and is just a source of confusion and clutter for everybody else. It has its place in a *PS3* Media Server but not in an *Universal* Media Server imo.

**Comment by Sami32** [comment]
@atamariya Yes, FFMpeg can do it as well, and the latest FLAC upgrade have recently be set into it.

tsMuxeR is also used to play 24-bit FLAC, without correct MIME-type;  some years ago FLAC was not natively supported by FFMpeg and since less than 1 year now, it passed from experimental to final.
I guess it's a remanence from this era.

I thought about this, but i was scared to affect Playstation users while modifying this part of the code...
