### ISSUE TITLE
UMS freezes when trying to browse files via BubbleUPNP

### ISSUE THREAD

**Issue by prescott66** [UniversalMediaServer/UniversalMediaServer#1206]
I am using BubbleuUPNP on my android and Google Chromecast 2 as my renderer.
When i try to browse medias/videos on my external HDD, UMS stuck, it cant be closed with exit button and CPU usage is 100%.

Strange is, that browsing medias on my locall HDD is fine...
My OS: Manjaro Linux with Cinnamon, Linux 4.10.0
UMS version: 6.6.0 but i get this issue with previous release too

Attaching my tracing debug log:
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/801771/ums_dbg.zip)

**Comment by Nadahar** [comment]
@prescott66 Which of your shares is the external HDD? How is it mounted?

I can't find any issue in the log file. I'm guessing that since UMS freezes you're not able to pack the debug files from that session. We need a log file where the error actually occurs. To give us that, run UMS in "trace" mode and try to browse files on the external HDD so that the error occurs. Kill UMS/Java and go find the log file manually here ```/home/dusan/.config/UMS/debug.log```. Rename the file to ```.txt``` and attach it here.

**Comment by Sami32** [comment]
@prescott66 Before giving you some issue solving steps to follow, as it seem to me be a configuration issue only, i need to fully understand what is your use case. As a no english native, i prefer make sure that i understood you correctly.

You intend to view the UMS streamed videos on your Android smartphone/tablet via BubbleUPnP, is that correct ? If yes, what is/are your Motorala phone(s) model(s) that will be used ?

**Comment by SubJunk** [comment]
Stale
