### ISSUE TITLE
Windows won't go into sleep mode, while Universal Media Server is running

### ISSUE THREAD

**Issue by ErdnussFlipS** [UniversalMediaServer/UniversalMediaServer#1218]
Please let Windows go to sleep mode, when no device is streaming.
I configured my UWS so, hat HTTPv2 is disabled and "Prevent Windows from sleeping while streaming" is also disabled, but Windows still won't go into sleep mode. When UWS is not running, Windows go to sleep mode, without any problem.

It's regardless of UWS is running as Windows desktop application or as Windows service.

My UMS.conf: [UMS.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/829105/UMS.conf.txt)
It's installed on a Windows 10 Pro 14393.693, with 2 external attached USB HDD's.
UWS is running on Java 8.

That's a bug for me and a showstopper to use this application as media server on a Windows NAS/Home Server. 😞 

PS: It's not the same bug, as #581 ("Prevent Windows From Sleeping" keeps computer awake even if not streaming).

**Comment by Nadahar** [comment]
@ErdnussFlipS If you install UMS as a service you must never use the GUI (start the application). You will need to add rules to open your firewall only if its running as a service. The safest thing is to uninstall the service and restart the computer and only use it as a desktop application.

It's a shame because IMO UMS would fit best to run as a service, but there is a fundamental design flaw that UMS has inherited from PMS where the GUI and the server is one and the same application. Since a service can't have a GUI, people tend to install the service and still use the GUI. That's when "everything" go wrong as you're essentially running UMS twice with the same configuration - so it's trying to use the same addresses, configuration files, ports etc.

If you've disabled "prevent Windows from going to sleep" and it still won't go to sleep, it sounds to me like you're running both the service and the application at the same time. Make sure that's not the case.

**Comment by ErdnussFlipS** [comment]
@Nadahar I've installed UMS, then configured it over the UMS GUI, disabled autostart and installed it as service (service is not running). Afterwards I shutdown UMS GUI and run UMS Service from windows service panel. Then I left the Windows system in idle, but Windows won't go in to sleep mode until I shutdown the service again.

Today I tested it again, and Windows is going to sleep, even when UMS Service is running. I don't know what happend, but now it works.

**Comment by Nadahar** [comment]
@ErdnussFlipS Sounds strange. As long as "Prevent Windows from sleeping while streaming" is disabled UMS doesn't send any commands to the Windows API regarding sleep mode - which should make it impossible for UMS to interfere in any way.

There are some potential issues with permissions when running as a service, the user the service is running as (usually ```Localsystem```) need to have permission to access UMS' profile folder. If not, the service will run with a "default configuration" ignoring the configuration file created using the GUI. But, if this "solved itself" this doesn't seem like a likely cause.

If this keeps working, I guess you can close the issue?

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1226
