### ISSUE TITLE
DVD ISO are not working anymore since 6.6.0 version

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1231]
It seem that this bug was intoduced with [this commit](https://github.com/UniversalMediaServer/UniversalMediaServer/commit/8558912e29cc80043b321cf9577342c56aaa9ea8).

Issues already related in our forum in the following threads:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=9223&start=20
http://www.universalmediaserver.com/forum/viewtopic.php?p=30137#p30137

**Comment by SubJunk** [comment]
Thanks for the bug report. I have a PS3 so I can test this

**Comment by Sami32** [comment]
@valib Please, could you have a look at [your commit](https://github.com/UniversalMediaServer/UniversalMediaServer/commit/8558912e29cc80043b321cf9577342c56aaa9ea8) and see what's wrong ?
I tried but i not understood why the tests make it fail.

**Comment by valib** [comment]
@Sami32 sorry but only @Nadahar can test it. I don't have a PS3.

**Comment by Sami32** [comment]
@Valib Sorry, i thought that i was the only one not having it ;)
But you can try to check at the code, or debug it with Eclipse ? As you are better than me.

@Subjunk can test as well, as @Nadahar is overbooked for now.

**Comment by Nadahar** [comment]
I have a PS3, but I don't think I have a DVD ISO. What are those useful for? 😛

**Comment by Sami32** [comment]
@valib Users reported that it happened with others renderers than PS3/PS4 as well.

@Nadahar I don't really know as i never used myself, but the users say that it affect the DVD play as well (VOB).
I just remember that such DVD ISO was useful for game and DVD play that is protected, with some software like _Alcohol 120_ or _DAEMON Tools_ you can make virtual copy making you able to play it without keeping the DVD inserted and without breaking the protections.

**Comment by Nadahar** [comment]
@Sami32 I have lots of DVD iso's with data content, I was referring to video content.

**Comment by Sami32** [comment]
@Nadahar VOB, is that data content ?

**Comment by Nadahar** [comment]
@Sami32 I'm talking about UDF formatted DVDs where you place data files (backups, software installations DVDs etc).

**Comment by SubJunk** [comment]
I can upload a DVD ISO with video on it if anyone wants. I still haven't got around to testing this so someone could beat me to it ;)

**Comment by Sami32** [comment]
2 more users reports:
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=9385&p=30435#p30435
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=9391

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/740
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=3857

**Comment by esabol** [comment]
Fwiw, you can find two DVD-Video ISO images, one NTSC and one PAL, here:
https://archive.org/details/BigBuckBunny

**Comment by esabol** [comment]
There's also an ISO at http://www.deniscarl.com/dvdtest/ but I don't know if it has sound.

**Comment by Sami32** [comment]
@SubJunk As i suspect that you never your your PM overcrowded box, i post it here.

Can you do something for the quota limitation message that appear to all the users on the forums since some weeks ? As most of them seem lost and don't know how to do.

Some cleaning of old logs or bigger files ?
Thank you for them.

**Comment by SubJunk** [comment]
@Sami32 I can't see any quota limitation message, can you be more specific?

**Comment by Sami32** [comment]
@SubJunk Sure.
"Sorry, the board attachment quota has been reached."

**Comment by Sami32** [comment]
@SubJunk If you can wait few day for the latest _MediaInfo_ version before push the 6.7.0 version, it'll avoid TS, MTS, M2TS freezing and ACELP issue.
As i think that we already have our quota of issues ;)

**Comment by SubJunk** [comment]
@Sami32 cool, I've increased the attachment limit

**Comment by Sami32** [comment]
@SubJunk Thank, i just found the answer how to solve it:
https://www.phpbb.com/community/viewtopic.php?f=46&t=1488605

Thank you :)
If you don't mind i'll delete our post off topic.

**Comment by SubJunk** [comment]
Cool

**Comment by valib** [comment]
@Sami32 the bug was not introduced by my commit https://github.com/UniversalMediaServer/UniversalMediaServer/commit/8558912e29cc80043b321cf9577342c56aaa9ea8 but by commit b235331d63ce004241d27e3a5eb66d260a269b57 introduced by @Nadahar. This commit stopped to play DVD ISO not only for PS3 but also for all other renderers because it stopped browsing inside the DVD ISO. I didn't realized that because I don't use this feature so I even tested it 😞

**Comment by Sami32** [comment]
@valib Never mind, me as well, if the users didn't reported it, i'll have never known about it, as i don't use UMS anymore except for testing...

Thank you for have taking the time to look at it :smile: , as we just have new other recent report on this issue in the forum.
And since @SubJunk didn't beat himself yet ;)

When i first checked at it i tried to withdrawed these lines but that didn't make thing better, and threadsafety is still a mystery to me, though i don't think it's related to it.
```
public ISO() {
		type = ISO;
	}
```

**Comment by valib** [comment]
@Sami32 it solve it only partially. Than the renderer is able to browse inside the DVD ISO but not to play when transcoding is needed. There is a `DVDISOFile` class which should take care about it but it seems that it doesn't work after that commit.

**Comment by Nadahar** [comment]
@valib I don't know how you conclude that it only fixes it partially, as far as I can see that's the only thing that b235331d63ce004241d27e3a5eb66d260a269b57 changed that's related to this issue. I have compared the behavior in 6.5.3 and with #1287 and can't see any difference.

Try turning off the cache to make sure what you're experiencing isn't caused by some wrong parsing that is cached.

**Comment by Sami32** [comment]
@esabol Thanks for the small ISO sample link :+1: 
Feel free to report back if it do not work in the next version; you can reopen this issue if it was closed.

**Comment by Sami32** [comment]
Not sure that's relevant here, but i discovered it and wanted shared:
https://github.com/stephenc/java-iso-tools
https://mvnrepository.com/artifact/com.github.stephenc.java-iso-tools

**Comment by Nadahar** [comment]
@Sami32 I've seen it, but: It's actually very old (it's forked from JIIC which is very old, and it doesn't seem like much has been done to it since), if it works that doesn't really matter, but it's a "warning sign". In addition, that will only allow us to read the "file system" of the DVD. The "real problem" is parsing the DVD content. This is stored in [this mess of a format](file:///E:/data/Dokumenter/Computer/Standards/DVD-Video%20Information/DVD-Video%20Information.htm). What ```libdvdread```/```libdvdnav``` is used for is parsing that mess. 

If MediaInfo used those libraries and could read the ISO format, we could get a lot done without relying on MEncoder to get the content, but it can't. Even if we get access to the "files" inside the image, it doesn't help us much in parsing them unless we want to do it outselves. MediaInfo, FFmpeg etc still can't parse those files for us as they doesn't understand the file system.

**Comment by Sami32** [comment]
@Nadahar I agree, but it was worst mention it, imo.
In 1 year old not too much things happened in ISO standard, isn't ?
But yes, as you already said, that'll ask some parsing to be done, and as you said that the DVD parsing is not as easy as it could seem...

I thought the same things about MediaInfo, but i feel that it's out of the scope of a such tool, because i think that ISO is considerate as "obsolete". I don't mean that can be useful for some users.

**Comment by Nadahar** [comment]
@Sami32 I'm not talking about one year. You have to look at the changes made, not only the dates. [Here is an discussion on the topic](https://softwarerecs.stackexchange.com/questions/34187/java-library-for-creating-iso-thats-still-supported).

I won't swear to anything now, but when I looked at it I think I found that the last actual code contribution was in 2006 or 2007. The JIIC CVS repository and homepage is also down, and seems to have been so for many years.

It's great that someone has managed to fork it on GitHub before it disappeared completely - and it might be working just fine, but Java itself has changed so much in that time that often things written that long ago has some problems today (relying on deprecated/outdates libraries and classes etc.). 

I think it would be great if MediaInfo supported it, but I don't know if the author is "interested". It would be much easier for MediaInfo to support than for us, since it's C++ so that the necessary libraries can be used directly. MediaInfo wouldn't have to do any of the DVD content parsing itself, it could just parse the streams (which are already supported I would think, except maybe the subtitles).

Linking the libraries statically would increase the size though, and linking them dynamically would make it a hazzle to use (IMO). There might also be some licensing issues, I'm not sure if their licenses are compatible though, it seems like the ```libdvd*``` use GPL (which doesn't allow use in closed-source projects) while MediaInfo use a BSD-style license where closed-source use is permitted.

**Comment by Sami32** [comment]
@Nadahar It should be great for us, but i don't think it is for MediaInfo, IMO.

Your link do like yourself, ask if it's still good, but that's all. All people around still use it without issue.
I can understand that an "living" project should prefered, but the fork work fine and no other similar project exist, AFAIK.
Yes, one day that could not work anymore, like any projects. No need to use, but being aware of doesn't kill, isn't ?

From what i unsderstood, he's on the way, before the end of this year, of the whole project's licence change. More fully open source.
That's said, you know how good is my english :wink:

**Comment by Sami32** [comment]
@Nadahar About the ISO files that wasn't able to open, they're UDF 2.50.
I finally able to open them with ISOBUSTER.

**Comment by Nadahar** [comment]
@Sami32 I'm not sure what you're referring to now, but I've looked for UDF support for Java as well, which was even more hopeless.

**Comment by Sami32** [comment]
You have say that some of my ISO was not recognized, so i tell you now, why they wasn't.
I didn't cared until today, as i did a report, so i needed to install a XP driver for them.

https://mvnrepository.com/artifact/com.github.stephenc.java-iso-tools/loop-fs-udf-impl/2.0.1
That's said, MediaInfo did parsed one of my UDF ISO file !!!
Don't ask me how it's even possible, i still don't get it.

**Comment by Sami32** [comment]
@Nadahar OK, so it seem that i was wrong, i planned to add ISO and UDF support, though it'll not be in a near future.

**Comment by Sami32** [comment]
Fixed by @Nadahar
