### ISSUE TITLE
Recent changes clarifications

### ISSUE THREAD

**Issue by taconaut** [UniversalMediaServer/UniversalMediaServer#1249]
Hi @Nadahar,
I'm merging your recent changes into ums-mlx and was wondering about the changes in DLNAMediaInfo (and DLNAMediaDatabase) where BITSPERPIXEL, MODEL, EXPOSURE, ORIENTATION and ISO have been _replaced_ by IMAGEINFO.

- Is this change only related to image files or is the ImageInfo being used for other file types?
- What's the difference in DB type BINARY or OTHER for THUMB (I'd like to avoid conversion on DB update if possible)

**Comment by Nadahar** [comment]
Hi @taconaut,

Most of the fields I removed wasn't in use at all, it seems that someone had added them with a plan of implementing something but never gotten around - or that this code has been lost along the way somewhere. ```ImageInfo``` is a new class that you can find in the ```images``` package, which holds all image related information for image media. Bits per pixel and orientation is part of those metadata, but the camera specific metadata isn't (because I couldn't see that it could be useful to us). There are loads of additional information stored in ```ImageInfo``` though, and it itself is an abstract class with subclasses for the concrete image types so that it can hold metadata unique to one format. 

Since thumbnails are also images the same applies to them. They have gotten their own class, ```DLNAThumbnail``` which basicly is a wrapper for the byte array with the actual thumbnail data and a corresponding ```ImageInfo``` instance describing that thumbnail. You can get both with getters.

When BINARY was used the byte array with the thumbnail data was dumped in the database. OTHER is used for serializing Java class instances, so the information is stored quite differently in the database although the information is essentially the same plus an ```ImageInfo``` instance. When you fetch a serialized object from the database, it is deserialized and an instance of it's class is constructed and returned. This means that complete instances of both ```ImageInfo``` and ```DLNAThumbnail```are stored in the database, and there's really no way to merge the changes from #1061 without also doing the database changes (unless you want to parse this information every time a it's needed). 

I'm currently trying to merge the changes in the database with those done in #942 - which I think will be a pretty big task. You might want to wait with merging this until 7.0.0 is out, because I fear that a lot of the work you put into the database changes now will be replaced by even bigger changes in 7.0.0 (where the tables themselves are reconstructed).

**Comment by taconaut** [comment]
@Nadahar 

Thanks for the response.
Did I understand correctly that both THUMB and IMAGEINFO stored in the DB will contain a serialized ImagInfo and that only for pictures (not video or audio) the IMAGEINFO will store the full size picture, whereas  THUMB will contain the downscaled thumbnail. I'm asking because I've never got around to implement picture support in ums-mlx and could safely ignore this for now.

I think I'll indeed wait for the full merge as it will require quite some time as my DB model is a bit more complex as the ums one here's just the bit for files.
![db_files_model](https://cloud.githubusercontent.com/assets/275379/24709265/9ea05ee6-1a19-11e7-96a7-20163f3265bc.png)

**Comment by Nadahar** [comment]
@taconaut No, [ImageInfo](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/2bc07700532dfd131b5d74608dbdde0c86d48775/src/main/java/net/pms/image/ImageInfo.java) only holds metadata about an image, not the image data itself. As stated above, it's subclasses with subclasses for concrete image formats which holds additional metadata for that format. 

The "base" class ```ImageInfo``` only holds this information:
```java
	protected final int width;
	protected final int height;
	protected final ImageFormat format;
	protected final long size;
	protected final int bitDepth;
	protected final int numComponents;
	protected final ColorSpace colorSpace;
	protected final ColorSpaceType colorSpaceType;
	protected final boolean imageIOSupport;
```

For JPEG images for example, the instance is actually a [JPEGInfo](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/2bc07700532dfd131b5d74608dbdde0c86d48775/src/main/java/net/pms/image/JPEGInfo.java) which in addition to those above holds:
```java
	protected final Map<Integer, JpegComponent> components;
	protected final Integer jfifVersion;
	protected final CompressionType compressionType;
	protected final Boolean isTypicalHuffman;
	protected final JPEGSubsamplingNotation chromaSubsampling;
```
But, as ```JPEGInfo``` is actually a subclass of [ExifInfo](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/2bc07700532dfd131b5d74608dbdde0c86d48775/src/main/java/net/pms/image/ExifInfo.java) which holds:
```java
	protected final PhotometricInterpretation photometricInterpretation;
	protected final ExifOrientation exifOrientation;
	protected final ExifOrientation originalExifOrientation;
	protected final Integer exifVersion;
	protected final ExifCompression exifCompression;
	protected final ExifColorSpace exifColorSpace;
	protected final Boolean hasExifThumbnail;
```
... all these metadata will be available for a JPEG (given that they could be parsed, very few JPEGs have all this infomation.

The instance stored in the database for a JPEG will hold those medadata, while those stored for a PNG will hold the corresponding data from [PNGInfo](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/2bc07700532dfd131b5d74608dbdde0c86d48775/src/main/java/net/pms/image/PNGInfo.java) etc.

Storing it this way is much more flexible, as I'd have to expand with database with a lot of fields that would only occationaly be used to cover all this if I'd map each metadata to its own database field.

Stored in THUMB is an instance of [DLNAThumbnail](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/2bc07700532dfd131b5d74608dbdde0c86d48775/src/main/java/net/pms/dlna/DLNAThumbnail.java). It doesn't actually hold any information itself (but has methods that govern rules for thumbnails) but it's a subclass of [DLNAImage](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/2bc07700532dfd131b5d74608dbdde0c86d48775/src/main/java/net/pms/dlna/DLNAImage.java) which again is a subclass of [Image](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/2bc07700532dfd131b5d74608dbdde0c86d48775/src/main/java/net/pms/image/Image.java) which holds the following:
```java
	protected final byte[] bytes;
	protected final ImageInfo imageInfo;
```

The content in ```bytes``` is the same as what was previously held in THUMB directly - the scaled down thumbnail image itself.
```imageInfo``` holds an ```ImageInfo``` subclass instance describing the *thumnail* (not the original image if the media is an image). 

These can be retrieved directly with getters, but ```Image``` also [holds a number of getters for easy access to information held in ```ImageInfo```](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/2bc07700532dfd131b5d74608dbdde0c86d48775/src/main/java/net/pms/image/Image.java#L493-L595).

It's very easy to "create" a ```DLNAThumbnail``` instance from a raw byte array (or a number of other forms) by using one of the ```DLNAThumbnail.toThumbnail()``` methods (which will parse the thumbnail metadata and create the corresponding ```ImageInfo``` instance). Retrieving the raw byte array is as easy as using ```DLNAThumbnail.getBytes()```. This means that adapting existing code is very easy, while the benefit is getting a much better (DLNA compliant) thumbnail handling in return.

Even if you haven't implemented support for images, I'm guessing you use thumbnails - so there is a lot of improvements in these changes that would apply to MLX. However, because of the manual labor required to "merge" the database structures, I'd still wait.

**Comment by taconaut** [comment]
Thanks a bunch for clarifying  👍
