### ISSUE TITLE
Ability to throw url at UMS and recive transcoded stream.

### ISSUE THREAD

**Issue by bigretromike** [UniversalMediaServer/UniversalMediaServer#1277]
Is there a possibility with pure UMS or with some kind of plugin to achieve this?:

I would send to already working UMS url to a file/stream (that is hosted on lan network with http access to it) via somekind of interface (api/console/python/plugin) and expect to UMS return a valid url to transcoded file (live transcoding like in dlna).

Basic usage: attempting to open unsupported format on player it would fallback to ums transcoded material so player would be able to play same file but in compatible format.

As I understand UMS need to be restarted for DLNA clients to see files, but in this case those would be pass too ums by the player/client itself.

**Comment by Nadahar** [comment]
@bigretromike Unfortunately I can't see that this is possible the way UMS is working internally. The problem is that UMS doesn't actually use the "file name" requested in a HTTP request - it uses the ID number which can be found before the last ```/``` in the URL. Had this ID been constant it would have been one thing, but it isn't. These ID's are generated for each renderer session (so each renderer sees different IDs). This has to do with the fact that the whole "content tree" isn't static and is built based on a number of factors and settings, that can vary from renderer to renderer.

If you could find a way to get the correct ID for a given file, it would be possible to request that file via HTTP from "anywhere", but you'd also need to "fake" the user agent of the renderer you'd pretend to be. I guess it would be possible to write a very advanced script that "simulated" a very basic renderer and browsed UMS' content to get the correct ID. It wouldn't be very easy or quick to do though, as browsing in UMS is time consuming as UMS will scan all the files in each folder and generate IDs, make decisions on streaming or transcoding etc, so the script would have to be prepared to wait for several seconds for each folder it had to traverse.

I don't know if a plugin could be written that could be of any help either, the problem is that this goes against the fundamental logic that UMS' "content tree" is built upon.

**Comment by bigretromike** [comment]
@Nadahar thanks for quick respond. Its been some time when I played with one cool plugin UMS have to offer `Jumpy` jumpy use the `dynamic` content I talk about but the problem with it is Jumpy expose those urls to dlna client and not the player I have in mind. I basicly would like to use well working mechanice from UMS as transcode on-demand machine with local content. I didn't read about "content tree", but Jumpy somehow bypass that thing - as you can for example browser xbmc/kodi addon content live ona DLNA player and pick content you want (which miss my 2 needs: ability to expose this 'explore' mechanic to my player (which is not dlna player), ability to skip-transcoding if thats not needed (which im not sure))

**Comment by Nadahar** [comment]
@bigretromike I don't think jumpy bypasses the IDs, UMS can take URLs as "content sources" but it will still generate an unique ID for each source for each renderer. UMS also needs a renderer profile which tells it what needs to be transcoded and not. This is different from renderer to renderer, so you'd have to create such a profile that matched the capabilities of your player.

**Comment by SharkHunter** [comment]
Yes this works. I use it every day and yes it was at least possible to get it trnacoded between redner. No plugin (neither Channels/Jumpy) bypasses any ID generation.  This is the sole purpose of the GlobalID stuff to be able to pass IDs between renders. This works perfectlt on 6.2.x if it works now I don't no but I wouldn't think so since nobody cares about dynamic content anymore (and some people have never understood whats so great about it).

**Comment by Nadahar** [comment]
@SharkHunter There's been no changes to the GlobalID that I'm aware of. But, they aren't "stable" in that they are regenerated every time you restart UMS. How is the external player supposed to know the ID for a given source without browsing the CDS?

**Comment by atamariya** [comment]
I personally do media searches via phone and then push it over to renderers - Kodi or denon.

**Comment by bigretromike** [comment]
Reading all your answers @Nadahar and especially yours @SharkHunter Im thinking about adding DLNA client (library) but that wouldn't resolve problem with getting my video url inside UMS.
I could then browser my Kodi addon inside same addon but with DLNA client then browser `Jumpy` that would browser my addon inside addon. Then DLNA client would read video urls from my addon via Jumpy..

But is there a way I could add dlna lib to my kodi addon and send video urls from my addon to ums (like a push function from remote?)

**Comment by Nadahar** [comment]
@SharkHunter 
> Don't you know DLNA 101?
You're missing the point. I said that because the ID's aren't stable one would need to use DLNA to browse the tree. The question here was if it was possible to get content via HTTP *without using DLNA*. Whether you use a DMP, DMR or other "control point" to do the "UPnP/DLNA browsing" isn't relevant, it still requires knowledge and implementation of UPnP/DLNA.

I also happen to know that the current GlobalID implementation is in breach of the DLNA standard:

> **10.1.4.1 MM ObjectID usage**
> **10.1.4.1.1**
> **[GUIDELINE]** UPnP AV MediaServers shall assign a unique object ID for each entry in their ContentDirectory service (CDS). This rule applies to both container and item objects in a CDS metadata hierarchy.
> **[COMMENT]** This guideline is a requirement repeated from ISO/IEC 29341-20-12. This guideline's scope for uniqueness is for the entire CDS hierarchy.
> **10.1.4.1.2**
> **[GUIDELINE]** UPnP AV MediaServers should maintain the object ID value on a persistent basis. 
> 

@bigretromike Your last comment makes me confused as to what you're actually trying to do. How does Kodi come into play? Kodi supports UPnP and can browse UMS without any modifications. What is the "external player" that you want to access UMS' resources with?

As to what you originally asked for, @SharkHunter mentioned the web interface - and that might be a way to obtain the URL's without using DLNA. I'm not sure of the details of how the web interface does this (it launches a Flash or HTML5 player) but it would probably be possible to parse the media URL from the web interface response.

**Comment by bigretromike** [comment]
@Nadahar I was afraid it will confuse. So I will recap what I want to do:

I develop Kodi Addon that use 3rd party application that serve videos as http streams. My addon give kodi ability to browser those videos with categories/tags/your ratings/etc. Those videos cannot be added to library because of reasons (they can be on other machine, adding them directly would bypass my addon functionality (marking/voting/reviews)). I would like to have ability to add setting in kodi that when enabled kodi addon would send stream http url to UMS (like `jumpy` does) so Kodi internal player would play the url from UMS that is a transcoded version of url that my Kodi addon support.

**Comment by bigretromike** [comment]
@Nadahar Kodi addon is not able to browser UMS (not in the way I would like) the only way to access the data from my plugin is via UMS + Jumpy, because Jumpy execute my plugin inside UMS so it basicly make bridge between data from 3rd party software that my plugin is design for and ums. 

Sorry about the way im trying to explaining my issue, because the way I does it make the issue bigger than it is.

I will try even simplier: 

there is a server application that expose and catalog your media library (we name it `server`) 
there is kodi with my plugin that can talk to `server` and get metadata (we name it `client`)
`server` expose media library as stream url
UMS have access to `server` by executing my `client` addon inside `jumpy` (because it execute python inside) that way UMS transcode urls from `server` and play them on renderer.

What I want to achieve is: being able to browser `server` inside `client` (kodi+addon) and then send url of video to UMS and get url from UMS for transcoded video. 

Currently I could achieve this only by: browser UMS inside KODI (dlna), pick `Jumpy`, pick my addon that is inside Kodi, then browser `server` content and play it. But this way I narrow the transcoding ability as every Kodi would have same render profile (which is false) 

The thing I want to achieve in long run is to be able to watch transcoded media on not powerful device connected to TV from inside Kodi with all the features that addon give to end user; 

The best way would be having somekind of interface that I would be able to send URL and get URL as respond - but thats probably not gona happend. But the light in tunnel in my case is Jumpy that transcode my `server` content that isn't added to UMS library so there should be someway to tide those things up. 

Question is how...

**Comment by Nadahar** [comment]
@bigretromike I think I understand, and I'm not sure that's very easy to do. DLNA is made for that purpose (deliver content to all kind of devices, also those with few resources) and your devices could communicate with UMS directly to achieve that. Unfortunately DLNA doesn't have a lot of possibilities for tagging, rating etc. 

I see a couple of possible approaches that could do what you want:
* Make a UMS plugin that implements your "client" - which browses your "server" directly from UMS without involving Kodi or Jumpy. UMS has something called "virtual folders" that your plugin could build a "tree" of that could make it possible to select media by rating, tags etc. The limit is that everything would have to be organized as virtual folders, but each media file could appear in many places in the tree - so that there were multiple paths to find the same media. Your devices would then browse your "server" via UMS and UMS would take care of transcoding.
* Implement a DLNA protocol in your "server" so that it could enumerate the resources available through UMS, which again would make these available through Jumpy -> "client". It sounds like a solution that would be hard to get to work reliably and predictably.
* Skip UMS alltogether and make your server use FFmpeg for transcoding the files before sending them to the "client".

**Comment by bigretromike** [comment]
Third option is no go. Plugin for ums is an option but it would be harder and qould braek alot of things and would split my project. I wanted to use ums as a backend fpr transcoding. The second option could be something. 

There is another option. Ums plugin that would server as in/out bridge like jumpy does. It would be probably overkill but who knows.. 

Is there any deep documentation for ums plugin development? 

Also im thinking about something... If my addon would have dlna remote to push media url somehow to ums and kodi could act as renderer ... Would that be a option to consider ?

**Comment by Nadahar** [comment]
@bigretromike If all you want is to use UMS to transcode, I think the 3. option is way easier than any of the other. UPnP and DLNA is a lot to learn just to do something like this, but that's entirely up to you.

I don't know all the inner workings of Jumpy, but as far as I know it isn't a "in/out" bridge. What Jumpy does, and the whole "plugin system" in UMS is built around, is to provide input to UMS. Does Jumpy really also output, and if so - in what form?

I'm afraid there is no plugin documentation (that I'm aware of) at all. Plugins have access to most of UMS, and has few "rules" to follow. The easiest way to figure this out is probably to read the source code of other plugins.

You can't "push" content to UMS since it's a server, a DLNA "remote" could browse UMS's content and then push that to a renderer, like Kodi. But, I'm really not sure what that would accomplish. You'd still need to implement UPnP and DLNA, which isn't trivial. I don't quite understand how you would control this UI wise, but that might not be important that I do.

**Comment by bigretromike** [comment]
@Nadahar and @SharkHunter thank you for great discussion. This issue gave me a lot of info that I was lacking. I will try to overcome my problem and still will like to use UMS as my first choice for transcoding solution. 

Also thank you for making UMS more and more reliable - I know its not perfect 100% bulletproof but its getting better and better.

I will close issue now as I know which direction I should go, and how to look on my issue from UMS perspective
