### ISSUE TITLE
FileNotFoundException (Error initializing plugin credentials)

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1290]
```logtalk
DEBUG 2017-05-30 13:31:31.402 [main] Error initializing plugin credentials: {}
java.io.FileNotFoundException: /home/asmol/.config/UMS/UMS.cred (Нет такого файла или каталога)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at net.pms.configuration.PmsConfiguration.initCred(PmsConfiguration.java:3165)
	at net.pms.PMS.main(PMS.java:1249)
DEBUG 2017-05-30 13:31:31.404 [main] PID file not found, cannot check for running process
ERROR 2017-05-30 13:31:31.405 [main] Failed to write PID file: /home/asmol/.config/UMS/data/pms.pid (Нет такого файла или каталога)
```

That's said, perhaps it's the correct way to output such error ?
It come from a Linux user's log.
Feel free to close it if it's "normal".

**EDIT**:
```logtalk
DEBUG 18:21:42.481 [main] Reading cred.path: "/home/asmol/.config/UMS/UMS.cred" (default: "")
DEBUG 18:21:42.487 [main] Error killing old process java.io.FileNotFoundException: /home/asmol/.config/UMS/data/pms.pid (Нет такого файла или каталога)
DEBUG 18:21:42.493 [main] PID: 16009
```

**Comment by Nadahar** [comment]
@Sami32 It looks "normal" except that IMO the stack trace shouldn't be logged unless TRACE is enabled. I imagine that most users doen't have ```UMS.cred``` si it's a bit strange that we don't see this more often.

**Comment by Nadahar** [comment]
Actually, this is a bug. It's not that the file doesn't exist, the code attempts to create an empty "cred" file if it doesn't exist. This exception is probably thrown when UMS can't create the file. It can either be because the folder doesn't exist (```/home/asmol/.config/UMS/```) or because UMS doesn't have write permission to the folder. Permissions on Linux is a real mess, so that's a common problem.

It shouldn't be a problem that the file can't be created, but it actually crashes UMS' initialization because the ```IOException``` isn't handled. That is the *real* bug.

**Comment by Sami32** [comment]
I suspect permissions, as he played with it. No PIDmake me suspicious about how it should be handled.
Thanks for having looked at it.

**Comment by Sami32** [comment]
In fact, from my log reading experience, many users use credentials, perhaps not 50%, but many.
Me also, i was surprise to see that, as i thought like you at first.
