### ISSUE TITLE
Duration is set to zero while it shouldn't.

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1330]
A duration of zero will be set if the file have less than 1 second duration.
[alert.wav.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1117324/alert.wav.txt)

**Comment by Nadahar** [comment]
@Sami32 I'm not sure, but I think `res@duration` supports decimals. How well renderers handle it is anyone's guess though.

I've noticed that about short test audio files as well, but I doubt this is a common problem for "real" (non-test) media.

The reason is probably that the duration is simply truncated by casting a ```double``` to an ```int``` or by simply using integers for division. This is the way that's done most places in UMS' code, and both cases will result in a truncation of the decimals - that is, the value isn't rounded to the closes but the decimals is simply discarded. That means that ```(int) 0.9 = 0```.

Even if rounding was done, it would only produce a duration for the values that's >= 0.5, and the duration would be wrong. The only "proper" way to handle it is to use decimal values. That shouldn't be difficult, but I'm worried about all the badly implemented renderers that wouldn't be able to parse it.

**Comment by Sami32** [comment]
Worrying that i share. So, better to forget about this rare case.

**Comment by Sami32** [comment]
That's said, just comparing the MediaInfo value to 1s and considering equal to 1s if < 1s is easily doable.

**Comment by Nadahar** [comment]
@Sami32 Sure, you could make it even simpler and say that if the duration is 0 it should be set to 1. Whatever one does, it doesn't make it correct though. If the real length is 500 ms and we send 1 second, we send an extremely wrong value (double the real value). I don't know what consequences that would have either.

**Comment by Sami32** [comment]
@Nadahar You already know what happen, and standard mean, with a duration of zero,

For a fake duration, with a superior estimation, that's very simple, the renderer stop when no media streaming are anymore detected, whatever long is the duration sended.

After, as we said, everyone see Zenith at his door.

**Comment by Nadahar** [comment]
@Sami32 It might not be that simple, the duration is also used to calculate for example the bitrate. However, having a duration of 0 is certain to fail, while a too high estimate just might fail. The best solution would be to use the actual duration, but that would need some testing to see if it's generally accepted.

**Comment by Sami32** [comment]
@Nadahar For you the word simple exist only in dictionary.
I know that for you half second is the end of the world, so the best solution was to close and forget about.
No users should complain because they miss half second playing, isn't it ?

**Comment by Nadahar** [comment]
@Sami32 
>  For you the word simple exist only in dictionary.
🤣 
Feel free to make a PR, if it works better than the current solution I can't see why we shouldn't merge it. I'm just saying that there can (and probably will) be more serious problems than "miss half second playing".

**Comment by Sami32** [comment]
@Nadahar 
> I'm just saying that there can (and probably will) be more serious problems than "miss half second playing".

Yes, consensus :wink:
