### ISSUE TITLE
Unable to open most rar / zip files

### ISSUE THREAD

**Issue by 29988122** [UniversalMediaServer/UniversalMediaServer#1331]
Android 6.0, bubble upnp client, windows 10 creators edition
UMS using both latest beta version and stable version, same error.

Steps to reproduce:
1. start server, tick browse rar zip option
2. using bubble upnp client to browse shared rar file
3. error occurred 100% of the time.

The attachments are trace-level logs, created followed the instruction inside UMS.
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1117837/ums_dbg.zip)
![2017-07-02 14 16 33](https://user-images.githubusercontent.com/5474709/27770610-52d066e6-5f74-11e7-8f6e-3472413a6d5f.png)

Possible error line:
TRACE 2017-07-02 22:15:14.416 [New I/O worker #8] net.pms.dlna.DLNAResource End of analysis for E:\H(actual)\新資料夾\#同人誌\[C86] Pack 1-20\(C86) [40010壱号 (40010試作型)] Hitasura Summer (ToLOVEる-とらぶる-).zip
DEBUG 2017-07-02 22:15:14.417 [New I/O worker #8] net.pms.network.RequestHandlerV2 Caught exception: null

**Comment by Nadahar** [comment]
I took a look at the code for RAR/ZIP/7ZIP not that long ago, and it's very old und buggy. I don't think it has been touched for years. Unless someone want to update and fix the code, I think you'd better unpack them. There's little or no gain kompressing media files in most cases, as most formats are already very well compressed.

**Comment by 29988122** [comment]
Oh thank you, I agree with your points.
As long as this bug have been documented, I'm fine with that : p

**Comment by LucCappellaro** [comment]
It seems that archive browsing is broken since version 5.0.0. It still works in version 4.4.0.
I have identified that the commit 45337fe works, but 172bbe6 does not.

I find archive browsing useful. You have to consider that archiving is not only for compression. 
Archives can add CRCs, which help to detect corruption (due to harddrive issues).
Archives can add redundancy, which helps to repair.
Splitting archives simplifies the process of localizing broken parts, and repairing/transferring them.

**Comment by Nadahar** [comment]
@LucCappellaro Anyone that wants to fix it is free to open a pull request. As far as I remember it's not only one problem with the archive browsing, but a whole lot of stuff. A lot has changed in the way UMS works since 4.x and nobody has updated the archive browsing accordingly. In addition I found the whole approach that was taken a bit too simplified.

The commit you point to (172bbe6b2b0b2d12dd5a96bab06202da792d6849) isn't a normal commit, it's a merge commit that basically merges all or most of the changes in 5.x into 4.x, so the actual commit that "broke it" (I doubt there's one, there's probably multiple changes that's caused it) is within #445 (one or more of [these commits](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/445/commits)).

I'm not saying that arhiving isn't useful for several purposes, although what you list above can be addressed using a filesystem instead. Depending on your OS, you can create filesystems that exists within "filesystem files" much like an archive, which has redundancy and CRC checks and a lot more. Take [Btrfs](https://en.wikipedia.org/wiki/Btrfs) for example, which can do pretty amazing things - although I don't know how stable it is in its current iteration. The advantage of using filesystems for the same purposes is that any software can read and write from them, because the drivers do the "dirty work" instead. Personally I think that's a much more useful way to do it, so every software doesn't have to have its own, more or less buggy, implementation to access the content.

I'm not saying that it won't be fixed, anyone can contribute and I don't know what the other devs will choose to take on. I'm just saying that as things are now, considering all the other "challenges" that exist, this comes pretty far down on my priority list.

**Comment by SamAnholt** [comment]
This actually really works. I'm having no problems extracting my rar files at all.  But now I keep getting the errors, it says your "filename" corruted.

**Comment by SubJunk** [comment]
Browsing archives is working for me, please feel free to reopen this if it is still a bug
