### ISSUE TITLE
java.io.IOException: No route to host (sendto failed)

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1333]
```logtalk
DEBUG 2017-07-04 16:41:12.219 [UPNP-AliveMessageSender] Sending ALIVE...
DEBUG 2017-07-04 16:41:12.286 [UPNP-AliveMessageSender] Error sending ALIVE message
java.io.IOException: No route to host (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at net.pms.network.UPNPHelper.sendMessage(UPNPHelper.java:389)
	at net.pms.network.UPNPHelper.sendMessage(UPNPHelper.java:361)
	at net.pms.network.UPNPHelper.sendAlive(UPNPHelper.java:226)
	at net.pms.network.UPNPHelper$1.run(UPNPHelper.java:414)
	at java.lang.Thread.run(Thread.java:748)
```
https://github.com/UniversalMediaServer/UniversalMediaServer/files/1121378/Archive.zip

**Comment by Nadahar** [comment]
@Sami32 I don't think its necessary to create an issue for every stack trace you find 😉 

I don't know what the circumstances were when you got this error, but probably has a similar cause as  #1329. What's new is that it's logged. We should maybe lower the "severity" of these to ```Debug``` like @SubJunk suggested. I'm pretty sure this has been happening all along, but hasn't been logged before. This error indicates that UMS no longer has network connectivity to the device. The most likely explanation is if a renderer is disconnected from the network without sending a BYEBYE.

**Comment by Sami32** [comment]
It has nothing to do with your logging work, as he have this issue months before you merged it, and if i remember well you did check at his log before and your analyse at that time was different.
From his log, it seem that the renderer was not disconnected.

Yes, less and less...

**Comment by Nadahar** [comment]
@Sami32 Sorry if I misunderstood then. I this isn't caused by my new logging and isn't caused by the renderer being disconnected or turned off, there must be something wrong with his network/network configuration.

**Comment by Sami32** [comment]
Yes, is was what we've agree on in february.
And since i still see it now, it just mean that he didn't solved it, and as you're the most network skilled around ;-) i think that you're the only one that can give advices to this Mac OS X japaneese user.

**Comment by Nadahar** [comment]
@Sami32 
> Yes, less and less...

What did you mean by that?

I looked at the log again now, and it seems that UMS is unable to send multicast. I'm not sure how that happens, but he has probably disabled something that's enabled by defautl. As far as I know the problem must be on the computer running UMS, because you don't need a "route" to a multicast address - it's simply broadcasted from the network card and it's up to any listening party to pick it up or not.

What the error probably really means is "not allowed". It can either be a firewall or some system settings. Make sure any firewall on the computer running UMS is turned off and that "allow multicast" is enabled if there is such an option somewhere in the network configuration.

**Comment by Nadahar** [comment]
[This](https://stackoverflow.com/questions/1264948/link-scope-ipv6-multicast-packets-suddenly-not-routable-on-a-macbook-pro) might be related. I still find it very strange, but it looks like macOS when dealing with multiple NIC's sometimes has a problem figuring out which NIC to use (although, since we're binding the socket to ```0.0.0.0``` I thought it should broadcast on all NICs).

**Comment by Sami32** [comment]
That could be, that make sens. Mac world...
 
If i remember well he desactivate IPv6 on our asking on his router, as Japan run entirely under IPv6, it could be possible that his japaneese Mac have some specific issue has you've found.

**Comment by Nadahar** [comment]
@Sami32 I don't know where to start trying to figure this out, it's not really a UMS issue but a network issue. You could get him to report the output of the following commands, maybe that can give us some hints:
```terminal
netstat -nr -f inet
ping 239.255.255.250
```
