### ISSUE TITLE
java.io.IOException: Broken pipe for all Playstation 4 transcoding

### ISSUE THREAD

**Issue by midnightmagic** [UniversalMediaServer/UniversalMediaServer#1334]
On UMS 6.7.1; host is Ubuntu 16.04.2 LTS, 64-bit

It appears no transcoding is successful for watching anything on my Playstation 4 Media Player. Only media files which can be directly rendered can be successfully played on the PS4.

It all fails with the following snippet from the trace file, which I've copied below.

It appears this is related to #1090 insofar as the PS4 is apparently making a second connection for meta-data and this is killing the transcoding connection?

Is there anything I can do to help debug this issue so it is corrected once and for all?

Thanks!

TRACE 2017-07-06 03:53:08.093 [HTTPv2 Request Worker 15] Resume Read: readCount=0 / writeCount=14645388
TRACE 2017-07-06 03:53:08.095 [HTTPv2 Request Worker 15] Ready to Stop: true
DEBUG 2017-07-06 03:53:08.098 [HTTPv2 Request Worker 15] Connection error: java.io.IOException: Broken pipe
DEBUG 2017-07-06 03:53:08.098 [HTTPv2 Request Worker 15] Premature end, stopping...
TRACE 2017-07-06 03:53:08.136 [HTTPv2 Request Worker 15] Transfer response sent to PlayStation 4:

HEADER:
  HTTP/1.1 200 OK (non-chunked)
  Content-Type: video/mpeg
  Accept-Ranges: bytes
  Connection: keep-alive
  Server: Linux-amd64-3.13.0-103-generic, UPnP/1.0 DLNADOC/1.50, UMS/6.7.1

**Comment by Nadahar** [comment]
@midnightmagic I'm not sure I see the connection to #1090 - which is about transcoding to MP4 (which UMS currently doesn't support). 

A full (trace) log would be a good start, there's a lot that happens before the part you've included that can be interesting. The pipe creation is interesting, and so is the parsing. Since there's problems with the pipe, make sure that UMS has write permission to whatever folder is used as the temp folder (you can see which folder it in early in the log). AFAICR UMS creates the pipes in the temp folder.

**Comment by midnightmagic** [comment]
I'll re-verify tmpdir; thank you for the suggestion.

There is a significant amount of anti-privacy information in the debug.log trace file and I found it impossible to manually comb through it.

The connection to #1090 was one I followed from here:

http://www.universalmediaserver.com/forum/viewtopic.php?t=8909

In particular, this comment:

> by atamariya » Wed Nov 09, 2016 6:48 pm
> 
> When a video is transmitted with "video/mpeg" mime type, the renderer makes a follow up request for EOF meta packet where MPEG file info. is stored. This request terminates the original transcoding process causing the playback to fail. I'm surprised more people haven't reported this yet.
> 
> Subjunk is working on this. You can follow the progress here.

And the link there is to #1090 here on Github.

**Comment by midnightmagic** [comment]
I have re-verified that not only is the /tmp directory properly world-writeable and stickied, but the subdirectory described by UMS as its temporary directory is there, owned by the user running UMS, and there are files leftover from a prior transcoding attempt. The mkfifo succeeds in the debug.log; if I tcpdump the connectivity from the Playstation and show that there is a secondary connection attempt, would that be useful..?

Perhaps he points at the wrong pullreq, but I can't see any further work or other pullreqs that would be more likely to have been the target that atamariya might have been referring to..?

**Comment by Nadahar** [comment]
I'm afraid there isn't much we can do without the log file. The "second connection" that was mentioned was for MP4, not MPEG-2 TS or PS. If that was the problem, UMS wouldn't work when transcoding for anyone, which isn't the case.

When it comes to the "anti-privacy" information in the log file, it contains first and foremost the names of your shared media. If those are "confidential", you can create a folder somewhere else were you put a few media files that isn't (or rename them to something generic) and configure that folder as your shared folder. In addition your username will probably be there because it's in some folder names, but that's easy to find/replace. Your IP addresses will also show, but they are usually private IPv4 addresses which doesn't reveal anything. If you use public IPv4 or IPv6 addresses, it should be easy to find/replace the fixed part.

**Comment by midnightmagic** [comment]
Okay. I understand. I'll go through it one more time and clean out what I can find. I don't care too much about what media files are in there—the stuff I was looking at was old 3D examples and showreels primarily, and 3D-related shorts.

Thank you for the privacy outline. I saw most of what you're describing and have find-n-replaced. There were a bunch of additional bits of data including the raw <Request> structures which I couldn't manually decode. I'll add the file in a second message, and maybe when you've peeked at it, if you don't mind, I'd like to delete it.

I am happy to help debug this as much as possible; I'm a semi-competent C programmer and a highly competent Linux/*BSD user, I just don't know much about DLNA type comms, which is why I'm relying on your kindness and indulgence. :)

So did that other fellow misspeak when he said MIMEtype video/mpeg and he meant video/mp4 ?

**Comment by midnightmagic** [comment]
[ums_dbg_edited.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1128777/ums_dbg_edited.zip)

**Comment by Nadahar** [comment]
@midnightmagic What "raw structures" are you referring to? As far as I know, there is nothing in this file that contains any "sensitive" information that I could see. You can delete the file if you want to, but it would be advantageous if it could stay so that others could look at it as well.

> So did that other fellow misspeak when he said MIMEtype video/mpeg and he meant video/mp4 ?

I'm not sure exactly what statement you're referring to, so I can't say. What I can say is that according to your logfile it's being transcoded to MPEG-TS with H.264 and AC3, which is 100% "stream friendly" and all necessary information is repeated in the stream on a regular basis. This is the same format as many TV broadcasts, where reading "the end" isn't even a relevant concept.

I don't understand what goes wrong though, but I must admit that I think it smells somewhat of some kind of permission problem. It could be worth the attempt to run UMS as root to see if that changes anything.

DLNA isn't really involved where this goes wrong. The attempted process is very simple: A pipe is created with mkfifo, FFmpeg is launched reading the source file and writing to the pipe and UMS is reading the pipe and forwarding it's content to a HTTP server from which the renderer reads the (transcoded) content.

There is an error immediately after creating the pipe, and then again shortly after playback has started where Java claims that the "pipe is broken" which means that the connection is closed. It doesn't seem like UMS ever successfully reads anything from the pipe.

Do you use the FFmpeg version that came with UMS, or have you replaced it with another one (from the distro or similar)?

Trying to run the transcoding "manually" to see if FFmpeg is able to transcode the file would also be useful. Simply run:
```powershell
/opt/soft/ums-6.7.1/linux/ffmpeg64 -y -loglevel info -i /vid/3d/file.avi -bufsize 31250k -maxrate 31250k -crf 16 -ab 448k -ar 48000 -c:a ac3 -c:v libx264 -tune zerolatency -preset ultrafast -level 31 -pix_fmt yuv420p -f mpegts test.ts
```
...and see if ```test.ts``` is playable with a TS capable player like VLC.

I have a Kubuntu 16.04 VM that I use for testing where I haven't seen this problem, so this shouldn't be a "general" problem with the platform. I'm a bit lost on what's causing this, I'm hoping that testing as root and converting the file with FFmpeg can give us some something more to go on.

**Comment by midnightmagic** [comment]
Sorry. The <Result> structures I replaced with the word "sigh" :-)

Okay, so if you're saying this was an MPEG-TS super-compatible transcode, that's good enough for me. I'll stop assuming it's a similar issue and won't pursue any more tcpdumps then.

I tried running it as root. The exact same issue occurs on the exact same file, as far as I can tell without digging too deep.

I have both tried using the ffmpeg which is included with UMS, and building my own ffmpeg from scratch with all the bells and whistles included to see if it was a platform problem (sometimes platforms don't ship with a fully functional transcoder.)

I manually ran the transcoder using the command-line you supplied, put the resulting file into a directory beside the one it was transcoding, and the file plays perfectly via UMS to my PS4, actually.

So somehow the pipe creation/utilization is involved in the failure.

Would the fact that this is inside an LXC container trigger any dusty memories for you..?

I manually built a FIFO pipe via mkfifo, used the above ffmpeg command you supplied, wrote to the fifo, then cat'd from the fifo to a file beside the file I'm trying to play-via-transcode, and then was able to play that file using UMS directly on my PS4.

**Comment by midnightmagic** [comment]
Wait. I think I'm on to something. Please don't spend any more of your time trying to help me debug this problem. I'll report back if I solve it myself.

**Comment by Nadahar** [comment]
@midnightmagic The structure you replaced with "sigh" is harmless. I'm on another computer now so I don't have access to the log anymore, but it's unescaped, formatted and repeated a few lines blow where you have substituted. It's simply XML that's XML escaped because it is sent as a value in another XML. The content is about the media file, it's the information UMS gives the renderer about the media file. It's mostly "technical metadata" like size, bitrate, duration etc. in addition to things like title, author/artist etc where this applies/is available. As long as the media file itself isn't "sensitive", the information in this section shouldn't be either.

Although I did a quick readup on LXC containers now, I'm not familiar with the concept. I've stuck to machine virtualization this far, so I don't know exactly what the consequences of such virtualization might be. I wouldn't be completely surprised if some constraint/limitation in that context could lead to such a problem, we are dealing with inter-process communication after all.

I was hoping that the experiments you made would give us a lead, but it seems they didn't. I'm not doing anything more until I know the results of "something". If you fix it and if it's something that's even remotely likely to happen to somebody else, it would be nice to know what the problem was.

**Comment by midnightmagic** [comment]
I have solved the problem.

I must apologize for wasting so much of your time.

It turns out the problem is outside of UMS and my PS4 entirely. Since the size of transcoded video can't be known in advance, UMS doesn't indicate that there is more than 0 bytes to be read—which means that the simple, stupid little python DLNA proxy I forgot I'd installed on my router (between two different internal subnets) to bridge UMS and my PS4 was incapable of knowing there was more than 0 bytes in the response from UMS, and was.. taa daa..  closing the connection prematurely without reading beyond 0 bytes in the body, which would provide zero data to the PS4, and kill the connection on the UMS side.

The fix was to special-case the content-type of video/mpeg in the script and attempt to read more than 0 bytes when proxying the response back to the PS4.

Thank you kindly for your time. Again, apologies for wasting it. If it helps, your comments helped clarify and gave me a reason to properly pursue this niggling annoyance and solve it.

For future searchers, the script I'm using for the DLNA proxying is based on this here:

https://gist.github.com/02strich/5504767

The fixes I've made to it to work more correctly in my environment I will summarize here:

57a60
>                 video_content = "video/mpeg" in line

67,68c70,77
<         else:
<             yield text_content, socket_file.read(content_length)
---
>         elif content_length >= 0:
>             if video_content:
>                 data_part = socket_file.read(8*1024)
>                 while data_part:
>                     yield text_content, data_part
>                     data_part = socket_file.read(8*1024)
>             else:
>                 yield text_content, socket_file.read(content_length)

A terrible hack, really, but the gist is that we presume that if the content-type is "something to come" we should attempt to read beyond 0. This *only* works in Python because we're lucky and there is in fact more than 0 bytes left to read in the file stream. If we attempted to read beyond the header and there was nothing there, Python..  sigh..  blocks forever, even, it seems, on a closed socket, at least in my tests.

Note that I've also had to special-case the UMS multicast datagrams to ensure that only UMS UPnP gets correctly proxied with a UMS->gateway IP replacement, to the PS4—rather than its default, which is to just spam everything everywhere incorrectly.

Thanks for your time. I hope this helps people in the future! Feel free to close this issue. UMS is awesome.

**Comment by Nadahar** [comment]
Had I known there was a proxy script involved, I would have approached it very differently 😉 

That said, I don't quite understand the need for a "DLNA proxy". I (obviously) don't know how your network is organized, but "DLNA" isn't really a protocol, it's a standard that puts a lot of restrictions on the UPnP standard to make sure that compliant devices can talk to each other without too much misunderstandings. Thus, DLNA relies on the same underlying protocols as UPnP, and it's basically organized like this:
* "Public announcements" are made with multicast, which is used for discovery and broadcasting "basic capabilities". IP 239.255.255.250 port 1900 is reserved for UPnP multicast. These packages needs to reach from all involved subnets to all involved subnets, i.e work in both directions. There's a limited amount of hops a multicast package can make, defined in its TTL. [Each time the package traverses a router the TTL value is decreased and when it reaches 0 it is dropped](www.tldp.org/HOWTO/Multicast-HOWTO-2.html). UPnP dictates that the default TTL value for the multicast packets should be 4. I'm not sure if UMS does this, or if the Java default (probably 1) is used.
* Everything else use unicast and will work using standard routing.

Under normal circumstances there should be no need for a proxy as long as both the unicast and the multicast traffic is routed. I have never tested this so I don't know if UMS uses the correct TTL value, but assuming that it does it should be all it takes.

**Comment by midnightmagic** [comment]
I'd forgotten, myself. Doh.

Initially I'd installed mrouted with a simple configuration on the router but for whatever reasons it either wasn't correctly forwarding the UMS multicast traffic, or the PS4 didn't want to talk to UMS because it was on another segment (or vice-versa.)

The multicast packets did not traverse my network segments either due to a deficient mrouted installation or configuration in the router, or due to some problem similar to your description—if a TTL is involved, then a value of 1 would likely explain why mrouted was refusing to propagate them, although *currently* the IP-based TTL of the multicast packets from the UMS machine are set to 32.

The amount of time required to debug the mrouted was greater than the (other than the transcoding issue, mostly functional) simple Python userland multicast + tunnel solution in that script—which is something I can disable just by killing the script.

Though, now I have something that works, I can turn back to a functional mrouted from the perspective of the PS4 + UMS combination. I am going to take a stab at guessing that either nobody, or almost nobody, uses a functional mrouted to enable a UMS + PS4 media setup. :)

But if I do, I'll write it up somewhere and post how to do it "properly." If there is a properly and there isn't something simple I'm forgetting like the mcast membership can't function across differing subnets after all.

**Comment by Nadahar** [comment]
As stated before, I can't even guarantee that UMS does this correctly as I've never looked into the scenario. I was just thinking that the proxy solution might lead to all kind of issues, but until you meet one I guess it'll do 😉 

Regarding UMS' TTL value, there's kind of a little mess there as UMS actually use two different sockets (bound to the same address) to broadcast multicast. It has to do with history and that nobody has felt like cleaning it up I guess, but it is possible that there are two different TTL values in play. 32 seems more than sufficient though.

It should be set to 4 and made configurable IMO, but I have too much on my hands already so it will have to wait.

**Comment by Sami32** [comment]
@midnightmagic I used your log to finish a PS4 Pro renderer, it's also why user's log are useful :wink: 

Do you mind testing it and give feedback ?
You'll need to uncomment the `H264Level41Limited = false` line to get MP4 level 5.2 support (4K HDR).
Specificly external SRT subtitles tests will be much appreciated :sunglasses: 
https://raw.githubusercontent.com/UniversalMediaServer/UniversalMediaServer/08b6476f43a03be9680c1cc07f60362bdd958471/src/main/external-resources/renderers/Sony-PlayStation4Pro.conf

Thank you.

**Comment by midnightmagic** [comment]
I would absolutely love to, whatever you need, however much time it takes. :-)

I have plenty of media with external .SRT. I will test and let you know. Perhaps that should be in another github issue though? Or a PR or something.

**Comment by Sami32** [comment]
Thanks.
Not that much time :-), as 4K HDR was already tested, but i never get any report on the SRT subtitles, though the users use this renderer since i posted on the forum.
So just testing external SRT display, with or without style (italic, bold), and report if it work as expected.
That's said, as the 6.7.x seem to have some subtitles issue for some users, using UMS 6.5.3 is a safe version known to work without subtitles issue.
After, if you want test more, feel free to do it ;-D

I agree, but i was asking first. You can find the PR [here](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1200).
