### ISSUE TITLE
Memory use is not correctly triggered on Linux as it is on Windows

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1348]
On Windows, when user's computer have more then 4GB of RAM, UMS trigger to around 1.3 GB to be used, if i remember well.
But on Linux, it doesn't work.
https://github.com/UniversalMediaServer/UniversalMediaServer/files/1167579/ums_dbg23.zip

**Comment by Nadahar** [comment]
@Sami32 
> On Windows, when user's computer have more then 4GB of RAM, UMS trigger to around 1.3 GB to be used, if i remember well.

The memory assigned to the JVM can't be done by UMS, as it's configured before UMS is started. What determines how much RAM is assigned is up to the command that starts ```java```/```javaw```. The ```UMS.exe``` file is a file generated by NSIS that merely launches ```ums.jar``` with some parameters (like heap memory size). The value to use is determined by the installer during installation [here](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/external-resources/nsis/setup.nsi#L115) and can be overridden by the user.

Since there are no installer for OS X and Linux, there's no where this can be done. On Linux [this logic](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/external-resources/UMS.sh#L62) is all there is, but it's very easy for the user to edit ```UMS.sh``` if they want to assign more memory. 

For OS X the value is set to 768 MB in [the appbuilder](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/pom.xml#L1459). To change the value, they'd probably have to [edit Info.plist](https://apple.stackexchange.com/questions/179669/how-do-i-edit-an-info-plist-file). As usual Apple has made it as difficult as possible, not only is the file often locked - it's usually stored in a non-text format as well, so that you need to either install Xcode (which will allow you to edit the non-standard format) or convert it to a text-based format before editing, and then convert it back after editing. In short, OS X users should just live with the default setting 😉 

Generally, it's not very smart to assign much more than what is assigned by default for 32 bit OS'es, because even if there are enough a too high setting might still keep Java from starting. The reason is quite tragic, but it's the same for any Java program. The JVM needs to get a continuous block of virtual memory address space, which by default is limited to a 2 GB address space that is shared by all processes on 32 bit OS'es. If just a single byte is assigned somewhere "in the middle" of the free memory, it will fail and UMS will never start. On 64 bit OS'es this problem isn't really relevant, since 64 bit OS'es has much larger virtual address space and each process is [assigned its own address space](https://en.wikipedia.org/wiki/Virtual_address_space).

**Comment by Sami32** [comment]
Yes, that what's i mean.
> but it's very easy for the user to edit
LOL As you already know, "easy" is a vague individual concept :wink:

**Comment by Sami32** [comment]
BTW, thanks, i didn't know that it was different for other OS, as i only checked for Windows long ago.

**Comment by Nadahar** [comment]
@Sami32 
> LOL As you already know, "easy" is a vague individual concept 😉

True, but the Linux user doesn't have much choice. So many things needs to be configured manually in a text editor in Linux to get them to work, and scripts often have to be edited as well. It's a normal part of the "installation process" on Linux, which is also why Linux is to difficult for many people.
