### ISSUE TITLE
[BUG] Settings are stored in wrong folder, bad path variable (+ portable settings)

### ISSUE THREAD

**Issue by 444nonymous** [UniversalMediaServer/UniversalMediaServer#1363]
The settings in windows are stored in C:\Documents and Settings\All Users\UMS. 

That's a wrong path no matter what. The right path is always the variable "%APPDATA%". It links to the current user profile "C:\Documents and Settings\{username}\Application Data\USM".  For all users it should be "C:\Documents and Settings\All Users\Application Data\USM"

And if you are going to fix this, please also create a portable settings option. Once installed UMS is really portable, being a java program. It would be great to store the settings inside the program folder. It could be C:\Program Files\USM\Portable or C:\Program Files\Settings, etc

Thanks

**Comment by 444nonymous** [comment]
Edit: C:\Program Files\USM\Settings

**Comment by Nadahar** [comment]
@444nonymous It's ```UMS```, not ```UMS```. You can edit your previous comments by clicking on the little pencil in the upper right corner.

The right path isn't always ```%APPDATA%```, that depends on the application (an in some cases the user's choice during installation). UMS use ```%ALLUSERSPROFILE%```, which maps to ```C:\ProgramData``` by default in some Windows versions. That's Microsoft's choice, not our.

I don't know the exact historical reason why ```%ALLUSERSPROFILE%``` was choisen instead of ```%APPDATA%```, but I suspect that it has to do with the possibility to run UMS as a Windows service. When a service is installed, it uses some built in account (```Local System``` or ```Local Service``` I think) by default. Very few users change this, and this user is never the same as the logged in user. 

This would lead to UMS running with different profile folders when running as a service vs as an application, which would be sure to cause a lot of confusion. UMS also often requires more configuration than the typical program using ```%APPDATA%```, which would make it likely that people using multiple user accounts wouldn't want it to have separate configurations. In any case, there's no "right" and "wrong" when it comes to using a shared configuration or not. 

```C:\Documents and Settings\All Users\Application Data\``` is the default value for ```%ALLUSERSPROFILE%``` for Windows XP, but hasn't been that since then AFAIK.

UMS already has a "portable settings option". When you start UMS, you can specify whatever profile folder you want with:
```powershell
UMS.exe profile=<path to profile folder>
```
You can specify this in your UMS shortcut, use it in a script or type it manually. ```%ALLUSERSPROFILE%\UMS``` is only the default when no profile folder is specified.
