### ISSUE TITLE
Option to inlcude a few useful metadata in the tumbnail

### ISSUE THREAD

**Issue by 444nonymous** [UniversalMediaServer/UniversalMediaServer#1368]
So, I don't think filenames should be changed. Just keep as simple as possible using filebot or UMS option "beautify". Both get the same result and style.

But the simple thumbnail showing the extension could also show the time length. It could also work for generated thumbnails. That's the main data I find missing when playing movies, how long they last.
But there could be other options to show subtitle info, etc, instead of renaming files, which gives problems like in https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1364

I'm not sure if it's the client / renderer the one that should get and show that info, or if it has to be provided by the server. I did not find any DLNA client in Samsung or LG TVs showing it. Just filename and icons. So I thought it could be implemented.

**Comment by valib** [comment]
@444nonymous filenames are not changed. What is changed is how it will be shown on the renderer. If you don't use `Prettify filenames` option the filename will be shown as it is and it is about the renderer if it show the whole filename and additional info.
The idea to show time length in the thumbnail seems good but I am not sure if it will be readable on the small thumbnails. @UniversalMediaServer/developers what do you think.

**Comment by Nadahar** [comment]
Most renderers show the length themselves. UMS gives this information to the renderer during browsing, so it's really up to the renderer to display this. Not all renderers do it though, which is why we have ```ShowDVDTitleDuration = true``` I guess. A similar setting that also applied to non-DVD titles might be a solution. I'm afraid putting this information in the thumbnail could be slow and have a lot of challenges:

* Many renderers use small thumbnails, in fact the standard DLNA thumbnail is maximum 160 x 160 pixels.
* Thumbnails are offered in many sizes, so to avoid resizing the text making in unreadable it would have to be modified when the thumbnail is retrieved - which would be slow.
* Not all renderers need this information, so it couldn't touch the cache.
* Text aren't readable unless there's a certain contrast to the background. It would be quite challenging to figure out what color to use or where to put the text so that it was readable.
* If would probably be very ugly, so we would need to use anti-aliasing. That would make the text even less readable and the process even slower.

**Comment by SubJunk** [comment]
We have an older version of 7.0.0 that wrote text on thumbnails and solved a lot of the challenges with that (automatic font sizing to fit different resolutions, contrast control by using a dark overlay, etc.)

However like @Nadahar said most renderers already display that information and we provide it to them, so it's strange yours doesn't, @444nonymous 

I'd be ok with merging a pull request for that feature if someone makes it optional

**Comment by 444nonymous** [comment]
If it's just my TVs, then forget about it. I was not sure if it was a server or client thing. 

If the all the metadata is passed by the server, it should be the client's job to display it in a proper way.

**Comment by valib** [comment]
@444nonymous see https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1364#issuecomment-324103846

**Comment by SubJunk** [comment]
@444nonymous given your last reply I'll close this issue since it seems concluded. If you have anything more to add feel free to reopen
