### ISSUE TITLE
Prevent SQL injection.

### ISSUE THREAD

**Issue by kevincox** [UniversalMediaServer/UniversalMediaServer#1376]
This is not sufficent SQL escaping to stop attackers. A proper SQL escaping/sanitization function should be used.

https://github.com/UniversalMediaServer/UniversalMediaServer/blob/c8d578f93d79e92edc1733a825fb1035f91f28b6/src/main/java/net/pms/dlna/virtual/MediaLibraryFolder.java#L97

**Comment by Nadahar** [comment]
@kevincox UPnP/DLNA is meant for LAN only and won't work via the internet anyway (because of reliance on multicast). As such, it's hard to see a relevant case for SQL injection. In addition, UPnP/DLNA doesn't support authentication and is by design "open" and "unsecure" in that any query will be answered without any need for identification. It anyone would utilize SQL injection to modify the database, all one would achieve would be to possibly "corrupt" the database. I have yet to see why anyone would bother to do that.

**Comment by kevincox** [comment]
If I understand correctly this could be triggered by a filename that was downloaded. You are right that it isn't the biggest attack vector in the world but it is still there. Also givining the atacker the ability to run arbatary SQL now they have a lot of leverage to exploit bugs in sqlite which could lead to RCE.

**Comment by Nadahar** [comment]
I'm not saying there isn't a way to exploit something (that's a claim I'm very careful with), I'm just saying I don't see a practical case. Updating this particular code would probably be easy enough, but I don't think the database code has been written with such attacks in mind at all.

We're not using sqlite but H2 (which is Java). I don't know how secure H2 is against RCE, but I doubt any attack designed for sqlite would work.

I don't want to manually check all references to this method using GitHub so I can't say for sure exactly what is fed into it, but it sounds reasonable that it is fed file/media names. I still have a problem seeing a real-world situation where somebody would upload a file with a filename that is designed to exploit use specifically with UMS, that somebody would download and use that file with UMS and on top of that anything "useful" (for the attacker) could be achieved by manipulating UMS' database. As far as I know, SQL injection is usually used to retrieve or manipulate information in databases used by web pages.

**Comment by SubJunk** [comment]
Looks like it would be easy to make it more secure so please submit a PR for it @kevincox :) I agree with @Nadahar the risk is very low but I would merge the change if it was submitted

**Comment by Nadahar** [comment]
Although I maintain that this is very far fetched, it seems that RCE in H2 is very straigt forward:

> H2 allows stacked queries to be performed. In addition, the underlying H2 database offers the ‘SCRIPT TO ‘ construct. Through this it is possible to store arbitrary Java code into a newly created .jsp script.
> 
> A remote attacker, could then create an arbitrary script into an accessible web path and execute arbitrary code/commands against the target server.
>

**Comment by valib** [comment]
It is not possible to use SQL injection in the UMS. We manage all requests in the `Request.java` or `RequestV2.java` and they as a respond of the request are trying to find relevant `DLNAResource` which is based only on the GlobalRepo ID not the filename (which is not the real filename of the media) when only the attack could be performed. If the DLNAResource is parsed then it has access to the database to use stored information or thumbnails otherwise it would fail.
