### ISSUE TITLE
java.io.InterruptedIOException: null

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1387]
```logtalk
INFO  2017-09-07 16:08:36.203 [tsMuxeR.exe-47] Process "C:\Program Files\Universal Media Server\win32\tsMuxeR.exe" has a return code of -1073741795! Maybe an error occurred... check the log file
DEBUG 2017-09-07 16:08:36.218 [Thread-241] IPC pipe interrupted after writing 0 bytes, shutting down...
TRACE 2017-09-07 16:08:36.218 [Thread-241] 
java.io.InterruptedIOException: null
	at java.io.PipedInputStream.awaitSpace(Unknown Source)
	at java.io.PipedInputStream.receive(Unknown Source)
	at java.io.PipedOutputStream.write(Unknown Source)
	at net.pms.io.PipeIPCProcess.run(PipeIPCProcess.java:81)
DEBUG 2017-09-07 16:08:36.218 [tsMuxeR.exe-47] Stopping process: ffmpeg.exe-45
```

**Comment by Nadahar** [comment]
@Sami32 Not all exceptions are errors, especially not when in trace mode. The pipe was simply interrupted, probably because UMS was being shut down.

**Comment by Sami32** [comment]
Thank you for your input.
That's possible, i still need to look deeply on that later.

**Comment by Nadahar** [comment]
@Sami32 An ```InterrupedException``` is a "special" kind of exception that doesn't indicate anything wrong at all, it simply means that the thread in question was [interrupted](https://docs.oracle.com/javase/tutorial/essential/concurrency/interrupt.html). Read the link to know what interrupts are and how they work, which is necessary if you want to understand ```InterrupedException```s. They generally don't have a "message" part (as it's not an error), which is why the message is ```null```. That's not an error either, and will almost always be the case for ```InterrupedException```s.
