### ISSUE TITLE
Buggy Filewatch in v7 with exceptions

### ISSUE THREAD

**Issue by ExSport** [UniversalMediaServer/UniversalMediaServer#1390]
@SubJunk @valib @Nadahar
Hi guys
I tried to install  **v7rc1** but it is quite "buggy" for novice or non-techie user.
After clean installation all disks in system are automatically shared and monitored. Due to exceptions on non-readable content it wasn't easily possible to force UMS save changes made in GUI so only option was to edit UMS.conf file manually to not kill all disks in the system by reading from them.
So I changed: **folders =D:\\!_MEDIA-FOLDER_!**
Restarted UMS but exceptions logging continued...
```12:47:31 DEBUG Added file watch at B:\Drivers\IntelVGA: B:\\**
12:47:31 DEBUG Added file watch at B:\Drivers\IntelVGA\DisplayAudio: B:\\**
12:47:32 DEBUG Added file watch at B:\Drivers\IntelVGA\Graphics\Lang\zh-TW: B:\\**
12:48:21 INFO  java.nio.file.AccessDeniedException: B:\System Volume Information
12:48:21 INFO  	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
12:48:21 INFO  	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
12:48:21 INFO  	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
12:48:21 INFO  	at sun.nio.fs.WindowsDirectoryStream.<init>(Unknown Source)
12:48:21 INFO  	at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(Unknown Source)
12:48:21 INFO  	at java.nio.file.Files.newDirectoryStream(Unknown Source)
12:48:21 INFO  	at java.nio.file.FileTreeWalker.visit(Unknown Source)
12:48:21 INFO  	at java.nio.file.FileTreeWalker.next(Unknown Source)
12:48:21 INFO  	at java.nio.file.Files.walkFileTree(Unknown Source)
12:48:21 INFO  	at net.pms.util.FileWatcher.addRecursive(FileWatcher.java:212)
12:48:21 INFO  	at net.pms.util.FileWatcher.add(FileWatcher.java:143)
12:48:21 INFO  	at net.pms.dlna.RootFolder.discoverChildren(RootFolder.java:165)
12:48:21 INFO  	at net.pms.configuration.RendererConfiguration.getRootFolder(RendererConfiguration.java:518)
12:48:21 INFO  	at net.pms.PMS.getRootFolder(PMS.java:163)
12:48:21 INFO  	at net.pms.PMS.init(PMS.java:824)
12:48:21 INFO  	at net.pms.PMS.createInstance(PMS.java:1148)
12:48:21 INFO  	at net.pms.PMS.main(PMS.java:1308)
12:48:21 ERROR A serious error occurred during Universal Media Server initialization: null
```
As you can see it checks not only shared folder but all volumes in the system so exceptions continue!
It seems it is due to empty/null value in **folders_monitored** what means for UMS to watch everything regardless shared folders.
When I changed it to: **folders_monitored =D:\\!_MEDIA-FOLDER_!**, watching non-shared folders stopped.

So it seems there are two things to be fixed:
- change behavior for empty/null **folders_monitored**
- fix generated exceptions for unreadable volumes/disks/folders/files
- don't share everything from start and don't try to watch all of them (should be fixed by fixing the first one)

Main reason why I spotted such destruction for UMS was because on tested system there are empty CDROM drive, shared root volumes from different PC so there is lot of unaccesible folders like "Documents and Settings", "System Volume Information", etc... under 12 drive letters.
So I was in state that I wasn't possible to change any settings in UMS GUI as exceptions or many background processes blocked/denied/slowed saving process of settings.
Editing only **folders** option in UMS.conf wasn't enough to get rid of exceptions what led me to **folders_monitored** settings 👍 
Are you able to reproduce it?

**Comment by Nadahar** [comment]
I think this is closely related to #1389. Thanks for a detailed description @ExSport 👍

**Comment by SubJunk** [comment]
Great, thanks for this

**Comment by SubJunk** [comment]
Please test the latest 7.0.0 branch and let me know if that fixes it for you

**Comment by ExSport** [comment]
Hi @SubJunk @Nadahar @valib 
Great, seems exceptions fixed and also behavior when every volume in OS was monitored when **folders_monitored** was empty.
But as I am here with UMS many years but last few months I had zero time to track progress here, I experienced major change in UMS behavior?
I mean that in past only browsed folders were parsed or all shared folders were parsed when user forced rescan by magnifier icon in UMS gui.
Now I see after clean install that before you are able to configure UMS settings and restart it (also with selecting only specific folders to share), UMS parses any files in OS and overloads whole system as it takes some time to the user and also UMS doesn't stop to parse "garbage=everyting" until UMS is restarted what can be done by user after 10 or 20minutes?
So it parses non-media files unnecessarily and DB grows in size with unwanted items (are there also stored non-parsed/non-media files in DB?).
Not sure it is good behavior as parsing e.g. whole C:\WINDOWS folder is waste of time and stored garbage in UMS DB.
If there is requirement of initial scan of all files (why?), then it should be done after shared folders are changed to anything else than **ALL FOLDERS** or by default not to share anything until user will select specific ones (and will do a restart to changes take in effect).
Btw. big thanks to all who still working on this project (incl. @Sami32 and others!)

**Comment by ExSport** [comment]
Btw. e.g. changing shared folders will change icon of "Restart Server" to **RED**.
From my point of view I am not sure user will spot it so will not know that restart is needed to take changes in effect. Also it doesn't work for changing shared folders :)
By default UMS scans all folders in system. You will change **shared folders**, icon will go to **RED**, you will click on it so server is restarted (not whole APP!). UMS still parses all files in the system! Only full UMS restart will stop parsing non-shared folders.

**Comment by SubJunk** [comment]
@ExSport if the file isn't recognized by UMS (isn't an image, audio or video file) I don't think it is added to the database. If it does that it's a bug.

One feature I want is to have the shared folders chooser to display in the first time startup wizard, since that should almost always be done. I think it is important to show all by default but strongly encourage users to specify them instead.

**Comment by ExSport** [comment]
@Subjunk I don't say they are stored but that DB grows with unwanted content before user is able to change sharing and restart UMS.
So e.g. c:\Windows folder is scanned and some unwanted files are stored there like small pictures or sound files etc...
Will try to scan some non-media folder with many files if DB will grow or not. Maybe not but definitely scanning root disk with system and indexing system "icons" and "sound" is unexpected behavior for user.
I think nobody will know they must reconfigure shared folders, restart UMS (full restart!) And delete media DB as it already includes garbage:)

**Comment by ExSport** [comment]
Btw. If user will not set specific shared folders I encourage to ignore some well known folders like WINDOWS, PROGRAM FILES, TEMP,...
Btw. why scanning is forced in v7 as in v6 only browsed folders were indexed by default?
Thx

**Comment by SubJunk** [comment]
Yeah it is probably a good idea to have a blacklist for those common folders in that case, and yes it is a bug that the program needs a restart to have folder sharing settings changed.

**Comment by SubJunk** [comment]
Scanning is forced in v7 to ensure the "Media Library" is kept up to date. I will work on it more to make it faster too

**Comment by SubJunk** [comment]
We can probably set a default value for our existing setting "folders_ignored"?

**Comment by ExSport** [comment]
Anything what will stop spamming DB with unwanted items is OK, e.g. not to start parsing files at "initialization" of UMS (first start of UMS) as in most cases user will reconfigure ALL FOLDERS to specific ones, so parsing and filling DB with garbage will not be initialized. If user will not change shared folders, on next restart it can parse whatever:)
Hard to say the best way how to do it but applying some blacklist is good idea [filter c:\windows; *:\temp; C:\*\temp\* etc...] 👍

**Comment by ExSport** [comment]
About DB "garbage" :)
I loaded it in DBVisualizer and got this info:
```
FILE:	medias.mv.db
SIZE:	117 MB
ROWS:	4698

One record example from /MEDIAS/PUBLIC/TABLE/FILES/COLUMN_NAME:
IMAGEINFO = 4234 bytes
THUMB = 100424 bytes

FILENAME                                
--------------------------------------- 
...
B:\Drivers\WLAN\Docs\HUN\warning.jpg    
B:\Drivers\WLAN\Docs\Icons\AdHoc.jpg    
B:\Drivers\WLAN\Docs\Icons\all.jpg      
B:\Drivers\WLAN\Docs\Icons\arrows.jpg   
B:\Drivers\WLAN\Docs\Icons\caution.jpg  
B:\Drivers\WLAN\Docs\Icons\conicon3.jpg 
B:\Drivers\WLAN\Docs\Icons\conicon5.jpg 
B:\Drivers\WLAN\Docs\Icons\conicon.jpg  
...
B:\Progs\Qt\Docs\Qt-5.6\qtcore\images\cursor-hsplit.png
B:\Progs\Qt\Docs\Qt-5.6\qtcore\images\cursor-ibeam.png
B:\Progs\Qt\Docs\Qt-5.6\qtcore\images\cursor-openhand.png
B:\Progs\Qt\Docs\Qt-5.6\qtcore\images\cursor-sizeall.png
B:\Progs\Qt\Docs\Qt-5.6\qtcore\images\cursor-sizeb.png
B:\Progs\Qt\Docs\Qt-5.6\qtcore\images\cursor-sizef.png
B:\Progs\Qt\Docs\Qt-5.6\qtcore\images\cursor-sizeh.png
B:\Progs\Qt\Docs\Qt-5.6\qtcore\images\cursor-sizev.png
B:\Progs\Qt\Docs\Qt-5.6\qtcore\images\cursor-uparrow.png
B:\Progs\Qt\Docs\Qt-5.6\qtcore\images\cursor-vsplit.png
B:\Progs\Qt\Docs\Qt-5.6\qtcore\images\cursor-wait.png
B:\Progs\Qt\Docs\Qt-5.6\qtcore\images\cursor-whatsthis.png
B:\Progs\Qt\Docs\Qt-5.6\qtcore\images\home.png
B:\Progs\Qt\Docs\Qt-5.6\qtcore\images\ico_note_attention.png
...
```
The majority is locked by THUMBS and IMAGEINFO.
Btw. what is stored in IMAGEINFO?
Also is it not better to create thumbs as separate files instead of DB? Or some benefit to make it available?
Thx

**Comment by Nadahar** [comment]
@ExSport ```ImageInfo``` stores metadata about the source image needed to know what formats/sizes to offer to the renderer and how to properly convert/transcode the image before sending it. The reason it is that "big" is because it is serialized. Serialization isn't very size-effective, but it's relatively fast and the only other option would be to add a lot of new fields to the database (I'm guessing somewhere around 30). Instaed, the whole instance is serialized and stored as a "binary representation".

Storing the thumbs as separate files aren't really viable either, they are also serialized instances of both the metadata for the thumb and the pixel data either as JPEG or PNG.

**Comment by ExSport** [comment]
@Nadahar
Thanks for explanation. I asked because I am not sure what behavior is for DB when UMS starts.
If it must be completely allocated in memory then there will be lot of out of memory errors for bigger DB as heapsize is quite small by default.
I remember such errors years ago with much bigger sizes like 2GB when you clicked on magnify icon as all files had to be parsed immediately(not by browsing), stored in DB and also cached in memory as it was like actually browsed folders so all thumbs were in memory.
But have to say it was probably at times when UMS stored RAW thumbs in full size what was embedded jpeg with 3 and more MB in size:)

**Comment by Nadahar** [comment]
@ExSport Yes, when in reworked "everything images" in #1061 I changed it so that they are stored compressed. That said, the database doesn't keep it all in memory so I don't think that should lead to out-of-memory errors. The database caches something in memory, but is supposed to be "smart" about it and adjust to the available memory.

**Comment by ExSport** [comment]
In past all what was actually browsed was cached in memory, it means mediainfo,thumbs,...and when memory got full, parsing failed.
If you forced it by clicking on magnify icon, you hit error much sooner or you had to restart UMS and rescan library again (already parsed files were skipped).
If UMS is now able to release old cache from memory when getting full (some garbage collector to release part of memory), then great! :)
It will avoid out of memory errors when initial parsing is started on bigger libraries with default heap size of only 768MB if I remember well.

**Comment by Nadahar** [comment]
@ExSport That problem is there still. There's no easy way to fix it, it's a fundamental design flaw inherited from PMS. It's not relatede to the database though, the database isn't loaded into memory but whatever you browse is. The same goes for scanning folders.

I have said that I think it's begging for trouble to make UMS scan all "by default", I think it will lead to a lot of problems for many users. Some will get out of memory errors, others will just have an unresponsive/slow computer for several hours after starting UMS, and I'm betting many won't be able to transcode anything until the scanning is over.

@SubJunk doesn't seem to think it's a big problem though, according to him the scanning is quick as soon as the files are already found in the cache (so that they don't have to be re-parsed). I'm not so sure that's true for big libraries and/or with slow (maybe networked) drives.

Releasing/GC'ing the old resources is very hard as it is now, because there are a multitude of references to objects which all need to be cleared. Basically, a much stricter structure would be needed to be able to do that. In addition we'd need some rules as to what constitutes an "old" resource and when to release it.

**Comment by SubJunk** [comment]
Yes we definitely have the issue where eventually the memory will fill up if you do manual scanning. However there is only one automatic scan that happens now, when the program starts up. When that is done, it uses the filewatchers to only process new files so there is no scanning done.

I'm happy for suggestions and even more happy for code to be contributed that helps the scanning be faster and use less memory

**Comment by ExSport** [comment]
@SubJunk 
```
However there is only one automatic scan that happens now, when the program starts up
```
And that can be issue for users. If they will not set anything, UMS will parse all files in system and definitely in short time will get out of memory as default heap 768MB will be filled quite fast.
Also when user will set specific folders but there will be huge amount of pictures or movies, in quite short time it again fill whole memory by cache so user will get sooner or later out of memory error.
For novice, this state will lead to uninstalling UMS as it is buggy, nothing works, memory exceptions and user can't imagine why it is happening and how to avoid it....

**Comment by Nadahar** [comment]
@SubJunk "Only one" scan is more than enough if that scan causes UMS to crash or to be busy for hours. I'm quite convinced that a lot of users will abandon UMS because of this. 

The memory consumption is just one part of the problem, even if that doesn't happen the fact that you have to start UMS x minues/hours before you want to use it might make it unusable for many.

I have no idea how to solve this without doing major refactoring of the basic functionality of UMS. As I see it, UMS simply can't be used like this unless a lot of things are changed - which would mean in a distant future. I'm certainly not going to do all that alone, and I can't even comprehend the number of things that will break during such an endeavour.

To lessen the memory impact without refactoring "everything", it might be possible to experiment with WeakReference in GlobalId, but I don't have the overview to know all the implications of this (or how well it would work). There's a fundamental problem in the way UMS generates resource ids. As per UPnP these ids should be consistent, ideally also across restarts. That means that you have to keep a reference to the id once it's been used. The obvious way to do this is to store it in the database, but that's very far from how the current implementation is. Another problem is all the "virtual"/dynamic resources that don't have their own entry in the database. Their ids need to be consistent too, and I don't know how that could be solved. There would have to be a consistant way to creates ids for dynamic resources that always ended up being the same, but that might not be possible in reality.

This fundamental problem is one of the reasons why all used resources are kept in memory. Since UMS creates "dynamic" resource trees per renderer, that also means that this must be maintained *per renderer*. It's basically a mess without any good quick fixes.

One possibility, although logically far from ideal, is to implement a cache solution like EhCache (like @atamariya has done). That's not without it's challenges though (it simply crashes for both @valib and me), and requires that Serializable must be implemented for everything that is to be cached. It doesn't solve the fundamental problem, but it avoids out-of-memory errors.

**Comment by atamariya** [comment]
I must admit full root folder scanning can cause user panic as has been noticed by @Nadahar and @valib on my branch. Root folder scanning, if nothing is configured, should be avoided.
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/1a648a0ac25a9b7a41e40c146b9145973742df7a/src/main/java/net/pms/dlna/RootFolder.java#L291-L293

Other steps may include -
-  single root folder view for all renderers
- limiting the scan threads and queuing them up
- not starting the scan on main thread
- caching and recreating the objects on demand from DB etc.

**Comment by SubJunk** [comment]
I agree with you guys, I was simply clarifying. We clearly have an issue here and 7.0.0 is not as close to release as I thought it was. We have had many releases so far spanning many months, and it's only now that I'm hearing about these issues, so now I can fix them.
