### ISSUE TITLE
Wrong Chromecast 2015 recognition

### ISSUE THREAD

**Issue by babywin** [UniversalMediaServer/UniversalMediaServer#1398]
Hi guys,
My Chromecast 2015 is worng detected as a Chromecast Ultra.
I've fix this by deleting the Ultra conf.
Please fix this in next releases.
Is annoying to do this every time you update, and also are so many people who can't figurate how to do it.
Cheers.

**Comment by Sami32** [comment]
Ho @babywin 
Please post your log before the next release.
It's annoying to every time ask for log, and also are so many people will not beneficy from a fix because no one with Chromecast have still posted a log.
[Here](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/4307d45adac8b8172e07f0e4971405a2cf9be630/CONTRIBUTING.md) are the steps to follows.

**Comment by babywin** [comment]
The requested log, but as I can see, the bug is not listed on it.
I've attached a screenshoot of the wrong recognition.

[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1367128/ums_dbg.zip)
![portapapeles-1](https://user-images.githubusercontent.com/10915570/31319963-cf491b94-ac42-11e7-947c-4ff3918cb504.jpg)

**Comment by babywin** [comment]
Same files, but for the offical release @Sami32 
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1367138/ums_dbg.zip)
![portapapeles-1](https://user-images.githubusercontent.com/10915570/31320139-be96b74a-ac45-11e7-8b58-5d60deb1075c.jpg)

**Comment by Sami32** [comment]
@babywin Nice to have tried, but you have misread the point 3:

> 3. Choose "**Trace**" from the "Log Level" dropdown at the bottom

So we are missing near all debugging informations...
For debugging Chromecast you can find informations in our [Wiki](https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/ChromeCast).

**Note**: One of my build that you've downloaded on the forum and tried, will not work, because you didn't followed the instructions that has been given with.

**Comment by babywin** [comment]
@Sami32 I've marked the TRACE option, but as I say, an incorrect detection of Chromecast v 2015 as a Chromecast Ultra does not leave any description in the LOG

**Comment by Nadahar** [comment]
@babywin Whatever you did, the files you have attached above are not "recorded" with ```Trace``` log level activated. That's easy to see, because most of the log is missing.

**Comment by Sami32** [comment]
Could be reopened when a trace log will be given.
