### ISSUE TITLE
Disable Web UI (or set root dir to somewhere else)

### ISSUE THREAD

**Issue by alex9099** [UniversalMediaServer/UniversalMediaServer#1409]
Hi, i would like to have the server open to the internet, but having the webui show all my files is a little bit unsafe, 

is there any way to disable it or at least change the root directory?

**Comment by Nadahar** [comment]
@alex9099 It's a bit hard for me to understand exactly what you want to do. You can disable the web interface by setting ```web_enable = false``` in UMS.conf. You can also change to port used. I don't think you can change the "root" of the web interface if that's what you're asking, but you can certainly change what UMS is sharing so that it doesn't share your root folder on the harddrive - if that's what you're asking.

There's also possible to require codes to access files or folders in UMS, but I'm not familiar with how this works myself.

All this said, there's really no point of exposing UMS to the internet if you don't want to share the web interface. UPnP/DLNA (which is the "main protocol" used by UMS) doesn't work across routers unless they are configured especially for that, and there's no way to get the routers out on the internet to do that.

I assume the reason you want the server open on the internet is to run other services on it that you want to be reachable?

**Comment by alex9099** [comment]
exactly,there are other servers on this computer, the main problem is that the web interface exposes the whole file system, and it is possible to download every file (that the server has access to)

**Comment by Nadahar** [comment]
As stated above you can disable the web interface entirely. You can also simply block the port the UMS web interface is running on in your firewall, you should never expose "everything" to the internet anyway.

**Comment by SubJunk** [comment]
The answer to use `web_enable = false` was provided, closing
