### ISSUE TITLE
Universal Media Server 6.7.4 - Build failure at git-commit-id-plugin: .git directory is not found!

### ISSUE THREAD

**Issue by GvMariani** [UniversalMediaServer/UniversalMediaServer#1425]
Trying to produce a new package for Rosa Linux Fresh 2016.1 (a rpm-based Mandriva derivative) on x86_64, using openjdk-1.8.0 and maven 3.3.9.
After installing the source tarball, downloaded from github, I proceeded according to the build instructions in the Wiki, skipping only the git passage (because I was interested at the one stable release...).
However the "mvn package" build process fails at the git-commit-id-plugin time with the following error message:
****************
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.2:revision (default) on project ums: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
****************
Downloading a snapshot of the master head and using it, did not solve the problem: I got the same error...
And obviously trying to cheat by manually adding a fake ".git" directory to the sources only generated another error, because it did not contain what was needed.

Next I launched maven with the -X  switch and found that git-commit-id-plugin was configured by default to fail in case of git errors, because both failOnNoGitDirectory and failOnUnableToExtractRepoInfo were set to "true"...
Manually setting the above two options to "false" in the main pom.xml file solves the problem and allow the build to finish successfully.

I must conclude that there is at least a bug:
* or in the Wiki build instructions, because the git clone/update pass is not optional at all, given that nor the released source tarball, nor the github-produced head snapshot contains the directory that git-commit-id-plugin wants;
* or in the main pom.xml file, because as-is it implicitly assumes that the build happens in a true git repository, while the build process should work OK also with a simple source tarball.

If needed I have a full log of a failed build with the maven -X switch...

**Comment by Nadahar** [comment]
@GvMariani I think you have a good point. We never build UMS outside a git repo, so I doubt we've ever thought of this. The git commit id is stored as part of the version information and can be helpful when troubleshooting.

I'm not sure what's the best solution, while we appreciate having the commit id in the log for support cases it seems unreasonable that the build should fail because it's missing. 

@UniversalMediaServer/developers What's the best approach?

**Comment by Sami32** [comment]
I don't know what should the best choice, but i'm in favor of modifying the _pom.xml_ file, because it shouldn't fail for Git repository missing, and if a user report issue with a log without Git commit number, we can always ask him to post a new log while using an official stable build, IMO.

And as very few users will build UMS themself, i don't see any problem with this choice.

**Comment by GvMariani** [comment]
Thank you for you attention...

If I can add my 5 cent from a distro packager POW, I would say that:
1) while Nahadar is right when saying that "it's easy to build a stable version from a git repo by simply checking out a tag", when you have a lot of things to package or to update at the same time, it is way faster picking up a release tarball and building it directly; we also have some scripts to automate the discovery of new releases and the downloading of the relative source tarball...

2) Moreover, IMO, strictly requiring to use directly the git repository to build a stable release not only contradicts what the build instructions say on the Wiki (easily fixable...), but also renders useless to have source tarballs published on the site (because, in the case above, they cannot be built)...

3) Given all the above, I would second the choice of modifying the pom.xml file.
Anyway, it's your call...

**Comment by Nadahar** [comment]
@GvMariani I agree that something must be done. The published source tarball was added recently, so I doubt anyone has thought of that. I'm pretty sure you're the first to try to build it, and I agree that it's useless the way it is now.

The only thing I'm not a fan of is that it will be packaged without the commit id, because it could potentially mean that we could have many users running these versions increasing the chance that we don't know what exact commit is being used. Stacktraces are dumped in the log when exceptions are thrown, and those reference line numbers. Without knowing the exact commit, it's impossible to figure out which line of code caused the exception.

I'm assuming that you script most or all of this, but would it be any harder to script it using git? As soon as you have found the new version (which probably is the hardest part), checking it out should be trivial and faster than downloading the whole tarball. This is ofcourse entirely up to you, it's just not what I'd call an "ideal" situation when I think of many support requests without the commid id.

I assume you have figured out the dependencies under Linux? Our documentation isn't ideal here, and the requirements to get especially tsMuxeR to run seems to vary from distro to distro. It is 32 bit, so it relies on some 32 bit libraries.

**Comment by GvMariani** [comment]
I understand your worry about the support request.
Well as an alternative, I could use the binary tarball, instead of the source one: I guess this one has the commit id thing enabled...
We are not Arch Linux or Gentoo: the reason we prefer building the sources is to make sure that the new program is OK with the libraries actually present in the distro; but in this case, being java, the issue should not happen (modulo the openjdk compatibility)...
This would solve my and your problem, but the fact remains: the sources from github (and even a git arch product, I guess), cannot be built as-is...

About tsMuxeR: as shown in the following thread on doom9.org (https://forum.doom9.org/showthread.php?t=168539&page=82), finding the needed 32bit libraries is very easy: you will need only to type "ldd tsMuxeR" in a terminal, after decompressing the binary with upx ("upx -d tsMuxeR").
In my PC (Rosa Linux, but it should be the same as OpenMandriva and Mageia) this prints:
linux-gate.so.1 =>  (0xf7f5c000)
libpthread.so.0 => /lib/libpthread.so.0 (0x48d4d000)
librt.so.1 => /lib/librt.so.1 (0x49028000)
libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0xf7e54000)
libm.so.6 => /lib/libm.so.6 (0x48f09000)
libc.so.6 => /lib/libc.so.6 (0x48b66000)
/lib/ld-linux.so.2 (0xf7f5e000)
libz.so.1 => /lib/libz.so.1 (0x492ff000)
libbz2.so.1 => /usr/lib/libbz2.so.1 (0x496ee000)
libpng16.so.16 => /usr/lib/libpng16.so.16 (0x49033000)
libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0xf7db5000)
libglib-2.0.so.0 => /lib/libglib-2.0.so.0 (0x4be49000)
libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x4933e000)
libpcre.so.1 => /lib/libpcre.so.1 (0x48f62000)
That boils down to the following packages: glibc (and libc6?), libbzip2_1, libfreetype6, libglib2.0_0, libgraphite2_3, libharfbuzz0, libpng16, libz1.
The same thing does not work for tsMuxeR-new, because upx fails to decompress the executable...

BTW, while at it, is tsMuxeR really needed on x86_64: if I'm not wrong it is disabled by default, so why simply don't remove it, at least on that arch, and avoid all the fuss about the 32 bit libraries?
Moreover, by reading the above doom9.org thread it looks like is an abandoned program and someone is already starting to have issues with newer formats...

**Comment by Nadahar** [comment]
@GvMariani As already stated we need to fix this, and changing the POM looks like the most reasonable option. I'm just waiting on feedback from other developers on that.

If you use the compiled tarball it would solve both our problems and as you say there shouldn't be any issues with java "binaries".

The challenge, if any, is the way we bundle the transcoding engines. Normally, "the Linux way" these should just be defined as dependencies, but that wouldn't work with UMS since UMS expects to find them in specific locations and is built to work with specific versions. These aren't statically built and rely on their dependencies being installed, and this doesn't really fit into the "package distribution" philosophy.

There are several reasons for this, one of which is that Linux probably is the platform with fewest UMS users, and we want as little platform dependent routines as possible. On Windows and macOS, bundling what you need is the most viable option.

Another reason is bugs and changes in different versions that forces us to skip many versions. Especially FFmpeg makes incompatible changes and a lot also depends on the compile options. We're currently using a quite old FFmpeg because some users won't see subtitles if we use a newer version.

The reason I'm mentioning this is to make sure you're aware of the potential issues there, because even if the compiled UMS binaries should be "safe" to use our bundled executables might not be.

tsMuxeR is a big problem, because of the reasons you mention. I don't think there are other requirements for tsMuxeR-new than for the "regular" tsMuxeR though, at least my experience has been that if one work both works.

The reason tsMuxeR is included but disabled by default is a reflection of the situation. It is buggy and doesn't work in all situations while at the same time we haven't found any other software that does what it does. It does work well for many users, and since it hasn't been released as an x64 executable we have to use the 32 bit version regardless of platform architecture. It allows some videos to simply be remuxed instead of transcoded, giving both better quality and requiring much less CPU.

The author said he would open source the code, but it doesn't seem that it will ever happen. I guess we're hoping that a solution will emerge, either that the source code is released against all odds, that another software that can do this better arises or that FFmpeg fix their bugs so that the TS output it produces is actually valid. In the meanwhile, the "best" solution has been considered to just keep it there but making sure that users much enable it manually.

Thanks for the tips on decompressing the library, I'm not "Linux savvy" enough to know much about those things. I do recognize the dependencies from when I tried to figure out the dependencies across different distros, but AFAICR most of them are also dependencies of some of the other. On some distros I think libfreetype6 was the only one necessary to add, but I just gave up because the difference in packages, dependencies and package names simply varied too much among distros.

**Comment by valib** [comment]
@Nadahar I vote for changing the POM in case there is not any side effect for building UMS on Windows and macOS.

**Comment by GvMariani** [comment]
Off-topics about documentation, but perhaps still useful to you, as always with my Linux distro-packager hat on:
> The challenge, if any, is the way we bundle the transcoding engines. Normally, "the Linux way" these should just be defined as dependencies, but that wouldn't work with UMS since UMS expects to find them in specific locations and is built to work with specific versions. These aren't statically built and rely on their dependencies being installed, and this doesn't really fit into the "package distribution" philosophy.

Regarding to the "package distribution philosophy", if the "specific locations" group you name is inclusive of the system path (as it is implied by the UMS.conf file and I read somewhere in your forums), this is not really a problem, because you can always put the bundled executables in the standard binary location (/usr/bin or /opt/bin or whatever...) and UMS will happily found and use them.
As you say, the only troubles can originate from the executables library dependencies, but this also can easily worked around:
or by directly using the system-installed versions, if applicable (see below about ffmpeg, though);
or by manually adding the required dependencies to the package recipe: as you perhaps know, different versions of the same library can be installed side-to-side on Linux, because they (near) always have different sonames, so you could keep an old program working even when it becomes incompatible with newer releases of the libraries it uses.
Not a big deal from a packaging POW, provided that you documents somewhere a quick way to find what each provided executable requires to run... So the little trick from the doom9.org forum could have a place in your installation (and packaging) docs, IMO.
BTW, for tsMuxeR dependencies, in the list I gave, I would point only on glibc, zlib, bzip2 and freetype (and the first 2 are near always present even in a x86_64 installation)...

> Another reason is bugs and changes in different versions that forces us to skip many versions. Especially FFmpeg makes incompatible changes and a lot also depends on the compile options. We're currently using a quite old FFmpeg because some users won't see subtitles if we use a newer version

because

> FFmpeg fix their bugs so that the TS output it produces is actually valid

This is an important info I cannot find anywhere in your docs...
Is important because by looking at the provided UMS.conf and by searching your forums I got the impression that one could make use at will of the system-installed ffmpeg, instead of the provided one, while here you'are saying the exact opposite for very good reasons...
This notice needs to be put somewhere in the install instructions with a big fat warning on top, IMO.
It would be useful also put in the same place a list of the known-working versions of ffmpeg (do you test them, did not you?), to help in verify the destination system.
Or (more ideally, but more useful for packagers), a list of the build-time switches needed to have a working build of ffmpeg, if you happen to know them: this way the a building ffmpeg from the sources can make sure their package is working for UMS.
Also, it would be very useful having the list of the ffmpeg bugs that you opened with the upstream devs (if any) to have them fixing their things: this way a maintainer can be warned when (and if) the upstream ffmpeg will work correctly for UMS.
All those things will help a packager to avoid producing non-working packages because of wrong packaging choices about ffmpeg, as I was inclined to do until I read your words above...

> The reason tsMuxeR is included but disabled by default is a reflection of the situation. It is buggy and doesn't work in all situations while at the same time we haven't found any other software that does what it does. It does work well for many users, and since it hasn't been released as an x64 executable we have to use the 32 bit version regardless of platform architecture. It allows some videos to simply be remuxed instead of transcoded, giving both better quality and requiring much less CPU.
> The author said he would open source the code, but it doesn't seem that it will ever happen. I guess we're hoping that a solution will emerge, either that the source code is released against all odds, that another software that can do this better arises or that FFmpeg fix their bugs so that the TS output it produces is actually valid. In the meanwhile, the "best" solution has been considered to just keep it there but making sure that users much enable it manually

Also this two paragraphs of your reply deserve a place somewhere in your docs, because they explain why the two 32bit binaries are needed, even with all the problems they poses, and why they are disabled by default...
BTW: in your experience, how many use-cases percentually *need* to actually make use of tsMuxer? If that number is sufficiently low (say < 10%) one could also think of not installing it at all on x86_64 (or -better - of making it optional, by putting the executables in a sub-package, not installed by default)...

Anyway, thank you for all your attention...

**Comment by Nadahar** [comment]
@GvMariani Sorry for late answer, too many things at once here for a while.

When it comes to system path I think that's only partially true. I'm really not sure, as a lot of this code is somewhat of a mess. Sometimes executables are called without a path (which would make them work with the system PATH), but I have no overview over how often that is true.

When it comes to documenting what versions work and doesn't work of the different external programs (like FFmpeg), I don't think that is possible simply because we don't know. There are so many details at play, a lot of which isn't documented. We often doesn't have any good way to analyze it either, because the problems manifest themselves with a combination of specific media and specific devices.

The only "manageable" way to handle this from our POV is to tie a given version of UMS with a given version of the dependencies and try to make that this particular combination works. This is fundamentally incompatible with the "Linux way", but as far as I can understand all we can manage. Transcoding engines isn't my "field" though, so I don't feel that confident when we get into the details about them. I think our approach is to find versions that work by trial and error (and user feedback), and then keep that version until we need new functionality available in a later version, where the trial and error routine must be repeated.

I really have no idea idea how many that use tsMuxeR. Putting it in sub-packages sounds like a good solution, given that there is a way to inform users that these sub-packages exist.

I'm sorry that I can't offer more clarity regarding the executables, but I don't believe we have the necessary overview or resources to figure out exactly what causes which problems and why. The fact that there are so many devices and many problems are exclusive to particular devices also means that our ability to test/investigate is very limited.
