### ISSUE TITLE
External input stream instance is null on Raspbian. Looks like broken script (syntax error)

### ISSUE THREAD

**Issue by Antoniossss** [UniversalMediaServer/UniversalMediaServer#1427]
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1580746/ums_dbg.zip)
So basicly playbak does not work and thumbnails are not generated at all.

There is following error in logs:21:49:31 DEBUG /home/pi/Desktop/ums-6.7.4/linux/ffmpeg: 1: /home/pi/Desktop/ums-6.7.4/linux/ffmpeg: Syntax error: "(" unexpected

**Comment by Nadahar** [comment]
The error comes from FFmpeg. I doubt that the bundled FFmpeg will work on ARM, so you probably need to replace all the binaries in "/home/pi/Desktop/ums-6.7.4/linux/" with ARM versions. In addition I can see from your log that you haven't installed MediaInfo, which you should for UMS to work properly.

Your log isn't that helpful either, as it's not captured in ```trace``` mode, but it seems that the problem is that you need ARM executables.

**Comment by Antoniossss** [comment]
Yes you are right, iv compiled ffmpeg myslef and it wprks. also installed
missing libraries yesterday. Thanks

pt., 22.12.2017, 06:02 użytkownik Nadar <notifications@github.com> napisał:

**Comment by Sami32** [comment]
Thanks for your feedback.
