### ISSUE TITLE
[sugestion] let us select subs while we watch

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#1431]
hello dev team
im trying to watch a anime movie with 3 english subs
and the default one is blank it has no text in it
so my question is why cant we select a other sub from the file while we watch it 

im watching it on a ps3
and the anime movie i try to watch is:
`https://nyaa.si/view/989064`
and dont mind the img on there its not hentai :P 
dont know why they posted that img

this is how i do my subs now
`dut,off;jpn,eng;*,und;*,*`

**Comment by Nadahar** [comment]
@Goten87 Since the video is in Matroska format and the PS3 doesn't support this, it has to be transcoded. During transcoding the subtitles are "burnt in" to the picture, so the PS3 doesn't even know there are subtitles there. As a result, you can't select subtitles from the PS3.

If the video and the subtitles both were in formats supported by the PS3, it would be streamed and you would be able to select subtitle stream from the PS3.

You can however select which subtitles stream to "burn in" by using the TRANSCODE folder and selecting the correct combination of transcoding engine (probably FFmpeg), audio stream and subtitle stream.

**Comment by Goten87** [comment]
What do u mean nu that
That I need go make transcode folder
I never done that So thats new for me

**Comment by valib** [comment]
@Goten87 yes you should simply enable the TRANSCODE folder at the Navigation/Share settings tab and than you can see in that folder all combinations of transcoding engines, audio and subtitle streams of your video. There you can choose the combination which will work for you especially the subtitles you want.

**Comment by Goten87** [comment]
Ahh Yeah I have that off normaly it Will take the subs automatic
