### ISSUE TITLE
How to set up UMS to use newer MediaInfo version?

### ISSUE THREAD

**Issue by Antoniossss** [UniversalMediaServer/UniversalMediaServer#1442]
I have managed to compile MediaInfo myself. UMS however is still loading old 0.7.91 version isteed of my globally accessible v17.12. How can I change that ?

**Comment by Nadahar** [comment]
@Antoniossss You have to replace the libmediainfo (or whatever it is called) file found in the UMS installation folder with your version.

**Comment by Antoniossss** [comment]
The problem is, that there is nothing in ums installation dir.

**Comment by Nadahar** [comment]
@Antoniossss Then it must be somewhere on your $PATH. Anyway, just put the MediaInfo library that you've compiled in the UMS folder and I think it should use that one.

**Comment by Antoniossss** [comment]
Iv managed make UMS use newer version of MediaInfo. Please check debug files - RogueOne is file that does not want to get listed, while RogueOne1 and RogueOne2 are the same file split in half using ffmpeg. Both are listed and plays correctly.

**Comment by Nadahar** [comment]
@Antoniossss From what I can see in your log, RogueOne isn't parsed because its parsing is already cached. That means that the parsing results from the old MediaInfo is still used. If you have the UMS GUI available, you can click on "Reset cache" on the Navigation/Share tab. If you don't have a GUI available, quit UMS and delete the ```database folder``` in your profile folder ```/home/pi/.config/UMS```.

**Comment by Antoniossss** [comment]
I did try that. I guess that for reproduction purposes of debug files it used cached version. Ill try to reproduce that for you. IMHO this needs to be changed as failed readouts should not be cached.

**Comment by Nadahar** [comment]
@Antoniossss I'm not sure how to interpret that. Did it solve the problem or not? 

UMS caches the results without having any rules as to what is a "failed" parsing. Some files won't give any parsing information because they are of an unknown type or unsupported variant, there's no way to know what is what. The reason to also cache parsing without useful information is speed, you don't want these files to be re-parsed time and time again as they might be just as slow or slower to parse even though they don't produce results.

**Comment by Nadahar** [comment]
@Antoniossss If you moved on to other software and don't intend to pursue this any further, you should probably close the issue as there will be no way for us to do anything further to investigate/solve this.

**Comment by Antoniossss** [comment]
Ok then I am closing

**Comment by Nadahar** [comment]
@Antoniossss I'd still like to know if it worked after resetting the database or not. I wasn't quite clear for me.
