### ISSUE TITLE
Ubuntu 17.10, UMS 7.0.0, no GUI, no taskbar icon

### ISSUE THREAD

**Issue by dln949** [UniversalMediaServer/UniversalMediaServer#1445]
Ubuntu 17.10 (Xorg), gnome 3.26.2, UMS 7.0.0, java-8-openjdk-amd64.  

The UMS server starts, but I am not able to access the UMS GUI.  The UMS icon appears on the desktop instead of on the top bar, but no amount of clicking on it makes anything happen.  Also, on the top bar a blank spot for an icon for UMS appears, but again no amount of clicking on it does anything.  

I cannot follow your instructions to produce an error log file for you since I cannot access the UMS gui.  

I do not know how to fix this.  What should I do to fix this?

**Comment by Nadahar** [comment]
@dln949 If you find UMS' log folder, you can find the logfile ```debug.log``` and post it. To make it more useful, run ```UMS.sh trace``` from a terminal window, which will make the log file contain much more information. The UMS log folder is usually ```/var/log/UMS/%username%``` AFAICR.

**Comment by Sami32** [comment]
@dln949 That make me remember an macOS user issue very similar to you.
Could you try to do a **clean install of the [6.7.4 version](https://sourceforge.net/projects/unimediaserver/files/Official%20Releases/Linux/UMS-6.7.4.tgz/download)**, and later to [6.8.0 version](https://sourceforge.net/projects/unimediaserver/files/Official%20Releases/Linux/UMS-6.8.0.tgz/download) ?

**Comment by dln949** [comment]
Nadahar, I am attaching the log file to this posting.  
[debug.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1684179/debug.log)

**Comment by dln949** [comment]
Sami32, I renamed the UMS .config folder, then ran 6.7.4.  It did asked me to configure, I selected NOT to minimize to the tray.  Then, I was able to see the GUI.  However, it still put small - and useless - icons on both the tray and the desktop.  

I repeated the process for both 6.8.0, and for 7.0.  Same results for each one.  

I think originally from an earlier version of UMS I had selected the option to start minimized.  That worked in the past.  But now on Ubuntu 17.10 using gnome it does not.  So, when I tried using UMS, it had that old setting, and caused the problem for me.  Does that make sense to you?  

I guess the not-so-nice workaround is to have UMS start not minimized to the tray, and just live with the odd icons on the tray and the desktop.

**Comment by Nadahar** [comment]
@dln949 Your theory seems spot on to me. In the future you can simply edit this file: ```/home/main19/.config/UMS/UMS.conf``` and changed the "Minimize" setting with a text editor.

The problem is that we don't control the creation of the tray icon etc, that the Linux desktops can't seem to standardize things and that Java (Swing) don't update these things anymore. Gnome is the one that has worked until now, but we've had issues with other desktops for a while.

The GUI framework we use is called Swing, which has long been the "main" GUI framework in Java. But, Oracle pulled all their developers from this project some years ago to work on JavaFX instead, a GUI made mostly with web in mind. Since then, very little, if anything has been done with Swing, and I'd almost say that Oracle has decided to leave Java GUI applications to die.

I wouldn't hold my breath that anything will be done to fix this, but there's a very slim chance that it could be addressed when they manage to release a stable OpenJDK 9. I know they have addressed some other GUI issues there, like support for HDR monitors.

In any case, there's nothing we can do about it except to prevent "start minimized" for selected environments. To do that we'd need to know which environments it doesn't work.
