### ISSUE TITLE
NullPointerException when trying to navigate zip file on Android

### ISSUE THREAD

**Issue by crazyasapanda** [UniversalMediaServer/UniversalMediaServer#1447]
Hi.  I am using BubbleUPnP on Android 7.0 on a Huawei MediaPad M3.  However, I tried other DLNA clients and they show the same error.  The text looks like it got an HTTP 500 Internal Server Error, but it got cut off.  (See attached image.)  The debug logs show a NullPointerException.

For some reason, I've been able to reproduce this with a zipfile full of jpg images, but if they are png images, it works fine.  Also, this works fine from my PS3.  I've tried on both 6.8.0 and 7.0.0 rc2.  I'm attaching debug packs from both versions, and a small zip file of jpgs that I used to reproduce the error.

Thanks.

[ums_dbg_6_8_0.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1705558/ums_dbg_6_8_0.zip)
[ums_dbg_7_0_0_rc2.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1705559/ums_dbg_7_0_0_rc2.zip)
![upnp-error](https://user-images.githubusercontent.com/36251747/35953381-3058881a-0c39-11e8-8d68-7aa9987077b6.png)
[rends4.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1705560/rends4.zip)

**Comment by crazyasapanda** [comment]
To add some more data points, I installed a DLNA client on my LG G5 phone running Android 7.0 and saw the same problem. Also on my PS4 Pro Media Player and the Roku Media Player on my Roku  Ultra.

**Comment by Nadahar** [comment]
This is a bug in UMS. The zip file hasn't been parsed properly. The reason PNG doesn't crash is because of another bug where handling of PNG isn't there.

The compressed file handling has been neglected for many years, and there's a lot of things that haven't been kept up to date there. It's hard to prioritize it because compressing already compressed files has little or no effect. One of the major hurdles is that UMS uses external tools to parse media today, and those tools can't read inside archives. That would mean we'd have to extract them to parse them, which would make parsing very slow. The "old" PMS parsing was very rudimentary, and I think only the extension was looked at for images like JPEG and PNG. That's obviously possible withing archives, but lacks a lot of details used by UMS today.

**Comment by crazyasapanda** [comment]
This all makes sense, except for the fact that it works fine when the PS3 is the renderer.  (And so far, only the PS3.)  Is there a setting in UMS.conf or something I can set to make other renderers behave the same way?

**Comment by valib** [comment]
@crazyasapanda as @Nadahar wrote this is a bug and there is not any setting which can change it. We should take care about it.

**Comment by Nadahar** [comment]
@crazyasapanda To elaborate a little. There might be some combination of settings that results in the code that causes the crash not to be executed, but there's nothing I know of. Since UMS comes from PMS which was made for the PS3, the code is still full of special handling for the PS3. So, regardless of settings, a lot of special rules will be applied only if the name the renderer sends out is "Playstation 3". The reason for the observed behavior can be caused by either or a combination of both explanations.

@valib The crash from the log happens during the generation of the DIDL-lite. Since the web interface doesn't use DIDL-Lite, that's not so strange. The bigger problem is the reason for the crash. The reason is simply that ```media``` is ```null``` - i.e it hasn't been parsed. We could always find a way around the crash, we could even just check for ```null``` where the NPE happens, but the real problem is that we don't have any information about the image.

**Comment by crazyasapanda** [comment]
@Nadahar Thanks for the explanation.  I guess I'm not surprised there's special case code just for PS3s given the heritage of UMS.  It must be extracting the images to get media info, since I get thumbnails and everything on the PS3. Maybe I need to find an Android DLNA client that can masquerade as a PS3. :)

**Comment by Nadahar** [comment]
As I suspected, there is PS3 specific code involved here: https://github.com/UniversalMediaServer/UniversalMediaServer/blob/1e6b1151faa47e0687d6ff6bce5bacf1d857aed4/src/main/java/net/pms/dlna/DLNAResource.java#L1981-L1987

It seems like there's a setting that could produce the same result though, and that setting ```DLNAOrgPN = false``` in the renderer configuration. That could lead to problems playing other files, but it might not. Some renderers use the PNs, others don't or can handle it if they're missing. UMS' implementation of the PNs is also very rudimentary and leaves a lot to be desired...

**Comment by crazyasapanda** [comment]
@Nadahar Thanks for digging deep into this.  The DLNAOrgPN = false workaround worked for me, so I'm going to use that for the time being.
