### ISSUE TITLE
Network interface not found (headless)

### ISSUE THREAD

**Issue by DerDominik** [UniversalMediaServer/UniversalMediaServer#1451]
I installed UMS on a debian (8,1) in headless-mode which almost works pretty good (from the tutorial: http://www.universalmediaserver.com/forum/viewtopic.php?f=4&t=11623)
But after first start of the server I got following messages in the log:

`java.io.IOException: No usable network interface found for UPnP multicast
	at net.pms.network.UPNPHelper.getNewMulticastSocket(UPNPHelper.java:275)
	at net.pms.network.UPNPHelper.sendByeBye(UPNPHelper.java:315)
	at net.pms.PMS.init(PMS.java:877)
	at net.pms.PMS.createInstance(PMS.java:1149)
	at net.pms.PMS.main(PMS.java:1309)`

And the server couldn't found by my clients.
After manual restart of UMS it is working perfect.

I tried also to set
network_interface = eth0
hostname = 192.168.99.6

But nothing changed.
Any other hint, what I can try?

**Comment by Nadahar** [comment]
@DerDominik I don't know enough about bash to understand what that guide is doing, but it seems a lot just to make it run as a daemon. In any case, you shouldn't normally need to set the network interface or hostname, and you certainly shouldn't set both. UMS will pick one with a valid IPv4 address, and only if UMS picks the wrong one you need to set it. If you set it, only set one.

I don't know what you mean by "restart manually", if you mean starting UMS using UMS.sh instead of as a daemon, there's something wrong with the daemon configuration. If you just mean to manually restart the daemon, that's strange but might also indicate that something is wrong with the daemon configuration.

network_interface and hostname works as a "filter" for which interfaces UMS should pick from. UMS needs an IPv4 address to work, so if you have filtered it in such a way that UMS can't find an interface with a valid (non-loopback) IPv4 address, you will get the error above.

If you have further problems, start UMS in "trace mode" by running ```./UMS.sh trace``` and attach the resulting logfile here.

**Comment by DerDominik** [comment]
With manual restart I meant stopping and starting the service via console ->

service ums stop
service ums start

Afterwards it is running until next reboot of the server.

I created two logs with trace option:
After booting the server (failure) -> https://pastebin.com/aEM156gE
After restarting the service (works) -> https://pastebin.com/CRWzzrcZ

**Comment by Nadahar** [comment]
@DerDominik I suspect that your problem simply is that UMS is started too soon when booting. You probably need to delay the start so that the network interfaces are up before UMS is being started.

**Comment by DerDominik** [comment]
Damn, I got it :-)

I remembered, that I got that failure on my first installation of the server, but don't know the solution. But I found a virtual box image of that installation.

I use a solution via a changed interfaces-configuration.

Old ->
> ' This file describes the network interfaces available on your system
> ' and how to activate them. For more information, see interfaces(5).
> 
> source /etc/network/interfaces.d/*
> 
> ' The loopback network interface
> auto lo
> iface lo inet loopback
> 
> ' The primary network interface
> allow-hotplug eth0
> iface eth0 inet dhcp

Functional ->
> ' The loopback network interface
> auto lo
> iface lo inet loopback
> 
> ' eth0 network interface
> auto eth0
> allow-hotplug eth0
> iface eth0 inet dhcp
>     dns-nameservers 192.168.99.1
> iface eth0 inet6 manual
>     pre-down ip -6 addr flush dev $IFACE

Maybe this will help someone with similar problems

**Comment by Nadahar** [comment]
@DerDominik I didn't quite understand what file you edited, and I don't know why you use the old (deprecated?) ```service``` command, but using systemd you can simply tell daemons to wait until the network is up: https://unix.stackexchange.com/questions/126009/cause-a-script-to-execute-after-networking-has-started

In any case, it's good that you got it working 👍
