### ISSUE TITLE
Offer self contained packages

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1460]
It could be pretty cool for people to not have to install JRE to run the program. Also it would give us more control over which version of JRE our program uses in those cases.

https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html

**Comment by Nadahar** [comment]
With all the bad choices made in Java 9, this might be the most viable solution. I think we'd need to offer both types though, so that those that need it can use different JVM's or configure their environment in a particular way, but the "standard download" could use this.

I would recommend just sticking with Java 8 for now, Java 9 is to be deprecated this summer already and Java 10 is also going to be supported for 6 months. Not until we get to Java 11 we will get another "long term" Java release that will be maintained like previous Java versions. Java 8 will be supported to 2021, much longer than both Java 9 and 10, so it's very tempting to just ignore them for now and see how it all ends up.

Supporting Java 9 now is very hard because of the lack of backwards compatibility and the need for a lot of libraries to be released in special Java 9 versions. Some things simply is no longer possible to do, and other libraries aren't that actively maintained, so I suspect we will never see a Java 9 version for some of our dependencies. Replacing them could mean a lot of refactoring.

**Comment by SubJunk** [comment]
I have been working on this since it seems like quite a lot of people don't like having JRE installed on their machines these days, Java has become a bad word. We are already half way there since we create a self-contained jar file already, we just don't also include JRE. I think I'm pretty close to getting it.

**Comment by SubJunk** [comment]
Leaving notes here for myself and in case they're useful for anyone else:

I did a basic version of this using `javapackager` using the `-native` flag, but that relies on making a new `.exe` file and since we already use `NSIS` to create a `.exe` file with quite a few features like account elevation and registry management, I'm now looking into `JLink`. An advantage of this is that it can include a stripped back `JRE` that only has the functions your program uses which is pretty cool. However it's a new thing with `JRE9` and its `Maven` implementation is in alpha. Still I'll give it a try https://maven.apache.org/plugins/maven-jlink-plugin/usage.html

**Comment by Nadahar** [comment]
@SubJunk Just some thoughts: Without looking to deeply at the NSIS generated EXE, AFAICR the registry is just used to determine hos much heap memory to allocate (which is set during the installer). That isn't really what I'd call an ideal way to determine the amount of heap memory anyway, so depending on how this works with ```javapackager``` this EXE might be a good replacement. When it comes to elevation I don't see why the EXE should elevate, in fact it shouldn't. There should be no reason why a normal run of UMS would have to be elevated, and if would put users off by requiring confirmation every time UMS is run if UAC is on (which it is by default).

Regarding ```JLink``` the stripped down ```JRE``` sounds good, but as long as it's dependent on Java 9 with all the challenges it represents, I don't see much point in going down that road until we're at a point were Java 9 can actually be used without issues. The UMS GUI currently only works with the Java 9 versions that doesn't enforce the Java 9 restrictions, on versions that does enforce it UMS simply crashes with an exception.

**Comment by SubJunk** [comment]
There is a functional POC for this at https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1518

**Comment by SubJunk** [comment]
This is in master now
