### ISSUE TITLE
isAIFF() in isLossless() in DLNAMediaAudio.java

### ISSUE THREAD

**Issue by onon765trb** [UniversalMediaServer/UniversalMediaServer#1473]
isAIFF() is includes in isLossless() in DLNAMediaAudio.java.
But aiff is not a codec but a file format(container).
Line 456 in DLNAMediaAudio.java
```
	public boolean isLossless() {
		return getCodecA() != null &&
			(
				isAIFF() || isALAC() || isALS() || isFLAC() || isMLP() ||
				isMonkeysAudio() || isPCM() || isRALF() || isShorten() ||
				isSLS() || isTrueHD() || isTTA() || isWAV() || isWavPack() ||
				isWMALossless()
			);
	}
```

**Comment by Nadahar** [comment]
@onon765trb You're correct. AIFF is one of those old formats that didn't really separate between format and codec though, an AIFF file is always encoded in one particular variant of PCM.

Whether "codec" in UMS is PCM or AIFF in this context depends on the parser used (MediaInfo, FFmpeg etc). Since PCM is also there, it should be covered in either way. Do you see a negative consequence of including AIFF in ```isLossless()```?

**Comment by Sami32** [comment]
@onon765trb Only AIFC can have compressed data and still only for the less common. As for FLAC and WAV containers that could contain lossy codecs though very rarely used by most users.

MediaInfo identify such uncompressed PCM with an AIFF codecID, and to be honest i don't remember having looked at FFmpeg ID.

**Comment by onon765trb** [comment]
I don't get a negative consequence about AIFF. I didn't only know whether it's a mistake or not. 

Max or Logic Pro users may know about aiff and aifc, well.
Using  afconvert which is an audio tool provided by apple.
```
afconvert -hf
...
    'AIFC' = AIFC (.aifc, .aiff, .aif)
               data_formats: I8 BEI16 BEI24 BEI32 BEF32 BEF64 UI8 'ulaw' 
                             'alaw' 'MAC3' 'MAC6' 'ima4' 'QDMC' 'QDM2' 
                             'Qclp' 'agsm' 
    'AIFF' = AIFF (.aiff, .aif)
               data_formats: I8 BEI16 BEI24 BEI32 
...
```
[CoreAudioTypes](https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX10.8.sdk/System/Library/Frameworks/CoreAudio.framework/Versions/A/Headers/CoreAudioTypes.h)
Sample made by afconvert [ima4.aifc.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1886893/ima4.aifc.txt)

@Sami32
With the commits of your fork, I am learning JAVA and making correction of potential problems and extension.

**Comment by Sami32** [comment]
@onon765trb Hehe, i recognized some FFmpeg options 😉 
And as you saw i used your scaling and padding knowledge as well 😉 
Use the PS4_SRT branch or subtitles one, but know that i didn't touched it since beginning of october so i forget many things. The last ones are just for testing and not "valid", and one cloning issue have to be solved.
Many are come from my starving commits and PRs done in UMS more some others fixes and enhancements.

Your sample was very useful for and your report give always new enhancement ideas. Thank you 👍

**Comment by SubJunk** [comment]
Can this issue be closed or is there more discussion needed?

**Comment by SubJunk** [comment]
Stale
