### ISSUE TITLE
Versions from 6.80 and higher not working in Mac OS High Sierra

### ISSUE THREAD

**Issue by endymion00** [UniversalMediaServer/UniversalMediaServer#1494]
UMD new versions can not be run in High Sierra (10.13.4).
I've tried versions: 7.0.1, 7.0.0 and 6.8.0 and  When I tried to run them a message stating that the app is damaged is shown.

The only version it works on my computer is: 6.7.4

JAVA version is 8 Update 172 (build 1.8.0_172-b11)

**Comment by SubJunk** [comment]
I'm installing High Sierra on my mac now... I may have been causing this problem by building UMS on Sierra. Would be cool if they would stop breaking stuff

**Comment by Nadahar** [comment]
> Would be cool if they would stop breaking stuff

Word

**Comment by mitisBlack** [comment]
Same issue on El Capitan; no clue what the source might be

**Comment by Nadahar** [comment]
@mitisBlack It can't be the *same* issue because the issue is about macOS 10.13. It might have the same cause, but then this issue isn't really about macOS 10.13.

"Same issue" is too short to be useful. What versions have you tried, and what exact error do you get?

**Comment by SubJunk** [comment]
I installed the latest macOS and UMS is working for me, even old versions of UMS are. So I'm not sure why it's not working for you @endymion00

**Comment by esabol** [comment]
I don't recall having this problem with UMS, but I have experienced it with LibreOffice in the past. It's possible your GateKeeper or quarantine cache has been corrupted, @endymion00. Moving the contents of ~/Library/Cache/ to the Trash and rebooting might help.

But, before you try that, check out this URL for a possible solution:
https://apple.stackexchange.com/questions/262355/xxx-cant-be-opened-you-should-move-it-to-trash-for-flash-projector-applicat

Personally, I would recommend the second option, which is what I recall using on LibreOffice. The first option is too heavy-handed for me, but a good last resort if all else fails.
```
sudo xattr -rd com.apple.quarantine /Applications/Universal\ Media\ Server.app
```

**Comment by Nadahar** [comment]
Does gatekeeper do anything useful at all, or is it just there to enforce "Apple approved" software? I certainly don't appreciate that Apple makes problems on purpose and then implies that the problem is with the application.

**Comment by esabol** [comment]
GateKeeper protects the user from malware, and I would never turn it off, personally. It doesn't prevent the user from intentionally executing anything. It's like going to a HTTPS website which uses a self-signed or invalid certificate. Your browser will complain and stop you from accessing the website, but all you need to do is tell your web browser that you trust the website's certificate and then you can access the site. GateKeeper works exactly the same way. This error message the OP experienced is not indicative of the typical user experience. As I said, it probably indicates a corrupted cache somewhere because I have never experienced it with any version of UMS on macOS.

**Comment by esabol** [comment]
Also, it's simply not true that your certificate is revoked if you stop paying to be an Apple Developer. What happens is your certificate expires and it can no longer be used to sign new applications. Code which was previously signed before it expired continues to verify and work just fine. Apple only revokes certificates when they are used to sign malware.

**Comment by Nadahar** [comment]
@esabol I must admit that I don't know the deep down technical details of how GateKeeper works, and thus can't be bombastic about exactly "how" useful it is. What I know is that it has caused us a lot of support issues from something I don't think should be our problem. The texts Apple has chosen to use is also quite annoying, informing the user that the "file is damaged" instead of that GateKeeper blocked it for whatever reason. Some honesty would go a long way, and make it more credible as an actual security tool.

From the little I read on Wikipedia it doesn't seem like much of a protection against malware anyway. It doesn't analyze the content at all. Also, it only blocks known malware once Apple has designated it so (which might be too late). While recognizing malware and viruses via "signatures" is very common, the Apple implementation makes it quite useless. The reason for this is that GateKeeper only checks the software the *first time it is run* and only if the software that downloaded it *marks it as untrusted*. That means that if the malware isn't blacklisted at the time you first run it, GateKeeper will never "protect" you against said malware. It also means that if you download it with a program that doesn't mark the file as untrusted, or copies it via the local network or from a removable drive, it won't check it either.

To me, all of these things combined show that the goal clearly isn't to protect the user against malware. The security aspect is just used as an excuse to be able to block unsigned software, and the motivation is quite obvious given that Apple earns money by issuing signing keys.

That's why I would disable it and find a use malware protection instead if you're inclined to install stuff you don't know what is. Everybody will have to make this judgment themselves obviously, but it seems to me like Apple is just pissing on open source developers. Renting the signing key obviously isn't a big deal for commercial software, they will just increase the price of the software accordingly, so the only real "victim" here is free software. As Apple wants to force everything through their "App Store" and take a cut of the price, it doesn't take too much imagination to figure out why they don't like free software.
