### ISSUE TITLE
Question: about audio remux

### ISSUE THREAD

**Issue by onon765trb** [UniversalMediaServer/UniversalMediaServer#1561]
I am working for audio remux in ffmpeg video to PR. And I have questions.
ll. 346-348 in FFMpegVideo.java
```
boolean isSubtitlesAndTimeseek = !isDisableSubtitles(params) && params.timeseek > 0;

if (configuration.isAudioRemuxAC3() && params.aid != null && params.aid.isAC3() && !avisynth() && renderer.isTranscodeToAC3() && !isSubtitlesAndTimeseek) {
```
Why is `!isDisableSubtitles(params)` needed?
Why is `params.timeseek > 0` needed? I think it is not needed if using a ffmpeg option, `-seek_timestamp 1` and `-muxdelay 0`.

ll. 814-822 in FFMpegVideo.java.
```	
if (
	configuration.isAudioRemuxAC3() &&
	params.aid != null &&
	params.aid.isAC3() &&
	!avisynth() &&
	renderer.isTranscodeToAC3() &&
	!isXboxOneWebVideo &&
	params.aid.getAudioProperties().getNumberOfChannels() <= configuration.getAudioChannelCount()
)
```
Why is `!isXboxOneWebVideo` needed? This is not used in ll. 346-348 in FFMpegVideo.java.

Thank you in advance.

**Comment by OP-Klaus** [comment]
@onon765trb for your first question, we found that in FFmpeg, seeking does not work with the audio `-c:a copy` param. Maybe they have since changed it so it works which would be cool

Second question, it is because we transcode to WMV/WMA for Xbox, so it doesn't support the common audio formats like AC-3 and AAC

**Comment by SubJunk** [comment]
@onon765trb for your first question, we found that in FFmpeg, seeking does not work with the audio `-c:a copy` param. Maybe they have since changed it so it works which would be cool

Second question, it is because we transcode to WMV/WMA for Xbox, so it doesn't support the common audio formats like AC-3 and AAC

**Comment by onon765trb** [comment]
Thank for explanation.
About `!isDisableSubtitles(params)`
Similar reasons?
