### ISSUE TITLE
Ability to test FFmpegVideo

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1651]
We could detect and prevent bugs like https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1648 if we had tests for our FFmpeg transcoding that sends the instructions we generate to FFmpeg and detects if it gives an error.

This is part of my vision for the future of our testing suite, which when combined with a library of real files and MediaInfo tests, could give us some nice coverage to detect regressions in those external libraries. Right now there is a lot of uncertainty and manual testing needed when we update those libraries and it prevents us from updating them (our FFmpeg version is over 2 years old) so this would give me more confidence in those updates when we do them. Particularly MediaInfo since they frequently change the way they report certain things which results in us needing to do code changes, but FFmpeg will be really useful too.

**Comment by stasinos** [comment]
Hi,

I looked around a bit, and found mediainfo being used though ffmpeg in net.pms.dlna.DLNAMediaInfo::parseFFmpegInfo() 

Are there other places as well, or would the mediainfo part of this Issue be testing that ffmpeg putput is parsed correctly?

s

**Comment by stasinos** [comment]
There are also a bunch of projects that could considerably alleviate the ffmpeg/mediainfo pains. These two are the most actively maintained:

https://github.com/filebot/filebot
https://github.com/bramp/ffmpeg-cli-wrapper

Have these been considered and rejected for some reason?

**Comment by SubJunk** [comment]
@stasinos I don't understand how filebot could be used for this, can you explain?
I haven't seen `ffmpeg-cli-wrapper` before but it could be good. However it might not be relevant for what I meant here, I'll try to explain better since I didn't give enough detail in the initial post :)

We have a lot of different commands that we pass to FFmpeg for transcoding, it is very complicated in there with all the different user and renderer configurations that affect those commands. This exposes us to a lot of edge-case bugs like #1648 where that would only happen on renderers with `KeepAspectRatio=true`, and since most renderers do not set that, the bug can go unnoticed by even those of us who use UMS every day.

So it would be cool to have automated tests that start FFmpeg transcoding within various contexts and verify that it started to transcode and did not report an error.

A short way to say it is that we should have tests that verify that we are sending correct parameters to FFmpeg under a lot of contexts.

**Comment by OP-Klaus** [comment]
I like having incomplete PRs, a lot of ours are in that state :) Sometimes we are explicit with the `Not ready` label to make it clear. Also if you install the `ZenHub` browser extension you can put it into the `In Progress` pipeline to indicate it is a WIP

**Comment by SubJunk** [comment]
I like having incomplete PRs, a lot of ours are in that state :) Sometimes we are explicit with the Not ready label to make it clear. Also if you install the ZenHub browser extension you can put it into the In Progress pipeline to indicate it is a WIP

**Comment by Nadahar** [comment]
@stasinos Even though I'm no longer a part of this project, I've been a quite active developer for 2-3 years.

I don't know your working environment, and I'm not sure why you need to debug UMS in headless mode. You'd need to use a renderer to play something that made UMS call `launchTranscode()`. That said, I don't know why you'd want to do debugging from a headless state, but you might be one of those that does everything in a terminal :wink: 

Personally I use Eclipse for everything and would really recommend it. Even though I know there are many people that dislike Eclipse for all kind of reasons, I must say that I think the powerful refactoring functions and reference tracking are unparalleled. Whenever I have to use a different IDE for some reason (for other languages), I constantly find myself looking for things that simply aren't there.

For debugging I would absolutely fire UMS up from Eclipse, put a breakpoint where you want to start debugging and use a software renderer to initiate things. I use mainly use Kodi for this, which I run in another window making it easy to control "both sides" form the same desktop.

Kodi has its shortcomings when it comes to UPnP AV/DLNA, but it's the software renderer that works best as a general test tool. I've had some issues with v17, so I'm sticking to v16 for now. In Kodi 16 everything works except viewing images. Browsing images works fine though. One thing to be aware is that Kodi caches a lot, and in particular it caches all thumbnails. That means that if you want to troubleshoot thumbnails, you'll have to keep manually clearing Kodi's cache folder.

VLC 3.x has finally got their UPnP AV/DLNA support up and working, so it's a possibility to use as well. I don't have much experience using it though, since there have been so many problems with their implementation in the past that I've largely given up using it.

For audio media Foobar2000 and MediaMonkey are other possible software renderers. Personally I think MediaMonkey is confusing and inconsistent, but Foobar2000 has a very good UPnP AV/DLNA implementation. Since it's limited to audio media and browsing, I don't use it that much though.

I hope some of these tips can make debugging easier for you.

**Comment by stasinos** [comment]
@Nadahar thanks for the pointers.
For what it's worth, I when that is more convenient, and I use eclipse (with emacs bindings, of course) when stepping through the code is more convenient.

**Comment by stasinos** [comment]
Headless mode is, I believe, more appropriate for these test cases. I see no reason starting the GUI to test ffmpeg outputs.

**Comment by Nadahar** [comment]
> Headless mode is, I believe, more appropriate for these test cases. I see no reason starting the GUI to test ffmpeg outputs.

What mode you use doesn't really matter, UMS behaves exactly the same. I simply don't know how to debug from headless mode :wink: 

> I don't see anythink to click to apply labels to the PR. Maybe it's a members-only thing?

It has to do with permissions. I used to be able to set labels here, but isn't anymore since my permissions have been revoked.

**Comment by SubJunk** [comment]
@stasinos if you'd like labels applied please let me know and I can apply them. I have added the `not ready` label to your PR since I guess that's what you wanted?
I hadn't realised before that labels are member-only. I would be interested to see how ZenHub behaves for you if you get time to try it, whether you are able to change pipelines

**Comment by SubJunk** [comment]
We have this ability now. There is a lot of room for improvement but I think this issue has been done.
