### ISSUE TITLE
Cannot open folder which is a symbolic link in the open dialog to add shared folder

### ISSUE THREAD

**Issue by DeFlanko** [UniversalMediaServer/UniversalMediaServer#166]
https://code.google.com/p/universal-media-server/issues/detail?id=42

**Comment by SubJunk** [comment]
@DeFlanko is this still an issue?

**Comment by Nadahar** [comment]
This is not virual folders, symlinks are links you can create within the file system where the link itself is a "shortcut" to another file or location. It should be fairly easy to test.

**Comment by Nadahar** [comment]
Wrong button, sorry. This issue is still there, just tested. Not sure if we can solve it though (looks like a swing issue), but I'll take a look.

**Comment by Nadahar** [comment]
I've tried quite a lot of things, and haven't been able. The problem is with ```JFileChooser```. Currently it is filtered to only show folders, and the symbolic link isn't considered a folder by the underlying logic and thus isn't shown. I've tried overloading ```JFileChooser``` and managed to get the symbolic link to show, but it's not possible to select but rather enters the folder when trying to select it.

I figured I'd look at a replacement for the quite terrible ```JFileChooser``` while I was at it, ```JFileChooser``` is a somewhat slow and buggy replica of the Windows XP version of ```Common File Dialog```. It has been replaced by ```Common Item Dialog``` since Vista, and it looks completely awkward on other platforms (I've read complaints about that too).

The awt version uses the same outdated XP dialog with even fewer options, so I didn't test it. Swt uses the native dialog, so that looks much better. I implemented that and it uses the current Windows 7 dialog on my Windows 7 computer, but they have failed to implement a lot of the underlying options making it impossible to browse for folders for example (you can only select files). In addition swt represents a bit of a distribution nightmare as you can only link to one, platform dependent version which would mean we'd need one JAR for each platform. To add to this, win32 and win64 is considered different platforms, and the win64 version only works with 64 bit JVMs (so a 32 bit JVM, which is the default offered by Oracle even on 64 bit OS'es won't work with the win64 version). It's sad though, because the native dialogs would be great for all platforms, but it gets too complicated and we aren't allowed to select folders anyway.

I've also looked at some other options, they have been old and abandoned and full of bugs.

The most promising so far is the JavaFX version. It either use the native or they have done a great job at replicating it, but it's only available with Java 8 and from what I understand using JavaFX restricts the JVM to using Oracle JVM.

The day we're on Java 8 we can consider if we want to use JavaFX, in which case it seems like we have a good solution (but I haven't tested it since it's not relevant now). I'm not sure if it will allow us to select symbolic links as folders though, only a test will reveal that.

I'm letting this one stay and attaching it to a Java8 milestone.

**Comment by atamariya** [comment]
@SubJunk can you add two tags - win and win8 - to this defect for easy categorization?

**Comment by SubJunk** [comment]
I've added those labels and removed the Java 8 one because we are now using Java 8

**Comment by SubJunk** [comment]
There is an old bug for this on OpenJDK's tracker, not sure if anyone will work on it but it periodically gets updates https://bugs.openjdk.java.net/browse/JDK-7094193

**Comment by SubJunk** [comment]
I have done a fix at https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1906 and it works for me on Windows 10. I can test it on macOS and I need someone to test on Linux.

**Comment by SubJunk** [comment]
Testing passed on macOS. I'm going to try to do a similar thing we do with LookAndFeels to allow us to continue to support OpenJDK

**Comment by SubJunk** [comment]
I've changed approach after seeing that JavaFX isn't a good thing to rely upon. New approach at https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1914 is working on macOS (which probably means master already is too)

**Comment by Nadahar** [comment]
@SubJunk As far as I can see from #1914, it only impacts Windows. How can it then make a difference on macOS?

**Comment by SubJunk** [comment]
It's already working on macOS in master - it seems that Swing supports linked directories on macOS by itself

**Comment by SubJunk** [comment]
The new implementation is working now on Windows, so it should be in our next release
