### ISSUE TITLE
Update and add IDE style guides

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1671]
We have defined our style guide to be the Google one from https://google.github.io/styleguide/javaguide.html

If we are happy with this, we can possibly replace our current config files with theirs:
https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml
https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml

**Comment by SubJunk** [comment]
@valib @drakulis  do you have any opinion about our code style?
My thoughts are that it is good to use a third-party definition because then developers don't waste time discussing/arguing about it, so it is best to just choose one that we like and stick to that, let them make those decisions so we can focus on important things. Just my opinion.

**Comment by drakulis** [comment]
Sounds good. 👍

**Comment by valib** [comment]
@SubJunk we have already set formatting for Eclipse made by Nadahar. I have no objection to use third party definition but do we need than reformat all current code or use that definition only for the new code? Reformatting the code has some disadvantages. There are some parts of the code made to be better readable but not in accordance of the code style.  Automatic formatting will change it.

**Comment by SubJunk** [comment]
@valib I think there are pros and cons for doing a mass formatting but I lean towards agreeing with you that we use the definition only for new code. For one thing it creates a lot of noise in Git `blame` if we format everything, suddenly it becomes harder to see more details about the last actual change to a line.

And like you said readability is most important and sometimes we do non-standard things for that (like vertical alignment for GUI code, or heavily indented if-statements).

I don't know about the way Eclipse does formatting but other formatting tools/guides I have used let you ignore things. I regularly use `ESlint`, `TSLint`, and `StyleLint`.
I see that for Java there is a similar thing `CheckStyle`, I wonder if that is a better option since it looks like it is supported by Eclipse, NetBeans and IntelliJ http://checkstyle.sourceforge.net/beginning_development.html

@valib @drakulis What do you guys think about CheckStyle?

**Comment by Nadahar** [comment]
@SubJunk It doesn't seem like you ever looked at #606 at all: https://github.com/UniversalMediaServer/UniversalMediaServer/blob/fcb4fe4ee00cdbef67971ee2d7e601733e1e589d/CheckStyle.xml#L1-L173

**Comment by SubJunk** [comment]
I have it working in VS Code on-the-fly which is nice. I tried their config for the Google style guide (https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml) and it disagrees with us a lot (it even disallows tabs) so that probably isn't a good choice for us, unless we want to dramatically change our code style. I also checked out the Sun config and that agrees with ours more.
The `CheckStyle.xml` in our project root agrees with us more and if we wanted to go down that route we could refine it more.

So we have some options:

1) Continue to rely on a custom CheckStyle.xml as our source of code style truth, but keep the Eclipse-specific files too, and refine it to match our style more closely.
2) Continue to rely on a custom CheckStyle.xml as our source of code style truth, and remove the Eclipse-specific files - Eclipse users can use a CheckStyle extension like other editors can - and refine the config to match our style.
3) Keep relying on CheckStyle but switch to using a 3rd-party config like Google's or Sun's, and format our code accordingly.
4) Another option?

@valib @drakulis I won't make any decisions until hearing from you both. I am leaning towards option 1 or 2 now, since it seems that our code disagrees with Google's style a lot more than I thought at first. As a non-Eclipse users I like option 2 because it seems over-complicated to have 4 files for this, but maybe you want to keep them @valib ?

**Comment by drakulis** [comment]
@SubJunk I'm always positive for tools which are increasing code quality and readability. But I think we are mixing two things here. Formatter and checkstyle are two different things. Checkstyle is just a code analyzer / reporter and when used in IDE it will just notify you with some fancy marker on the gutter or underline issues in your code (but you can easily ignore it), while formatter will actually make a changes in the code. You can invoke it by some shortcut or assign it in save actions - which is a common pattern to keep code clean. Checkstyle is rather a tool used on CI / CD servers like Jenkins / Travis to force on developers clean code.

As for your question I would vote for option 1. At least I would leave `Eclipse.Formatter.xml` which as I wrote before can be easily imported in all IDEs used by us. This is the one prepared by @Nadahar, right? We may start using it. Well... I think we have to start using it asap since currently we are using none. Then when somebody disagree with particular rule, may create a ticket and provide some arguments why it should be changed.
And I'm agree that new formatter should be used on currently edited file - not on all files in the project. But I mean on FILE - not only on changed code. Otherwise we will end up with different format styles in one file.

I love Eclipse Cleanup which is like a formatter extension and can automatically fix some checkstyle issues. But it seems to not be supported anywhere else then Eclipse. If it is already synchronized with `CheckStyle.xml` I would also leave it. It will make life easier for Eclipse users.

I would remove `Eclipse.CodeTemplates.xml` - it doesn't have any valuable content.

@valib As for preventing autoformatting of parts of code: IntelliJ and Eclipse supports special comment-tags which are able to do it:
```java
// @formatter:off
  String testValue = 
            "This code will not be formatted in Eclipse and IntelliJ";
// @formatter:on
```

Unfortunately Netbeans doesn't seems to support that :( There is even issue created about it: https://netbeans.org/bugzilla/show_bug.cgi?id=211546 . It has been created on 2012 so it seems nobody cares about it :( . Even though I think we should use it and NetBeans devs will have to be aware of it and watch out.

P.S.
I don't like tab-indention either ;) but i can leave with it. There seems to be some kind of holy war between fans of tabs and spaces indention so I think that putting this under discussion will rise war also here. So you have to take hard decision and choose one by yourself.
