### ISSUE TITLE
Fully played thumbnail not updating retrospectively

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1686]
If I have a setting other than "mark" for the fully played action, then I change it to "mark", the thumbnails (probably) don't get updated. We could store a boolean in the thumbnails table to indicate whether the stored thumbnail has that overlay, and check it in that case.

I haven't confirmed this bug via manual testing, just something anticipated from the code

**Comment by pipin77** [comment]
Can't confirm this. 
My setting was:   Overlay
Changed it to : No Action
Overlay was gone, i played 3 short videos, no markings 
Changet it back to: Overlay
All fully played overlays were shown, the 3 new fully played videos, were marked too!

**Comment by Nadahar** [comment]
As far as I remember I fixed this a long time ago. Your original implementation @SubJunk, was to modify the "original" thumbnail stored in the database giving obvious issues. I think I refactored this so that the overlay is added on-the-fly in #1061 (or at least in the same "era") to fix multiple issues with your original simplified approach.

**Comment by SubJunk** [comment]
Cool, thanks for checking, I'm glad we confirmed :)
