### ISSUE TITLE
Look into AppImage

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1701]
Maybe it could be useful for our Linux users
https://appimage.org/

**Comment by Twig6943** [comment]
bump

**Comment by Samueru-sama** [comment]
The following script will produce an appimage from the released portable build: 

```
#!/bin/sh

set -e

export ARCH="$(uname -m)"
export APPIMAGE_EXTRACT_AND_RUN=1
APPIMAGETOOL="https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage"
UPINFO="gh-releases-zsync|$GITHUB_REPOSITORY_OWNER|UniversalMediaServer|latest|*$ARCH.AppImage.zsync"

wget "https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/14.5.1/UMS-14.5.1-x86_64.tgz"
tar fx ./*.tgz

cd ./ums*
cp ./web/react-client/icon-256.png ./ums.png
ln -s ./UMS.png ./.DirIcon
echo '[Desktop Entry]
Version=1.0
Name=Universal Media Server
Comment=A DLNA-compliant UPnP Media Server.
Exec=UMS.sh
Icon=ums
Terminal=false
Type=Application
Categories=Java;AudioVideo;' > ums.desktop
ln -s ./UMS.sh ./AppRun
cd ..

wget "$APPIMAGETOOL" -O ./appimagetool

chmod +x ./appimagetool

mv ./ums* ./ums.AppDir

./appimagetool --comp zstd \
	--mksquashfs-opt -Xcompression-level --mksquashfs-opt 22 \
	-n -u "$UPINFO" ./ums.AppDir UMS-"$VERSION"-"$ARCH".AppImage
```

**Comment by Twig6943** [comment]
@Samueru-sama thanks a lot. do you know why the UMS team doesnt package their app as appimage? (They just need to run this script every now and then)

**Comment by Samueru-sama** [comment]
> @Samueru-sama thanks a lot. do you know why the UMS team doesnt package their app as appimage? (They just need to run this script every now and then)

I not an UMS dev so I don't know.

You would think that making an appimage means having to read the entire documentation, then compile ums, run linux deploy, then fix some bugs and release. 

However if you already release binaries that target linux, you don't need to do all of that and just repackage them as an appimage like in the above script.

For example electron builder has this feature already when you compile binaries for linux to also make an appimage, this is why you often see appimages of electron apps, since it is just a one line change lol.

**Comment by Twig6943** [comment]
https://github.com/Twig6943/Universal-Media-Server

**Comment by Samueru-sama** [comment]
> https://github.com/Twig6943/Universal-Media-Server

That was really fast lol

**Comment by SubJunk** [comment]
Thanks for the script, I will incorporate this into our official release process

**Comment by SubJunk** [comment]
@Twig6943 I attempted to adapt your script to happen on tag, but have run out of time for the day. Are you able to look at this failure please? https://github.com/UniversalMediaServer/UniversalMediaServer/actions/runs/11547699043/job/32137989075?pr=5067

**Comment by Samueru-sama** [comment]
> @Samueru-sama @Twig6943 I attempted to adapt your script to happen on tag, but have run out of time for the day. Are you able to look at this failure please? https://github.com/UniversalMediaServer/UniversalMediaServer/actions/runs/11547699043/job/32137989075?pr=5067

Im on the phone and about to sleep, but the mv error is likely because the wildcard expands to multiple matches and that errors it out.

In the original script when the portable build is extracted I do an mv ./ums* ./ums.AppDir since the original directory contained the varying version in its name, the ums.AppDir is then passed to appimagetool.

If you know the name of the directory you can directly pass it appimagetool without my hack.

**Comment by Twig6943** [comment]
why not just grab the UMS-AppImage.sh from my repo?

**Comment by SubJunk** [comment]
It's fixed now, the next release will have this. Thanks!

**Comment by Samueru-sama** [comment]
> It's fixed now, the next release will have this. Thanks!

 I checked the last artifacts and the appimage is named `UMS--x86_64.AppImage` without version, however the last commit apparently fixes that issue but I'm not sure. 
 
Notice that 2 files get produced, one is the appimage and another is a .zsyc file which used by [appimageupdate](https://github.com/AppImageCommunity/AppImageUpdate) to get delta updates working, the reason I comment about the filename is because once appimagetool is ran the name of the files cannot be changed before being released, otherwise it breaks zsync updates for some reason.

And on a smaller note, you shouldn't need to install libfuse2 in the CI, since appimagetool and the produced appimage already work with fuse3 instead, not to mention that I export the env variable `APPIMAGE_EXTRACT_AND_RUN=1` which makes it work even if fuse is broken, anyways I think even all my appimages CI still still install libfuse2 just out of habit lol.

**Comment by SubJunk** [comment]
Thanks for letting me know the filename can't change. I will remove libfuse2 from the script. Is it also useful if I submit the releases to [appimage.github.io](https://github.com/AppImage/appimage.github.io) ?

**Comment by Samueru-sama** [comment]
> Thanks for letting me know the filename can't change. I will remove libfuse2 from the script. Is it also useful if I submit the releases to [appimage.github.io](https://github.com/AppImage/appimage.github.io) ?

The app will be added to AM which is more package manager like than the appimage.github.io website, but you are free to add it to that place as well.

iirc https://appimage.github.io only has a requirement that the app has to work on ubuntu 20.04 which is the latest still supported LTS release, **which it does as I just tested it with distrobox**. 

And just in case, the filename can be changed before running appimagetool, you can even rename the appimage after downloading it and delta updates will still work, what can't change is the name of both the .zsync and appimage between generation and uploading. In other words, if the generated appimage is called `UMS-v123.AppImage` it has to be uploaded with that name, just mentioned this because the last artifacts don't have version in their name so as to avoid that being added after generation.

**Comment by SubJunk** [comment]
Thanks again for your help
