### ISSUE TITLE
UMS Web Interface no longer sends the correct format

### ISSUE THREAD

**Issue by SsJVasto** [UniversalMediaServer/UniversalMediaServer#1760]
The renderer for Firefox seems to have changed between version 7.6.2 and 7.7.0.

I recently tried to update my UMS 6.8.0 to UMS 7.8.0.  I tried playing a file in my browser, and it sounded like 1999 (like a 52kb MP3 file).  I went back and downloaded every release between 6.8.0 and 7.8.0 and tried them one by one.  The problem started in 7.7.0, but was flawless in 7.6.2.  I included snippets of the debug file, but to sum it up:

In 7.6.2:
DEBUG 2019-02-14 17:46:14.207 [pool-1-thread-6] net.pms.remote.RemoteMediaHandler Sending MapFile [name=[Kenny] Ohne Dich.mp4, id=107, format=MPG, children=[]] **with mime type video/ogg** to Firefox
In 7.7.0:
DEBUG 2019-02-14 17:50:59.425 [pool-1-thread-8] net.pms.remote.RemoteMediaHandler Sending MapFile [name=[Kenny] Ohne Dich.mp4, id=107, format=MPG, children=[]] **with mime type video/mp4** to Firefox

I imagine it works well in Chrome because of its native support of mp4 files, but it sounds terrible in Microsoft Edge and Mozilla Firefox.  I haven't tried other browsers.

[snip-7.6.2.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2867112/snip-7.6.2.log)
[snip-7.7.0.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2867113/snip-7.7.0.log)

(The original debug files were 132724 lines and 133297 lines, so I removed the folder parsing and extracted the parts about rendering)

**Comment by valib** [comment]
@SubJunk this is caused by PR #1702 at line
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/934febe6ade50f6c9578e24fd5e2be30fcb5f175/src/main/java/net/pms/configuration/WebRender.java#L399
because the bitrate 16 kb/s for the AAC format is very low. I would recommend the part of code 

```
cmdList.add("-c:a");
cmdList.add("aac");
cmdList.add("-ab");
cmdList.add("16k");
```
delete and let the ffmpeg to create standard mp4 audio output format.

**Comment by Nadahar** [comment]
16kbps for AAC is simply a joke IMO. They have bought the hype and keep sending DAB+ (radio) in 80 kbps and 96 kbps here in Norway, and the quality is appalling so much so that I've stopped listening to radio since they shut down the FM net. I can't even imagine how terrible 16 kbps is. In my experience, 128 kbps is the absolute minimum for AAC, but higher is preferable. Using a radio with low-quality speakers, 196 kbps sounds "fine" to me, but playing it on a HiFi system might be very different. Regardless, 16 kbps is just madness.

**Comment by valib** [comment]
@Nadahar I think the 16 kbps is there since the time @SubJunk tested which format and setting will be the best for web interface. Maybe it could be 196 kbps and it is only mistyped.

**Comment by SubJunk** [comment]
Nice find @valib yes that looks like a typo. That part of the code was added 5 years ago and I think was more of an investigation.

I'll leave the aac codec in there until more testing can be done, but I have increased the bitrate to 128kbps for now.

A future enhancement should be to make it variable based on the number of channels, ideally plugging it into the same logic our renderers use, since they handle all this already
