### ISSUE TITLE
Thread exhaustion, UMS created 32k threads

### ISSUE THREAD

**Issue by ChrisLundquist** [UniversalMediaServer/UniversalMediaServer#1864]
I don't have a reproducible problem yet, but am reasonably sure I've tracked down the problem.
I was unable to ssh to one of my servers last night (I'd auth and the connection would close, logs later revealed fork was failing). After some debugging I saw that when the server became unresponsive, there were about 32k java threads running. UMS is the only java process.

My configuration is:
UMS is running in an LXD container using bridged networking. nginx is fronting UMS to serve static assets, and forward requests upstream. (java doesn't run as root this way, port 80/443 work)

Log details:
```
INFO  2019-10-29 12:35:55.684 [cling-2] Exception in thread "cling-2" java.lang.OutOfMemoryError: unable to create new native thread
INFO  2019-10-29 12:35:55.684 [cling-2]         at java.lang.Thread.start0(Native Method)
INFO  2019-10-29 12:35:55.684 [cling-2]         at java.lang.Thread.start(Thread.java:717)
INFO  2019-10-29 12:35:55.685 [cling-2]         at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
INFO  2019-10-29 12:35:55.685 [cling-2]         at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025)
INFO  2019-10-29 12:35:55.685 [cling-2]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
INFO  2019-10-29 12:35:55.685 [cling-2]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO  2019-10-29 12:35:55.685 [cling-2]         at java.lang.Thread.run(Thread.java:748)
...
DEBUG 2019-10-29 17:52:27.959 [UPNP-AliveMessageSender] Sending ALIVE...
...
DEBUG 2019-10-29 18:52:05.432 [HTTPv2 Request Worker 6] Finishing configuration for Unknown renderer
DEBUG 2019-10-29 18:52:05.432 [HTTPv2 Request Worker 6] Reading MediaInfo: true (default: false)
DEBUG 2019-10-29 18:52:05.432 [HTTPv2 Request Worker 6] Updating status button for Unknown renderer
DEBUG 2019-10-29 18:52:05.432 [HTTPv2 Request Worker 6] Using default media renderer "Unknown renderer"
INFO  2019-10-29 18:52:05.432 [HTTPv2 Request Worker 6] Media renderer was not recognized. Possible identifying HTTP headers:
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.66 Safari/537.36
DEBUG 2019-10-29 18:52:05.572 [HTTPv2 Request Worker 6] Connection error: java.io.IOException: Connection reset by peer
DEBUG 2019-10-29 18:52:05.572 [HTTPv2 Request Worker 6] Premature end, stopping...
DEBUG 2019-10-29 18:52:05.572 [HTTPv2 Request Worker 6] Connection error: java.io.IOException: Broken pipe
DEBUG 2019-10-29 18:52:05.572 [HTTPv2 Request Worker 6] Premature end, stopping...
...
DEBUG 2019-10-30 06:47:39.487 [UMS Shutdown] Sending BYEBYE...
DEBUG 2019-10-30 06:47:39.487 [Thread-668] Stopping UPNP Services...
DEBUG 2019-10-30 06:47:39.852 [UMS Shutdown] Shutting down the HTTP server
INFO  2019-10-30 06:47:39.852 [UMS Shutdown] Stopping server on host 192.168.0.30 and port 5001...
DEBUG 2019-10-30 06:47:40.561 [UMS Shutdown] Shutting down all active processes
DEBUG 2019-10-30 06:47:40.562 [UMS Shutdown] Stopping ProcessManager
DEBUG 2019-10-30 06:47:40.562 [Process Terminator] Shutting down ProcessTerminator
DEBUG 2019-10-30 06:47:40.562 [Process Terminator] ProcessTerminator has stopped
DEBUG 2019-10-30 06:47:40.562 [UMS Shutdown] Stopping services
DEBUG 2019-10-30 06:47:40.562 [UMS Shutdown] Stopping SleepManager
INFO  2019-10-30 06:47:40.562 [UMS Shutdown] Stopping Universal Media Server 9.0.0-b2
```
I'm not sure what is running Chrome 29, but it is likely an older samsung TV?

```
24091     - S   0% linux/jre-x64/bin/java -Xmx2048M -Xss2048k -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djna.nosys=true -classpath update.jar:ums.jar net.pms.PMS console
```
Was my command line.

```
 PID       SYSCPU        USRCPU        VGROW         RGROW        RDDSK         WRDSK        RUID           EUID            ST       EXC         THR        S       CPUNR         CPU       CMD         1/2

24091        1.28s         1.41s           0K         2360K           0K          340K        100000         100000          --         -        32177        S           6          0%       java
```
Here is a line from `atop`. Note the `32177 THR` count.
The reported memory usage from atop at this time was:
```
MEM | tot    31.3G | free   12.7G  | cache  13.2G 
```
Using `atop` I can see UMS spawned about 900-1000 new threads every 10 minutes.

My working theory is that the thread count severely fragmented the server's memory such that `fork` could not get an an allocation from `malloc`. I have various log lines from cron jobs and sshd failing to fork such as:
```
Oct 29 05:45:01 deon CRON[24145]: (CRON) error (can't fork)
```

The possible related events on my network could be:
- I have several machines with browser tabs open, polling UMS.
- I got a new TV, Samsung Q70, and UMS broke a day or two after networking it.

I'm happy to email you the atop logs and UMS logs, but I'd rather not post them on GitHub as there is a fair amount of metadata I'd rather not share.

**Comment by SubJunk** [comment]
Thanks for the info, please post the logs to me on our forum universalmediaserver.com/forum
We do use a lot of memory and some of that should be made more efficient. Often we found it is because there is a renderer spamming requests at us. For example some LG TVs seem to spider through DLNA servers for some reason, requesting every folder and subfolder.

**Comment by ChrisLundquist** [comment]
The memory *usage* doesn’t appear to be the problem. I think the RES size
was ~2G which is what I passed to java. The VMEM size was 70G (2MB thread
stack x 32K threads).

Even when the server was unresponsive, it had 12G free, and 13G in cache.

Another theory is that I hit max_pid. The thread count is *slightly* lower
than 32k, so the kernel Task descriptors could have been exhausted. The
system claims max_thread is ~255k. In older versions of Linux threads and
processes shared the same descriptors for scheduling purposes. I’m not sure
if that is still true or not (I was running 4.18).

I can keep poking around, but at the end of the day, something caused
thousands of threads to be spawned and exhausted some resource of the
system.
The system running UMS has 4 cores/8 threads of CPU. UMS should probably
not need more than a few hundred or thousand threads? (I think I see about
60-80 at idle).

It sounds like we might be starting a thread per request. Do you think it
would make sense to use a thread pool if we aren’t already to put an upper
bound on threads?

**Comment by ChrisLundquist** [comment]
Consulting folks who know far more than I do, they are very confident
max_pid is the problem, and java exhausted the amount of process
descriptors in the kernel.

You can increase this to ~4M, but that doesn’t really fix the problem, as
UMS probably shouldn’t be spawning ~100 threads a minute :)

So disregard the memory fragmentation hypothesis, I was wrong there.

**Comment by SubJunk** [comment]
We have generously been given access to the Java profiling tools YourKit and ThreadSafe to help us with these kinds of problems, I think it would be a good idea to use one or both of them when we look into this.
I am very interested in making UMS more efficient.

**Comment by mbentley** [comment]
Is there anything I can possibly do to help debug this situation?  I have had it happen twice in the past week now (currently happening)

![image](https://user-images.githubusercontent.com/414445/127242077-54a7a011-1bdb-494a-a0c7-acb710fe36c5.png)

**Comment by SubJunk** [comment]
I would love any help we can get. This is probably the part of Java that I know the least about. I have tried to use profiling tools but I'm not good at them yet. Last time I used one (last week to inspect a process that wasn't closing) it just showed that there were lots of byte arrays open, but not any context for them, so I don't know where they were coming from or what was responsible for closing them.
We are open source and I have been hoping we could attract some expert who knows about this stuff, and I even did announcements on the forum to look, but it hasn't happened.
I will look online for tutorials about it. Open for more suggestions and help if you have any

**Comment by SubJunk** [comment]
Looking at those logs I can see that Cling did some things around that time, maybe that somehow caused this

```
DEBUG 2021-07-27 23:26:17.791 [cling-1166] Mute: 1
DEBUG 2021-07-27 23:26:17.792 [cling-1150] Subscription cancelled: AVTransport on uuid:e7df2cfd-1b84-4da2-9266-f65dd8e559b2: DEVICE_WAS_REMOVED
DEBUG 2021-07-27 23:26:17.792 [cling-1161] Subscription cancelled: StreamSplicing on uuid:e7df2cfd-1b84-4da2-9266-f65dd8e559b2: DEVICE_WAS_REMOVED
DEBUG 2021-07-27 23:26:17.792 [cling-1165] Subscription cancelled: ConnectionManager on uuid:e7df2cfd-1b84-4da2-9266-f65dd8e559b2: DEVICE_WAS_REMOVED
```

**Comment by SubJunk** [comment]
I guess that means there have been at least 1166 Cling threads and maybe they're not closing properly

Are you able to run a Java profiler like JProfiler or YourKit in trial mode?

**Comment by SubJunk** [comment]
I found this which may be helpful https://stackoverflow.com/questions/46083045/too-many-threads-using-cling-upnp-library

**Comment by SubJunk** [comment]
@mbentley I made a build for you to test with the suggestion from that thread above. It seems that Cling allows unlimited threads by default. It's a shot in the dark but worth a try

https://www.universalmediaserver.com/uploads/UMS-SmallerThreadPool-x86_64.tgz

**Comment by mbentley** [comment]
Awesome, I really appreciate the response.  I wish I knew much about Java besides running apps but I can certainly try to run the build you created and I'll check out trying to get a profiler attached.  I work with a few of guys who have some Spring experience so maybe I can get someone to help take a look as well.  It looks like they added support in JProfiler for attaching to existing JVMs inside of Docker containers so that shouldn't be a problem.  I'll see if I can run both the limited thread pool version and the normal version of UMS for a while and see where that gets me.  It looks like the issue has only happened about 4-5 times in the last 90 days and it is super random so we'll see.

**Comment by Nadahar** [comment]
When it comes to getting an overview over the state of the threads, I think `jvisualvm` goes a long way. It comes with the JDK (and possibly the JRE, I haven't checked). It's possible to do a thread dump to file from there, but mostly I just use it to find "problematic behavior", then goes into debug view in Eclipse and then pauses one of the threads in question. This will let me start to debug one of these threads and see exactly what they're up to.

That said, I really think that the idea of "profiling experts" is getting everything backwards. Is the idea supposed to be that you can just code like a pig, and then let those "experts" analyze the results and try to figure out what's causing it later..? I doubt you'll find anybody willing to do that, as it's much easier to do it right in the first place. Trying to "fix" something that has been coded without caring about consequences is often more work than just starting from scratch while doing it right. At least that's what I end up doing most of the time.

When it comes to limiting the number of Cling threads, I have a really hard time to see how that can solve anything. The result of this is that the queue will fill instead, and depending on the queue implementation it will either grow infinitely large and cause OOM, or it will become full and start rejecting new entries. When that happens, everything will stop working. The alternative is that things will just be very delayed, which in reality will also mean that things will stop working, because there are lots of timeouts involved.

Cling spawns the threads, but it's probably your code that causes them not to finish in a timely fashion. This is the "true cause" of the problem, and no amount of "lazy workarounds" will mitigate it, it will only make the problems manifest somewhat differently.

**Comment by mbentley** [comment]
I can certainly get a `jstack` dump next time something happens as well, assuming that it might be helpful.

**Comment by SubJunk** [comment]
@mbentley cool, I think we have set up some good ways forward, I look forward to seeing that data next time it happens :) thanks

**Comment by mbentley** [comment]
Well, it is happening again.  I can't get JProfiler to attach over ssh because the user in the container is non-root and it doesn't seem to understand setting the user on the container, not on the host.  I did get a jstack dump: [jstack.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/6897123/jstack.txt)

I'm seeing the problem on my 10.8.2 UMS, not the 10.8.3-SNAPSHOT version you built.

I'm going to keep trying JProfiler and see if there is some setting that I am missing.

**Comment by SubJunk** [comment]
That's useful and continues to point to Cling. I found an ancient issue on their tracker that might be relevant https://github.com/4thline/cling/issues/3 which mentions a potential fix that would involve compiling a custom Cling version https://github.com/bubbleguuum/cling/commit/1aca3bd7295d8ddbd08fd8b8b21ad55353920df9
Interesting that it hasn't happened on that snapshot yet too

**Comment by SubJunk** [comment]
@mbentley is that testing build still running well for you?

**Comment by mbentley** [comment]
So far it has been totally fine.  Unfortunately I haven't had any further issues with the normal `10.8.2` build since those two days in a row to do any more troubleshooting.

**Comment by SubJunk** [comment]
@mbentley ok, thanks. I'll run a test of that code too to see if there are any problems that arise long term with the limited threads

**Comment by mbentley** [comment]
Figured I should update about a month later - still haven't had any issues popping up with either the `10.8.3-SNAPSHOT` or `10.10.1` versions I am running but it wouldn't be the first time it has gone a month without issue.

**Comment by SubJunk** [comment]
@mbentley thanks for the update. I think @valib noticed a problem with that beta build I made, where some UPnP functionality stopped working. We will likely end up making a custom Cling build. That would also unfreeze the version of Maven we are stuck on, so it's extra motivation

**Comment by SubJunk** [comment]
@SergiusTheBest can you please try it with 11.0.0-a2? That doesn't use Cling anymore

**Comment by SubJunk** [comment]
@SergiusTheBest that's great news! I will link this issue to v11 so that it will close when it gets its final release. Thanks
