### ISSUE TITLE
Fix support for RAR files up to v4

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2022]
There was a related library bump in 7.6.0 so I assume it was broken at some point since then, but I haven't confirmed that it works in 7.6.0

**Comment by SubJunk** [comment]
It turns out I was testing with a RAR file that was version 5, and the library we use to unrar doesn't support it (https://github.com/junrar/junrar/issues/23) so I will try to make a v4 RAR file to test

**Comment by SubJunk** [comment]
Here are some testing files - just rename the extension from zip to rar
[pexels-rar4.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/4589393/pexels-rar4.zip)
[pexels-rar5.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/4589395/pexels-rar5.zip)

**Comment by Nadahar** [comment]
I wouldn't hold my breath about the v5 support, I looked at it once and it's basically a whole new implementation that has little in common with v2. Since it's proprietary as well, I doubt many people will find the will to spend the time implementing this in Java. The only real purpose I can see for doing that is to help sell more v5 encoders.

**Comment by SubJunk** [comment]
I agree, I've changed the title to reflect that expectation

**Comment by SubJunk** [comment]
Works with junrar 4
