### ISSUE TITLE
UMS 9.5.0 seams to cause serious memory leak issues!

### ISSUE THREAD

**Issue by TigerIcecold** [UniversalMediaServer/UniversalMediaServer#2065]
As soon as I open UMS 9.5.0, the non-paged memory pool grows without an end:
<img width="640" alt="30-05-_2020_22-47-45" src="https://user-images.githubusercontent.com/52179928/83338871-a0040b80-a2c8-11ea-93c9-a39d1962ff22.png">
I use Windows 10 2004:
<img width="344" alt="30-05-_2020_22-56-16" src="https://user-images.githubusercontent.com/52179928/83338890-d772b800-a2c8-11ea-8666-46815853701e.png">
...and the newest Oracle JRE 8:
>java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

As soon as I close UMS, the non-paged pool stops growing. I have reproduced the issue multiple times. It doesn't occur with JDownloader for example - another Java Application.
To clean up the memory I have to reboot my PC.
The memory leak issue with UMS occurs again even after a reboot of Windows.

**Comment by valib** [comment]
@TigerIcecold we need the log to investigate this problem.

**Comment by TigerIcecold** [comment]
I have played a bit with this:
"C:\Program Files\Java\jdk1.8.0_251\bin\jvisualvm.exe"
Here is the NPS snapshot as ZIP:
[UMS.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/4706674/UMS.zip)
And here is the screenshot:
![UMS](https://user-images.githubusercontent.com/52179928/83339995-8fa55e00-a2d3-11ea-8fd0-e55a1050cb2f.png)
Will this help?

**Comment by valib** [comment]
@TigerIcecold please follow the instruction 
# How to contribute

In order to help diagnose and fix your issue we often need your "debug information". It's easy to save this information and attach it to a GitHub issue:

  * Start UMS.
  * Go to the `Logs` tab.
  * Press the `Create TRACE logs` button which restarts UMS in the "TRACE" mode. If that doesn't work for some reason, either select `Trace` from the `Log Level` dropdown at the bottom or set `log_level = TRACE` in the configuration file and restart UMS manually.
  * Reproduce the problem.
  * Click `Pack debug files` on the lower left.
  * Click `Zip selected files`.
  * Save the zip file to a location you will remember.
  * Attach the zip file to the GitHub issue.
    
##  Thank you for your participation

**Comment by SubJunk** [comment]
It would be really good to get the logs for this @TigerIcecold

**Comment by TigerIcecold** [comment]
Well, the UMS-own log contains lot's of information about my PC, I'm not willing to share. SRY about that. What I can tell you: The memory overflow seems to occur while scanning my media library, which is distributed on multiple HDDs, right after the application starts. While scanning the used RAM amount and the non-paged memory pool grows constantly linear. I have posted the possible responsible Java methods for it.

**Comment by SubJunk** [comment]
I understand the privacy concerns but there's not much we can do without those logs. Would you be happy to PM them to me or @valib on our forum? I assure you we don't care about anything on your PC and it would not be accessed by others.

I use UMS on Windows 10 every day and it has never happened to me

**Comment by valib** [comment]
If the user don't want to share the log we are not able to fix this issue.
