### ISSUE TITLE
Minimise what is transcoded

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#2122]
Is it possible to only transcode just the audio or just the video if only one of them is not supported?

If the renderer does not support dts but the 4k h265 HDR video is supported, can just the audio be transcoded and muxed back with the video instead of the whole thing being transcoded and losing HDR?

(as someone on the forum said, Serviio does this https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=14170&p=41736#p41731)

**Comment by SubJunk** [comment]
I'm working on this at the moment as part of v10. I will likely do it in two parts:

1) If the renderer supports the video/audio format, and the video format is the same as the transcoding one the renderer wants, then copy instead of transcode
2) If the renderer supports the video/audio format, then copy instead of transcode (this means we need to customize the MIME type during browse requests)

**Comment by SubJunk** [comment]
The first one is done in the `api-3` branch
