### ISSUE TITLE
GUI redesign

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#2125]
GUI redesign to make it more user friendly, this is something I would like to attempt. some ideas

Shared folders tab

> Transcode options per folder (no transcoding, Always transcode, Ignore subs, sorting order, custom options etc)
> Pin-code/IP access/Security in GUI
> Virtual folders in GUI
> Move some of the #--# folders to this view to how it will look on renderer

		
Web content tab separate from shared folders

> enable external network at top to enable tab (instead of general settings)
> Keep all online options ans content here
> better support for youtube (Sign in and access subscriptions etc)

Transcoding

> Subtitle language options from dropdown lists to avoid errors
> Subtitle preview in GUI

**Comment by SubJunk** [comment]
Our GUI can use all the help it can get. I would like to help this issue become more focused though since the things listed aren't just GUI. In some cases there are already issues for these things, I'll try to provide links to those.

It's great to see all of these ideas :)

> Transcode options per folder (no transcoding, Always transcode, Ignore subs, sorting order, custom options etc)

I'm not entirely sure about my thoughts on these, there is a lot there. My initial thoughts are that disabling or enabling transcoding should not be necessary, because if a user needs to do that, it means their renderer and/or user config isn't set up correctly. I would rather focus more on making it easier for users to change both of those configs (as you have already mentioned in other issues).

Ignoring subs in a folder could be good because of problems with the way some video files are set up that we can't fix. That should be its own issue, and it will depend on our folder-viewer being more powerful than it is. It may coincide with this issue https://github.com/UniversalMediaServer/UniversalMediaServer/issues/707 because if we move our GUI to the web interface it becomes much easier to work with instead of being a nightmare none of us want to touch hehe

Custom sorting per folder is a good idea too, and similar comments to above

> Pin-code/IP access/Security in GUI

This sounds good. We have some of these features hidden in our settings and they would get used a lot more if they had a GUI. My guess is that we have users that want those features but don't realize that we already have them.

> Virtual folders in GUI
> Move some of the #--# folders to this view to how it will look on renderer

Yes this is a big desire from me too. I actually started work on this in this PR https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1493#issuecomment-387326038 but it stalled and I guess we need to really decide whether our future efforts go into improving our Java GUI or into establishing the web interface as the place to go for changing settings. If we do the latter, we could possibly add it iteratively by doing one tab at a time, and then the Java GUI could just link to the appropriate page on the web interface if the tab has been moved

> enable external network at top to enable tab (instead of general settings)

That setting is for more than this tab - it also disables API lookups and other attempts at internet connections, so it is really a "general" setting

> better support for youtube (Sign in and access subscriptions etc)

That sounds good. Currently YouTube doesn't work at all, so that would need to be fixed first https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2128. This should be its own issue

> Subtitle language options from dropdown lists to avoid errors

This is another one of my unfinished PRs that got stale https://github.com/UniversalMediaServer/UniversalMediaServer/pull/74
Would be easier in a web interface. Could be its own issue

> Subtitle preview in GUI

That's a significant feature but maybe there is a way we can integrate with another tool that already does that? Can be its own issue

**Comment by Mik-S-UMS** [comment]
Glad some of these you already had a desire to add. 

Sorry this was a bit unfocused, just wanted to similar ideas grouped instead of spamming a load of issues. I guess a GUI update would just make those those easier to implement. feel free to split into separate issues if it makes more sense and close this one.


> I'm not entirely sure about my thoughts on these, there is a lot there. My initial thoughts are that disabling or enabling transcoding should not be necessary, because if a user needs to do that, it means their renderer and/or user config isn't set up correctly. I would rather focus more on making it easier for users to change both of those configs (as you have already mentioned in other issues).

I guess this would be good for testing of configs, or have custom transcoding options for a specific folder like to fix aspect ratio on problematic files for example. 
Also custom subs options for a folder that you wouldn't want to be applied to anything else, good for anime. 
you can have one for English dub with titles/signs as subs and another for Japanese audio and English subs.
Combine this with virtual folders you can have 2 folders "Anime (Dub)" and "Anime (Sub)" pointing to the same directory.

> Ignoring subs in a folder could be good because of problems with the way some video files are set up that we can't fix. That should be its own issue, and it will depend on our folder-viewer being more powerful than it is. It may coincide with this issue #707 because if we move our GUI to the web interface it becomes much easier to work with instead of being a nightmare none of us want to touch hehe

I'm learning a bit more about the GUIs and think I might have a go at redoing it using WindowBuilder in Eclipse as I don't have to learn as much code. If successful it should be easier to add those features.

**Comment by SubJunk** [comment]
@Mik-S-UMS cool, good luck, I look forward to seeing what you make :)

**Comment by SubJunk** [comment]
Closing this as it's been over 2 years now, feel free to reopen

**Comment by SubJunk** [comment]
Yes definitely. I can move pretty fast in the browser
