### ISSUE TITLE
Future problem

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#2135]
@ @SubJunk I think that there will be the problem in the future in the ProcessManager made by  @Nadahar. This is the warning

[INFO] Running net.pms.dlna.DLNAMediaInfoTest
[ERROR] WARNING: An illegal reflective access operation has occurred
[ERROR] WARNING: Illegal reflective access by net.pms.service.ProcessManager (file:/E:/Workspace/UniversalMediaServer/target/classes/) to field java.lang.ProcessImpl.handle
[ERROR] WARNING: Please consider reporting this to the maintainers of net.pms.service.ProcessManager
[ERROR] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[ERROR] WARNING: All illegal access operations will be denied in a future release

**Comment by Nadahar** [comment]
It's only a problem if you keep updating Java while Oracle keeps cutting down on the capabilities. One of the things reflection is used for seems to be possible to do without reflection in Java 8, the other one I have no idea (get the OS PID of the process).

Regardless, as always, I simply fail to see any reason to upgrade for upgrade's sake, especially when you know that crucial functionality has been removed in the "upgraded" version while it offers little or no benefit.

**Comment by SubJunk** [comment]
It's a good thing to keep in mind. It is one of the best things about us including Java in our app - we can choose whether or when to upgrade, so that takes the urgency away from this kind of situation.

@valib I think this issue should be closed, since it isn't a problem on its own, and it will be seen in the future if we try to update to a version of Java that breaks with this - our tests will fail in that case
