### ISSUE TITLE
Font scaling issues on some elements of the GUI for some users

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#2549]
A few users have reported issues with font scaling for some GUI elements like the title, tick boxes and restart server button.
(either that or everything else is not being scaled when on a 4k monitor) It appears to have started from version 10.5.0

https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=14739
![image](https://user-images.githubusercontent.com/66766335/125012814-b69b9b00-e062-11eb-80ad-b27506764397.png)

**Comment by SubJunk** [comment]
10.5.0 is when we switched from Java 15 back to Java 8 in order to fix problems with UPnP via Cling, so that is likely why this has happened.
Having said that, we may still be able to fix it.

**Comment by saveli** [comment]
So I have these problems on Ubuntu too:
![image](https://user-images.githubusercontent.com/18439300/126353109-1ccd28bc-0a26-43f7-a74e-2e8cbf3f0f9c.png)


Following [this](https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display) I tried using the system java (`openjdk 11.0.11 2021-04-20`)  by commenting out 
```
# Use our JVM if it exists
#if [ -f jre8/bin/java ]; then
#    JAVA="jre8/bin/java"
#fi
```
in `UMS.sh`, but it didn't work despite being fixed since `java-9` according to that post.

The flag `-Dsun.java2d.dpiaware=false` to allow OS to handle scaling didn't work either, but the flag `-Dsun.java2d.uiScale=2.5` was succesful:
![image](https://user-images.githubusercontent.com/18439300/126352876-8a7bd9c6-366b-4295-844a-b9117b119b6f.png)

So the easy solution is to add `-Dsun.java2d.uiScale=2.5` as flag at the bottom of `UMS.sh` (and maybe add some if-else to set it to 1.0 on low dpi and 2.5 on high dpi displays).

**Comment by SubJunk** [comment]
@saveli thank you! Maybe you can help us with that if..else part too?

**Comment by saveli** [comment]
Well, from [this](https://askubuntu.com/questions/197828/how-to-find-and-change-the-screen-dpi) it is troublesome to provide a single correct solution as all three ways reported different values for my two monitor setup...

But I only found below calculation to result in the "correct" value of 2.5 for my setup with a display scale of 1.25, Xft.dpi of 192 and the GNOME hardcoded base of 96 dpi: 1.25 * 192 / 96 = 2.5

So I just added this (anywhere in body)
```
# primary monitor display setting scale factor
SCALE=`sed -n '0,/<\/scale>/{s/<scale>\(.*\)<\/scale>/\1/p}' ~/.config/monitors.xml`
# get dpi of X
DPI=`xrdb -query | sed -nE 's/Xft.dpi:[[:space:]]*([[:digit:]]+)/\1/p'`
# gnome hardcoded dpi as base
HARDCODEDDPI=96
# final factor (bc for floating point arithmetic)
FACTOR=`echo "scale = 1; $SCALE*$DPI/$HARDCODEDDPI" | bc`
```
and this flag in the last line
```
-Dsun.java2d.uiScale=$FACTOR
```

to `UMS.sh`

**Comment by SubJunk** [comment]
@saveli thanks for sharing that. I wonder if there is a comprehensive script out there somewhere

**Comment by SubJunk** [comment]
Another similar report at https://www.universalmediaserver.com/forum/viewtopic.php?f=13&t=14855&p=44598#p44598
