### ISSUE TITLE
Unstable testIsFullyPlayed

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2742]
This test is making master unstable and needs to be fixed. Unfortunately I can't reproduce the failure locally, so am debugging it by pushing commits to here. Any ideas would be helpful. https://github.com/UniversalMediaServer/UniversalMediaServer/runs/4611809555?check_suite_focus=true

```
Error:  Failures: 
Error:    TableFilesStatusTest.testIsFullyPlayed:103 
Expecting actual not to be null
```

**Comment by SubJunk** [comment]
@SurfaceS your fix has made it less common but it still happens sometimes, so I have reopened the issue

**Comment by ik666** [comment]
I had a look at this issue: Seems like a race conditions leads to this sporadically appearing error due to synchronizing against 2 different objects (once against the class file and once against a member attribute). Since the member attribute is already a Lock implementation, it just needs to be implemented as intended.

**Comment by SubJunk** [comment]
This was fixed
