### ISSUE TITLE
Cant navigate OS when adding folder on OSX

### ISSUE THREAD

**Issue by schroef** [UniversalMediaServer/UniversalMediaServer#2993]
ums 10.21.0.1
OSX
10.11.6

Description
When adding a source folder on OSX, i cant traverse folders. I can only add folders give by the popup menu
see image. The folders cant be traversed, double clicking them doesnt open them neither. Therefor it adds all sub-folders etc etc resulting in to much data

Steps
01 Open UMS > Shared Content
02 Add New source folder
03 Cant navigate system to custom folder

![Screen Shot 2022-05-23 at 15 14 00](https://user-images.githubusercontent.com/6923008/169890253-552f41f2-5858-4192-b78e-6c232de45446.png)
![Screen Shot 2022-05-23 at 15 13 57](https://user-images.githubusercontent.com/6923008/169890257-746db96f-3c3e-4552-b26b-2ded849fcbd8.png)

**Comment by schroef** [comment]
Therefor UMS keeps crashing, ive added the main folder Document which has lots of folders which dont matter. Currently UMS crashes now on start as it scans all folders

**Comment by SubJunk** [comment]
Both double-clicking and using the `Choose` button works for me. Can you try with UMS 11.0.0-a2?

**Comment by schroef** [comment]
> Both double-clicking and using the `Choose` button works for me. Can you try with UMS 11.0.0-a2?

That DMG is empty for me, i cant install it on 10.11.6

**Comment by SubJunk** [comment]
@schroef you are using an older version of macOS so please try the `pre-10.15` release of v11 here https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/11.0.0/UMS-11.0.0-pre10.15.dmg

**Comment by schroef** [comment]
Not really sure that matters. A DMG can always be mounted. I can use the smh from the website, but none of the version here in the release section

**Comment by SubJunk** [comment]
@schroef the reason I said it is that, among other differences, each DMG is compiled with a different filesystem which can really affect compatibility. The `pre-10.15` releases are made with the `HFS+` filesystem target.

We are very actively working on a new release that allows you to manage folders via web browser so that should fix any of these kinds of problems - we won't have to rely on these hacky interfaces anymore since browsers can just use system defaults.

In the meantime you can manage folders on macOS by editing the `folders` entry in your config file which is usually in `/Users/username/Library/Application Support/UMS/UMS.conf`

**Comment by schroef** [comment]
Yeah already figured out that i can adjust the config manually. I just found it weird the osx app interface is so limitied compared to windows

**Comment by SubJunk** [comment]
This should be fixed now by using the browser settings
