### ISSUE TITLE
Translation keys

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3099]
Our source language file https://github.com/UniversalMediaServer/UniversalMediaServer/blob/b69a5f0d07984ff20ad7890120e608df3a09cef0/src/main/resources/i18n/messages.properties is a mess, as one would expect from 14+ years of translations without refactoring.
I propose it would be nicer to have simple keys that are an abbreviation of the value. I do that on another large project and it is more readable IMO.

What that means in reality is that this:
`FoldTab.UseInfoFromAPI=Use info from our API`
Would become:
`UseInfoFromAPI=Use info from our API`

Exceptions can be made when there is an explicit grouping or important context, like the `Language` section https://github.com/UniversalMediaServer/UniversalMediaServer/blob/b69a5f0d07984ff20ad7890120e608df3a09cef0/src/main/resources/i18n/messages.properties#L244-L283 but in general I think we make things more confusing instead of less, by adding unnecessary context.

This also gives us a good chance to get rid of the unreadable keys. So this:
`NetworkTab.14=Could not install the Windows service. It is probably already installed.`
would become:
`CouldNotInstallWindowsService=Could not install the Windows service. It is probably already installed.`

@UniversalMediaServer/developers any opinions on it?

Obviously there is the problem of all of the existing translations. I had a look in Crowdin to see what their support is for renaming keys, and I can't see any, so there will possibly be a manual task to update them. I can do that.

**Comment by SurfaceS** [comment]
I agree that the source language file is a mess.
Especially because of the unreadable numbered keys.

Grouping have pros and cons.
This makes it easier for us to find if there is a word/phrase that would say the same thing.
On the other hand, sometimes we recreate a new entry because it is not based on the same group.

The thing to be careful is : 
For the same word/phrase in English, you can have several words/phrases in another language, depending on the context.

I don't know about Crowdin's renaming keys.

**Comment by Nadahar** [comment]
@SubJunk There are more problems, but I don't know if you use all the features. If you use Crowdin "branches" (the crowdin plugin supports making Crowdin branches for git branches), Crowdin won't be able to correctly "merge" them when you merge the git branches. Also, you will lose comments, explanations, context information etc. provided for the strings you delete.

If you still want to do it despite all the potential downsides, I'd recommend exporting all the languages to files though. You can then use a good text editor and do some cross-file find and replace (use regex so that you can make sure matches only match at the start of lines etc) and change all the language files at once. Once that is done, you can upload all the files to Crowdin again. It's still quite the job, but it's miles faster than doing it manually for all the different languages.

**Comment by SubJunk** [comment]
Oh yeah that's a good idea to export/import the languages as files, thanks. I don't use the branches feature so it should be safe. The comments have usually been suggestions and have been actioned so I'm not sure there is any value lost there.

**Comment by SubJunk** [comment]
I'm using this regex in VS Code. Seems to work so far

<img width="512" alt="image" src="https://user-images.githubusercontent.com/584228/176792274-12221c73-d5f9-4c10-b043-8c27ba5d6574.png">

**Comment by Nadahar** [comment]
@SubJunk As long as you get a preview first, it's probably "safe". Was was thinking of doing the code and the language files separately, in which case you could require that it was at the start of the line. But, I guess those labels are very unlikely to match anywhere they shouldn't...

**Comment by SubJunk** [comment]
Tweaked to be a bit safer
<img width="513" alt="image" src="https://user-images.githubusercontent.com/584228/176794006-e48096d2-60d6-4ed0-bfaa-3a26119d7193.png">

**Comment by SubJunk** [comment]
Done in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/3123
