### ISSUE TITLE
"Clear All" in New Media Folder multiple times, does nothing

### ISSUE THREAD

**Issue by perler** [UniversalMediaServer/UniversalMediaServer#325]
I would like to start using the new media folder, but it has all my items from the first index in it.

the "clear all" link (when you browse via DLNA) appears at least 4 times and when starting it, nothing happens.

**Comment by Sami32** [comment]
@perler @SubJunk It's take some secondes though before delete the database datas but it actually does from UMS interface.
But i think you was talking about this option from "Server Settings" in "Navigation/Sharing settings" tab, yes i found that was buggy. https://github.com/UniversalMediaServer/UniversalMediaServer/issues/949

Could it be considerate as duplicate ?

**Comment by polygirl** [comment]
Hi @perler it's been some time since you opened this issue and since then UMS has advanced.  The new media folder functionality is now part of the Media Library and it has many other features.  We're going to close this issue, but if you have any other problems with the latest version of UMS please let us know by opening a new issue.
