### ISSUE TITLE
Problem with Sony Xperia Movies

### ISSUE THREAD

**Issue by s-kostyuk** [UniversalMediaServer/UniversalMediaServer#347]
Unable to play any video file from UMS directly though Movies application - unsupported file format error occurs. But if find exact the same file though BubbleUPnP and then transmit it to Movies application - video plays just fine.

Illustration: https://www.youtube.com/watch?v=k1JC5YMYwJ4
UMS debug.log: http://pastebin.com/SEh3h7EJ
config: http://pastebin.com/sTESAva5

Thanks

**Comment by Sami32** [comment]
@s-kostyuk Did you solved this issue ?

Because i saw errors telling that `MediaInfo` and `Libzen` was not loaded under Linux, an other error telling `ffmpeg has a return code of 2! Maybe an error occurred...` and your Media renderer (Sony SGP311) was not recognized. So it's not a surprise that you could not see anything ;-)

So it's look like you need to do a clean install following these steps:
Linux install instructions: https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Linux-install-instructions 

If not, post your log following these instructions, please:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by s-kostyuk** [comment]
Actually, I switched to Plex quite long time ago so this issue is not actual.

As I remember, two years ago UMS was installed on Cubieboard A10 (ARM device) with debian as an OS. So it's not surprising that ffmpeg returned error and failed to transcode the video.

Now I can try to test this issue again with the same devices, archlinux arm and latest UMS. If you want.

**Comment by Sami32** [comment]
@s-kostyuk Thank you for you feedback :-)

It's unusual plateform testing, but if worst a try.
If you accept to test it again it will be nice to know what's happen since then on FFmpeg side.
