### ISSUE TITLE
Renderer subtitle capabilities

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#353]
@UniversalMediaServer/developers I propose that instead of the current system of using SupportedSubtitlesFormats and InternalSubtitlesSupported to determine which subtitles are compatible with the renderer, we add two new arguments to the "Supported" lines; "is" and "es", for "internal subtitles" and "external subtitles".
Renderers often only support external or internal subtitles for certain file formats, so our current system can't work perfectly for those renderers.
So this way we would have lines like:

Supported = f:mpegps   v:mpeg1|mpeg2|mp4|h264   a:ac3|lpcm   is:srt|ass   es:srt|sub   m:video/mpeg

What do you guys think?

**Comment by Sami32** [comment]
@SubJunk That a good idea :-)

**Comment by SubJunk** [comment]
Wow 2014!

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/961

**Comment by SubJunk** [comment]
> Wow 2014

Wow 2018!

And we are finally almost merging it :)

**Comment by fgimenezm** [comment]
Looks like that merge broke the SupportedExternalSubtitlesFormats functionality.
I'm using an LG WebOS TV and up to 9.1.0 I could stream with external SRT subtitles without transcoding but in 9.2.0 I get something like this in the logs:
```
Matched external subtitles track for "xxxx.mkv": External, type: SUBRIP, lang: es, externalFile: C:\...\xxxx.srt, external file character set: ISO-8859-1
Reading SupportedExternalSubtitlesFormats: "SUBRIP,WEBVTT" (default: "")
This video has external subtitles that can be streamed
...
...
External subtitles format undefined in Supported lines, video will be transcoded
```

The renderer config for LG WebOS TV doesn't have the new "si:" and "se:" parameters but it does have the old SupportedExternalSubtitlesFormats one which the log shows is being read. I would expect the code to use the value from SupportedExternalSubtitlesFormats when there is no "se:" parameter but that doesn't seem to be the case. The end result is that the video gets transcoded due to this when it should be streamed directly.
I reverted back to 9.1.0 and the exact same file streams without transcoding and with the external SUB.

**Comment by SubJunk** [comment]
@fgimenezm thanks, I have created a new issue for this so we can track it better https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1892
