### ISSUE TITLE
Error when I try to save General setting (FireFox web browser)

### ISSUE THREAD

**Issue by Zcooby** [UniversalMediaServer/UniversalMediaServer#3691]
Every time i start the PC the program UMS starts FireFox webbrowser with a open tab with Deteced media renders.
That i find anoying. 
I change some settings in General setting (FireFox web browser) and try to save it but it gives me error, 
that the settings can not be saved and run a log trace.
[ums_dbg_2022-12-15-08-36.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10234802/ums_dbg_2022-12-15-08-36.zip)

**Comment by SubJunk** [comment]
Thanks for reporting it. Does it work in this version? https://www.universalmediaserver.com/uploads/UMS-boblatimer.exe

**Comment by SubJunk** [comment]
@SurfaceS I'm guessing we haven't fixed this problem yet, I haven't looked into it

**Comment by SurfaceS** [comment]
**First you do not change the good setting :**
You change the `Start minimized to system tray` setting.
It related to java GUI.

If you want to disable the browser on start, you need disable it in : `General Settings` -> `Graphical user interface` -> `Launch GUI in browser on startup` setting.

**Second thing related to the error :**
SSE was not send the conf back if no auth. fixed in #3709

**Comment by SubJunk** [comment]
We should also rename that minimise setting to be less confusing
