### ISSUE TITLE
Cannot add network drive for Shared Content

### ISSUE THREAD

**Issue by BitEater21** [UniversalMediaServer/UniversalMediaServer#3750]
Whenever I try to add a mapped network drive folder as Shared Content, UMS immediately removes the new entry without showing an error message.

In the log I file I found entries like this:
_WARN  2023-01-01 12:37:37.056 [main] net.pms.configuration.sharedcontent.SharedContentConfiguration Insufficient permission to read folder "V:\Video": Permissions do not allow execute access_

When asking for hints in the forum, another user replied, that he has the same issue with UMS v12 which he did not have before.

I am using UMS v13.0.0 on Windows 10 Home 22H2 Build 19045.2364. 
The network drive is on a Synology NAS, access works fine in Windows Explorer etc.

[_ums_dbg_2023-01-01-12-38.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10330483/_ums_dbg_2023-01-01-12-38.zip)

**Comment by OldMan100** [comment]
This problem is present in any version after 11.6.0. All versions after 11.6.0 are unable to access any files through a network path, O: or \\DS-418-1\General 02. Any drive connected through USB are good. I do not know if stated in the logs attached, but at one point, the program stated, no permission to access the files through the network. But 11.6.0 has no problem accessing my network.

Attached are two log, Trace and All.
[ums_dbg_2023-01-02-10-17.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10333146/ums_dbg_2023-01-02-10-17.zip)
[ums_dbg_2023-01-02-10-25.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10333147/ums_dbg_2023-01-02-10-25.zip)

All of us are having the same problem, the program will not access anything on a network path.

**Comment by SubJunk** [comment]
Thanks for reporting this bug, I'm looking into it now

**Comment by SubJunk** [comment]
I'm not sure if it will do anything but can you try https://www.universalmediaserver.com/uploads/UMS-3750.exe please

**Comment by OldMan100** [comment]
SubJunk,

UMS-3750 had two problem in the beginning. First, it freeze for about 2 mins. during installing one of the jpg.  Second, after verifying the correct language, the installer does not close.  The startup icon is on the screen until I manually close it. And opening the program bring me back to the language question and the program is frozen again.  So, I could not verify if this version would work. Back to version 11.6

**Comment by SubJunk** [comment]
@OldMan100 thanks, can you please try https://www.universalmediaserver.com/uploads/UMS-3750-2.exe

**Comment by BitEater21** [comment]
Thank you @OldMan100

I currently don't have my computer available I had installed it originally. On another computer with this version I can add network folders. But the login dialog appears 3 times before I see any settings and appears again every time I select another settings page.

**Comment by SubJunk** [comment]
@BitEater21 thanks for testing the fix. I'll make a new issue for the login dialog problem. Can you please provide logs for it?

**Comment by OldMan100** [comment]
SubJunk,
I believe you've fix the problem. The new version has been installed, network share locations inputted, the program started and re-started a few times. So far, all saved locations are still saved. I will see how things go and inform you of any problems.

Thank you

**Comment by SubJunk** [comment]
@OldMan100 thanks for testing and your feedback!

**Comment by OldMan100** [comment]
SubJunk,
As far as what BitEater21 stated, the log in page appears for a split second when flipping between the other pages in the menu, Shared Contents, Tools, Sever Setting, etc.

**Comment by BitEater21** [comment]
@SubJunk : Commented in #3751

**Comment by sporkkchops** [comment]
I'm encountering this error as well using a synology nas.
