### ISSUE TITLE
Incorrect video time Samsung-CD

### ISSUE THREAD

**Issue by Fredo1650** [UniversalMediaServer/UniversalMediaServer#4114]
Hello, 
The new Samsung-CD.conf file that I downloaded to resolve the eac3 #4039 audio problem still produces these new bugs that I did not have with the original version Samsung-CD (Original).zip, then I can no longer move forward or backward in the video, the maximum time displayed is 6s instead of 00:48:07, with the original version everything works correctly again (Time, forward, backward in the video ) but no more eac3 codec which can be found only in the Samsung-CD-3 (Modified codec eac3 #4039).zip file

Log Samsung-CD (Original): ums_dbg_2023-10-06-19-09
Log Samsung-CD-3 (Modified codec eac3 #4039): ums_dbg_2023-10-06-19-14

[ums_dbg_2023-10-06-19-09.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/12834162/ums_dbg_2023-10-06-19-09.zip)
[ums_dbg_2023-10-06-19-14.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/12834163/ums_dbg_2023-10-06-19-14.zip)
[Samsung-CD (Original).zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/12834164/Samsung-CD.Original.zip)
[Samsung-CD-3 (Modified codec eac3 #4039).zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/12834165/Samsung-CD-3.Modified.codec.eac3.4039.zip)
![Samsung-CD (Original)](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/33e62923-277a-4981-a3cd-1cdde7504f03)
![Samsung-CD-3 (Modified codec eac3 #4039)](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/0102cdbd-ca36-4fc0-8954-7e5fbc1acd1c)
![Samsung-CD (Original)](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/469acd3b-0273-47fa-8899-217f47e673ef)
![Samsung-CD-3 (Modified codec eac3 #4039)](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/101018178/f1d7d530-3b04-43d8-bd22-c03abbef83e9)

**Comment by Mik-S-UMS** [comment]
When you are unable to seek the video and the time displays wrong is due to the video being transcoded, and Samsung TV's  does not handle this too well (at least up to the F series as mine does this) but will still play. It a limitation on those TVs.

This modified conf is more up to date with what that TV supports but may be missing one format that you TV can play if it works using the old conf. I can see 3 of the videos marked to be transcoded use the "aac-lc" audio codec and the other uses "eac3". I see in the previous issue that the "eac3" format was not supported to this bit is correct.

**Comment by SubJunk** [comment]
Yeah this is the correct thing for UMS to do - your TV does not support EAC3 audio, so we transcode the video. The side effect of that is the wrong time code and no seeking
I think it is a bug with Samsung TVs because we do send the correct time to the TV
