### ISSUE TITLE
3 TV found on my network at start?

### ISSUE THREAD

**Issue by mykeehu** [UniversalMediaServer/UniversalMediaServer#4138]
Something may have changed in the latest versions, because you find three TVs instead of one (see image), while there is only one Samsung D5500 (UE40D5500). This should also be improved.

![image](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/6390413/b37dfcfe-8c13-4c36-a882-f1f696c8b72e)
![image](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/6390413/e0140670-c559-40cb-9655-a8eebba63531)

12:08:51 INFO  Renderer Samsung E+ Series found on address: 192.168.1.50
12:09:06 INFO  Renderer Samsung E+ Series has an estimated network speed of 36.29368888888889 Mb/s

**Comment by SubJunk** [comment]
Thanks for reporting this. I get it too with my LG TV. It's inconsistent though, sometimes it shows 1, sometimes 2, sometimes 3. I think it depends on the order that we receive the broadcasts from the TV.
Any ideas @SurfaceS ? It is still like that in the v14 branch

**Comment by SurfaceS** [comment]
@SubJunk On v14 it should not happen as it is now sync.

**Comment by SubJunk** [comment]
Hmm I have two on v14 now (I have to use the java interface while I can't get into web settings)
![image](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/584228/2992c117-a99e-4140-8977-83c099aba486)

**Comment by SubJunk** [comment]
Here is the web settings view too. Can email you the logs if you want, I saved them
![image](https://github.com/UniversalMediaServer/UniversalMediaServer/assets/584228/9b4d59e1-30bf-4d8d-9a31-2faa4597089e)

**Comment by SubJunk** [comment]
I think the TV is advertising it as a separate service. One has service `webos-second-screen-3000-3001` and the other has `AVTransport, ConnectionManager, RenderingControl`

**Comment by SurfaceS** [comment]
@SubJunk : Your case is not the same as @mykeehu.

@mykeehu has the same 'upnp device' 3 time with 2 of them with IP 0% (null).
It was due that the server received multiple request at the same time, then UMS has not yet registered the renderer for the 2nd and the 3rd request -> create phantoms.
This is fixed in V14.

For your issue, it may not be an issue.
As I see on logs, your TV advise for multiple devices (`urn:schemas-upnp-org:device-1-0`) on different IP ports.
You have :
- `urn:lge:device:tv:1`
- `urn:schemas-upnp-org:device:Basic:1`
- `urn:dial-multiscreen-org:service:dial:1`
- `urn:schemas-upnp-org:device:MediaRenderer:1`

Each device have their own services.

It is possible that a device (like a computer or a smartphone for ex) open multiple software on the same 'physical device', and advise multiple 'upnp device' that are different endpoint.
They should be treated unique.

Here, UMS recognize `urn:schemas-upnp-org:device:Basic:1` and `urn:schemas-upnp-org:device:MediaRenderer:1` as renderer.

**Comment by SubJunk** [comment]
That makes sense. I will close this as fixed in v14

@mykeehu we will do a public beta for v14 very soon
