### ISSUE TITLE
Subtitles mixed from previous file

### ISSUE THREAD

**Issue by Jouse82** [UniversalMediaServer/UniversalMediaServer#423]
Subtitles work fine for the 1st file after starting UMS. For 2nd and consecutive files, the first 30 minutes are fine, but after that the subtitles of the current episode get mixed with the ones of the 1st file I've watched since starting UMS. The feed from UMS shows the running episodes subtitles + the subtitles of the first file both. Kinda annoying..

**Comment by Sami32** [comment]
@Jouse82 Did the latest UMS version solved this issue ?

@valib I think remember that you solved this issue already, right ?

**Comment by valib** [comment]
@Sami32 not me but manufacturer of the TV. See http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=2959&start=20. I always said it is not the UMS problem because it sends the subs only once on the TV request before video streaming starts and there was not any other TV requests to send something else in the logs.

**Comment by Sami32** [comment]
@valib Thanks for you feedback and your tracking help :+1: 
I didn't remember where i read about it
