### ISSUE TITLE
No Blocked media renderers?

### ISSUE THREAD

**Issue by xeophyte** [UniversalMediaServer/UniversalMediaServer#4644]
I updated UMS to 13.10 and there is no Blocked media renderers and Network devices on the main page. Why is that?

**Comment by SubJunk** [comment]
@xeophyte that was an incomplete feature that snuck in from v14, and we removed it because of problems. If you rely on that feature it would be better to run the v14 beta release from https://github.com/UniversalMediaServer/UniversalMediaServer/releases/tag/14.0.0-b1
We will hopefully release v14 final within the next week too

**Comment by SubJunk** [comment]
Yes, and it is in the beta too
