### ISSUE TITLE
Missing renderers file Samsung TV 2023

### ISSUE THREAD

**Issue by Fredo1650** [UniversalMediaServer/UniversalMediaServer#4655]
Hello, I am currently using UMS 13.10.1 in this version the Samsung-TV-2023.conf file that mik_s had created on the forum is missing. Could it be added in future versions ?
Maybe there have been new updates with this renderers in the meantime ?
Best regards.

https://www.universalmediaserver.com/forum/viewtopic.php?t=15994

[Samsung-TV-2023.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/15314430/Samsung-TV-2023.zip)

**Comment by Mik-S-UMS** [comment]
It may not be suitable to be included in its current form as it will need to be fully tested. It is basically an older conf I modified to give better support but no guarantees that everything is correct as I can't test it myself.

I have suggested that the Samsung confs could be improved so that newer models will use a more recent conf for 4K instead of falling back to the old notCD one.

**Comment by SubJunk** [comment]
Good idea, I'm doing this now, as well as adding better generic support

**Comment by SubJunk** [comment]
Actually the detection was already done in https://github.com/UniversalMediaServer/UniversalMediaServer/issues/4410 

The way the 2019+ config is written, it should be fairly future-proof until Samsung changes their naming convention

I'm adding more tests for newer TVs to make sure they are covered, but by looking at that forum thread, it seems like the problem was related to the maximum bitrate and not the renderer config. Or is there a change in the config that improves things?

**Comment by SubJunk** [comment]
The generic part is done too at https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4838
So now unrecognized Samsung TVs will use the UHD 2019+ config
