### ISSUE TITLE
Shut down/sleep computer after streaming the current or next file

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#474]
This would be a cool option to have for late at night. Suggested at http://www.universalmediaserver.com/forum/viewtopic.php?f=13&t=2932

**Comment by valib** [comment]
@SubJunk It could be nice feature but there are some circumstances to be solved. Could it be set from a renderer or the UMS? If from the renderer how we do it? It could be done for one user but how to solve it when the UMS would serve for more than one? Use timer e.g. 5 or 10 minutes to check users (renderers) activity? That is my first look on that issue so we can discuss more.

**Comment by SubJunk** [comment]
@valib yeah I think that recommendation is good. It could open a can of worms to allow setting it on the renderer, though I suppose if it's disabled by default then the user could decide.

**Comment by SharkHunter** [comment]
This is a big can of worms that will work for some but probably "misbehave" for a lot of people. One of the biggest problems would  be "render inactivity". We know that we can't trust the start/stop callbacks. So if you say 30 minutes of render inactivity what do you mean? 30 min after the stop callback? Then you'll shutdown UMS in the middle of the movie (which might be ok since the render might have buffered the whole thing). And what if you play a dir with a lot of audio in it. Most renders continues to play the next track. So when does render inactivity occurs here? 
The only thing I could think would work is to detect when the renders are gone (ie. the render shuts down) but that was maybe not what you wanted?
I think most people would have it off since it would misfire a lot. I would rather make this a plugin than part pf UMS core (since it is possible to put it outside).

**Comment by ExSport** [comment]
I expect user wants it to shutdown computer when he asleep. So he started 1,5hour movie and he is not sure he will stay awake until the end so he want shut down pc automatically.
So something like enabling option to shutdown PC after x files finished streaming directly from browsed folder? Opening folder "shutdown", choosing option to shutdown PC after 1 file finished and starting movie playback. If buffer stopped to generate, streaming/transcoding ended, wait 15mins and then shutdown PC. If more renderers are present, defining master renderer which can initiate this restart should be fine.
I don't think user wants some advanced AI, he wants only "stupid" shutdown of PC after some time to quiet fans and spare some electricity when he already asleep and movie finished :-) It is only my guess.

**Comment by SharkHunter** [comment]
@ExSport - yes for sure. Still we could make it a plugin and rely on the start/stop callback. I think. But that might not work. If we take the PS3 for example the stop callback normally fires after 20-25 min (for a full 1,5-2 hour movie) since the PS3 downloads at max speed. This confuses the resume option and it would confuse the shutdown as well. And what happens when the server dies? Does the PS3 continue playing from it's buffer or does it stop?

**Comment by Goten87** [comment]
there is a plugin that let you shutdown you pc when your done streaming i think

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1226

**Comment by Sami32** [comment]
@ExSport  @Goten87 @taconaut @squadjot Are you intested to test this @Nadahar ["sleep" version](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1226) ?
https://we.tl/Ku5vts3y7e     ( _Windows_ EXE and JAR file for _Java 8_)

Feedback will be much appreciated ;)
Thanks.

**Comment by Nadahar** [comment]
Here's a download link for [OS X (Java 8)](http://superbum.org/downloads/UMS_Sleep_Test.dmg) if anyone wants to test that as well.
