### ISSUE TITLE
Unknown video format on TV

### ISSUE THREAD

**Issue by Fredo1650** [UniversalMediaServer/UniversalMediaServer#4952]
Hello,
I report a reading error on a video, the TV says "Unknown file format" at launch (Manhattan Lockdown.mkv)
By manually going through the transcoding file only VLC video worked. In the UMS log I noticed errors on the other transcoders that did not work.
Thank you.
![20240904_021848](https://github.com/user-attachments/assets/b573fd43-cf17-4e8e-bcd5-bcad801bccb6)
![Capture d’écran 2024-09-04 022728](https://github.com/user-attachments/assets/e0e3e825-98d4-4637-8120-6ae0dd0e9b43)
[ums_dbg_2024-09-04-00-52.zip](https://github.com/user-attachments/files/16859059/ums_dbg_2024-09-04-00-52.zip)
[ums_dbg_2024-09-04-01-21.zip](https://github.com/user-attachments/files/16859060/ums_dbg_2024-09-04-01-21.zip)

**Comment by Mik-S-UMS** [comment]
I can see UMS is picking the wrong conf and using the Samsung-UHD-2019.conf instead of Samsung-CD.conf

I think the reason is a mistake in the matching criteria in the 2019 conf where it will just match `Samsung TV` on its own.
`(QN|UA|UE|GQ|QE|TQ|QA)\d{2}(Q|QN|RU|LS|QE|AU|BU|CU|DU|S)\d[\dBCD]|Samsung TV`

**Comment by Fredo1650** [comment]
Hello, I am sending you other logs in TRACE mode.
![Capture d’écran 2024-09-05 030209](https://github.com/user-attachments/assets/dc5874b9-2298-4694-9cec-a0aabf463f07)
![Capture d’écran 2024-09-05 031510](https://github.com/user-attachments/assets/99086b01-82a8-4eea-8efc-454a792353e8)

Log UMS on the link below because it generated a 42MB file for me that I can't upload directly here 25MB maximum
https://1drv.ms/u/s!ApfA-Z5pdNqrp24YgtSfocAl5RGf?e=5OnmZn

**Comment by SurfaceS** [comment]
@SubJunk  DEBUG 2024-09-05 02:59:58.169

Starting `"C:\Program Files (x86)\Universal Media Server\bin\ffmpeg.exe" -y -loglevel info -i E:\FILMSE~1\MANHAT~1\MANHAT~1.MKV -filter_complex subtitles=E\\:/FILMSE~1/MANHAT~1/MANHAT~1.MKV:si=0 -map 0:V -map 0:a:0 -bufsize 25000k -maxrate 24000k -crf 23 -c:a copy -c:v h264_nvenc -preset llhp -pix_fmt yuv420p -f mpegts \\.\pipe\ffmpegvideo_98_1725497986959`

`OutputTextLogger [fc#0 @ 000002a4caecf700] Cannot find a matching stream for unlabeled input pad subtitles:default`

`OutputTextLogger Error binding filtergraph inputs/outputs: Invalid argument`

`Process C:\Program Files (x86)\Universal Media Server\bin\ffmpeg.exe has a return code of -22!`

**Comment by Mik-S-UMS** [comment]
There are several problems here.

The wrong conf is one and I think the some of the Samsung confs need reworking. 
A recent change was to make a newer conf to be used as a fall back if there is not a good match so newer 4K TVs will have better support instead of using the old CD or NoCD confs if there is not a match.

The loading priority of the Samsung-UHD-2019.conf should be lower than Samsung-CD.conf, or have non so it will only be used if no other conf match.
@Fredo1650 if you add `LoadingPriority = 2` to the Samsung-CD.conf this should make it use the correct one. This way you won't need to play from the transcode folder.

Next problem is transcoding and is one of the issues I found for #4950, specifically video 3 in [this post](https://www.universalmediaserver.com/forum/viewtopic.php?p=48821#p48821). This is the same error that you posted @SurfaceS. 
I think this is due to a change in FFmpeg as I compared the transcoding command between v14.5.0 and 13.10.1 and they are the same but in V14.5.0 it fails. Looking at the FFmpeg versions they are different.

There is an issue with subtitles though that causes an EOF when transcoding. This is something common to FFmpeg and Mencoder as I found both were affected.

for Mencoder, in this log it actually crashes my log viewer program after this error. 
```
TRACE 2024-09-05 03:00:07.342 [mencoder.exe-8-Timer] net.pms.io.BufferedOutputFileImpl buffered: -9,223,372,034,691,888,831 bytes / inputs: 1
TRACE 2024-09-05 03:00:09.521 [NetworkConfiguration Watcher] net.pms.network.configuration.NetworkConfiguration Checking network configuration changes
TRACE 2024-09-05 03:00:12.886 [jupnp-stream-server-97] net.pms.io.BufferedOutputFileImpl Resume Read: readCount=9223372034703292159 / writeCount=29035284
TRACE 2024-09-05 03:00:12.886 [jupnp-stream-server-97] net.pms.io.BufferedOutputFileImpl Something went wrong with the buffer, error: java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -111343359 is negative
```
I had to open it in notepad++ to copy this but scrolling below this line it would glitch the display till I had scrolled down far enough. The size of the file should not be this big for only 3min of logs, it is 200mb when extracted from the zip.

**Comment by Fredo1650** [comment]
Hello, 
I added the value LoadingPriority = 2 to the Samsung-CD.conf, it works perfectly on the TV without transcoding, Samsung-CD.conf is the correct file for this UE40D6500 TV
Thank you @Mik-S-UMS 

After this modification I noticed that my other QLED 4K TV also starts this same configuration file Samsung-CD.conf, I did not see any error on it, previously this TV used Samsung-UHD-2019.conf which I think was adapted to UHD TV
![Capture d’écran 2024-09-06 014402](https://github.com/user-attachments/assets/f7369abe-1f8d-4fd3-b734-740972ee6e30)
[ums_dbg_2024-09-06-01-41.zip](https://github.com/user-attachments/files/16901325/ums_dbg_2024-09-06-01-41.zip)

**Comment by Mik-S-UMS** [comment]
@Fredo1650 Ah this complicates things a bit, I did not notice you has 2 Samsung TVs. Might be better to undo this change for now if you want to use the 4K TV with UMS.

I don't see why the CD conf would match the 4K TV. 
I tested the matching criteria of CD with a regex tester and it does not  match anything from the 4K TV. 
It did come up with an error as there is a "/" at the end of the line of `UserAgentSearch` which it says is invalid so this might be a factor. You could try removing it to test.

My knowledge about regex is very limited so maybe @SubJunk can improve it.

I did notice you had disabled transcoding so that could be why it is working as it is not doing any checks to see if the format is supported, then again the CD conf is very bare so would allow most things to work. This should be updated as I doubt that TV can play h265.

**Comment by Fredo1650** [comment]
@SurfaceS 
Hello, 
I made the changes you advised me to make, it now works very well, both televisions have the correct configuration.
Thank you.
![Capture d’écran 2024-09-07 003909](https://github.com/user-attachments/assets/e7347620-ee8e-4938-ada0-619f0f21720d)
