### ISSUE TITLE
[Suggestion] Disable defer to tsMuxeR option by default

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#503]
I'm unsure about this one so I want your opinions @UniversalMediaServer/developers 

Here is a pros and cons list for using the defer to tsMuxeR option:

Pros:
Less CPU-usage - this is the only big pro but it's a big one.
Likely to use less bandwidth - renderers that transcode to H.264 will use similar bandwidth.

Cons:
Audio sync is often off on PS3, especially after seeking
Seems to cause mysterious bugs like streams quitting half way (the forum is littered with it in logs)
Files don't play to the end (a few seconds is cut off)

I think for overall stability we should disable the option by default but what do you guys think?

**Comment by WolfganP** [comment]
You probably know by now that I'm a big proponent of avoiding video transcode at all costs (quality, resources utilization), so re-muxing is a must for me. 
If tsmuxer introduces side effects, can we force the remuxing features by using ffmpeg or mencoder instead? (ie enforce -v copy in global or renderer specific settings)

**Comment by SubJunk** [comment]
@WolfganP this isn't about removing the feature, it's about disabling it by default, so whatever we do it won't affect your current functionality :)
I tried having FFmpeg remux things before (released in version 2.6.1) but it was problematic. I guess I can try it again with a newer FFmpeg version.

**Comment by WolfganP** [comment]
@SubJunk yes, understood. I just wanted to cheer in and add my 2cents in making UMS a mean and lean remuxing video machine :-)
That's why I always look for ways to forcing it w/o having to resort to TRANSCODE folder or the like; and suggested adding "-v copy" option to the engines to enforce it (at main setting? as a transcoding quality profile? at renderer level?)
Count me in for the remuxing tests!

**Comment by SubJunk** [comment]
@WolfganP I've made a quick build that muxes via FFmpeg whenever it would normally mux via tsMuxeR, please test it http://www.spirton.com/uploads/UMS/UMS-199876e.exe
I tested it on my TV and it worked for a file but it will need testing on many renderers and with many files before I will consider making it a permanent change - we have created enough bugs lately so we don't need more :) Thanks for the help

**Comment by ExSport** [comment]
Nice @SubJunk !
Will test it in few weeks on real renderers or days on Android Mobile or
with some local Windows sw renderer...
Dne 18. 3. 2015 0:51 "SubJunk" <notifications@github.com> napsal(a):

**Comment by SubJunk** [comment]
@ExSport great, thanks!

**Comment by WolfganP** [comment]
I'll test it as well this weekend (been on travel for a while and couldn't get to test on my setup). Thx!

**Comment by SubJunk** [comment]
This is done in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/07496796307e2f7b773812cca6d1fb8e211bf439

It can still be enabled but this will make playback more stable for more users I think.

**Comment by ExSport** [comment]
@SubJunk And I think many users left PMS due to removing tsMuxeR remuxing completely :)
From my side it is my preferred engine when no subs are needed :+1:

**Comment by Nadahar** [comment]
Why was it removed? Did it have a lot of bugs/issues, or was it just lack of subtitle support?

**Comment by ExSport** [comment]
Yes, that PMS developers concluded it is buggy. But SubJunk with other testers made it stably usable so it wasn't never removed from UMS.
UMS logic it clever enough to force transcoding if tsMuxeR is used and subs are required or encoding parameters are not supported by renderer. So I think defaults were changed due to other possible problems like A/V sync or unplayable files on some systems (results are very sensitive to original file, FFmpeg/MEncoder version etc...)
On Windows I used it for ages (my parents) without major problem but last time father informed me that some files were unsynced so maybe some new FFmpeg/MEncoder parameters or updated versions introduced some A/V sync problem (I spotted some similar posts in forum). So maybe it is a reason why by default it is disabled. @SubJunk knows :+1:

**Comment by SubJunk** [comment]
@Nadahar @ExSport when it works it's the best option, but there are a couple of issues with it:

1) PS3 doesn't support offsets properly in .ts files, so when many MKV videos are remuxed to PS3 the audio sync is out
2) There are quite a few logs on the forums from people who get crashes with tsMuxeR that we haven't been able to solve

I really wish FFmpeg were more stable for MPEG-TS remuxing but it is even less stable
