### ISSUE TITLE
High idle CPU use in 5.x

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#513]
Apparently this is still happening, even when the program is minimized: http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=2949&start=10

**Comment by valib** [comment]
It seems to me as a bug in the startPoll() in the Chromecast.player. In the logs there are every 1 sec an error:

Bad chromecast mediastate javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset

It could be also the Chomecast or the network problem. There is also running BubbleUPnP or TumpoCast on the same computer as UMS is running. It may also caused this problem. UMS version 4.4.0 is working OK because the Chromecast support was introduced in the 5.0 version

**Comment by ExSport** [comment]
Time to document how to disable Chromecast support:
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/526

**Comment by polygirl** [comment]
We presume this has been fixed in a later version of UMS so we're closing.
