### ISSUE TITLE
General Configuration Settings - System Tray and Taskbar - Window 7

### ISSUE THREAD

**Issue by punkle01** [UniversalMediaServer/UniversalMediaServer#557]
Please add a box which may or may not be checked by the user with the following:

Only show UMS in the Taskbar when the program window is opened to the Desktop.

**Comment by Sami32** [comment]
@punkle01 Do that mean that you don't want see this icon in the TaskBar when UMS is running minimized or as a service ?
It's just an aesthetic wish or you find that your TaskBar is too full ?

**Comment by Nadahar** [comment]
I'm assuming this is about Windows? Generally Java is quite limited in its possibilities to such customization because of its OS agnostic approach. Visibility in the taskbar is tied to the GUI, and Windows will as a standard show any application with a GUI. Running UMS as a service or in headless mode should mean that it won't show up. 

@Sami32 When UMS is running as a service, UMS doesn't show neither in the taskbar nor the tray as far as I know. A service in Windows doesn't have a "connection" to a desktop, and actually making a service interact with the desktop requires some trickery that I'm not even sure is possible under Java. A service runs independend of any logged in user and thus there isn't always a desktop there to interact with. A computer running terminal services can also have the opposite situation, that there are multiple users and multiple desktops running at once on the same computer. Services are therefore completely isolated from this.

**Comment by Sami32** [comment]
Feel free to reopen it if necessary.
