### ISSUE TITLE
Java versioning

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#571]
@UniversalMediaServer/developers a couple of questions it would be good to have your opinion on:

1) How long should we continue to release versions for Java 6?
2) How long should we wait until we convert master to Java 8?

**Comment by Optimusprimeums** [comment]
@Subjunk My view (OSX Build view) for the Java 6 releases is the majority of downloads are for this version. Java 6 is able to be used on OSX 10.7.3 and below but Java 7 is 10.7.3+ and Java 8 is 10.8.3+ so thats the limitation we have transitioning to a java 7/8 only on OSX
Now personally, I think we should transition master and make the default Java 8 as i'm sure we will have the same discussion when java 7 support stops. I think that a 6 month warning letting all Java 6 users know about us stopping support and a warning in program with the same warning would suffice. Plus maybe starting a forum discussion on the topic to gain some valuable feedback would help.

**Comment by SubJunk** [comment]
@Optimusprimeums thanks for your thoughts, lots of good ideas in there. I'm not in a rush to transition from 7 to 8 because the differences between them are not that big, but 6 is a bit annoying. We have so many differences just for that version. But if people still get use out of it I guess we continue with it.

**Comment by Sami32** [comment]
@SubJunk The first question was already answered and acted.

The second one could come not before the end of the next year ? As Java 9 will give a good modularity improvement opportunity, understanding more light weight.
But the download statistic should give us a better idea of the timing: 50% for Linux, 15% for OSX and 62% for Windows users as for now.

**Comment by SubJunk** [comment]
@Sami32 the download stats are skewed because we default to Java 7 downloads. But yes I think it's too early to switch to Java 8 fully.

**Comment by SubJunk** [comment]
We can reopen this in the future if we want to ask again

**Comment by Sami32** [comment]
Java 7 could be the default download, do not mean that people will use it on their Java 8 installed version, or after recognized their mistake they will also download the Java 8 version as well.

Of course, they could also install Java 7 just for UMS, but i don't think that there is a huge amount of users doing that; that's said i could be wrong ;-)

**Comment by Nadahar** [comment]
@Sami32 I disagree. I didn't even have Java on my computer until I installed UMS. The Windows installer will automatically install Java 7 if needed. Why would people actually choose the Java 7 version? There's nothing in it for them, there's no "advantage" in using Java 7 that I know of. Java 8 can also run Java 7 code with a few exceptions.

The only reason for anyone to still use Java 7 that I know of is that some Linux distros still have Java 7 as the default Java version and installing Java 8 can be a bit more work than Java 7 in those instances. In addition I guess some Windows XP users might be scared to use Java 7 because Oracle Java 8 is "no longer supported" on Windows XP. It's apparent though that this isn't by choice by Oracle but some deal they have with Microsoft that's forcing them to say so. AFAIK the latest versions of Java 8 still works perfectly on XP and my guess is that new versions will keep on working. This is simply one of Microsofts dirty tricks to force people to upgrade away from XP.

**Comment by Sami32** [comment]
@nadahar I personnaly have issues using Java 8 on Windows XP and solved it using Java 7.

So, except if you like answer to users or search and eventually solve their issues, better to stuck to Java 7 for now. That's for me the advantage. My point of view.

**Comment by Nadahar** [comment]
@Sami32 What's the issue? Have you tried an older Java 8 version from before they "discontinued" XP support?

**Comment by Sami32** [comment]
The one that you mentioned but also 60. I'm too mazy to search but you'll find them in the closed issues.
> AFAIK the latest versions of Java 8 still works perfectly on XP and my guess is that new versions will keep on working
