### ISSUE TITLE
[Suggestion] Remove or move some configuration options from the user interface

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#586]
@UniversalMediaServer/developers It could be a good idea to move some of the configuration options out of the user interface, and make sure they are well-documented in UMS.conf for advanced users. Either that or we make an "advanced settings" tab which contains a lot of the options we offer.
A lot of programs do this and it can help the program seem more accessible for new users, who see those options and get daunted about having to customize every setting.

We were recently reviewed by PCMag Australia and one of the biggest complaints they had was the "confusing and annoying setup", which is weird considering that UMS usually works best with no configuration, so I can only assume that the reviewer was daunted by the optional settings.

Here's the review by the way http://au.pcmag.com/universal-media-server/34391/review/universal-media-server

**Comment by Nadahar** [comment]
I'm pretty new to UMS, and I must agree that the user interface is somewhat cluttered and that the logics is hard to grasp. I think I've figured out what most things do now, but that's partly because I've looked at the source code and done some tracing to check what the real effect is.

I wouldn't move more functionality into UMS.conf, there's actually quite a few things I'd like to see added to the GUI from there instead. In my opinion the worst with the GUI is it's lack of logic/structure and that a lot of the options have unclear/lacking description and mouse-over help text. I'd do a big reorganization of the tabs, create subgroups/frames for different topics within each tab and then look at the naming/description of the choices. 

UMS already have "Hide advanced features" but I'm not sure if that's enabled or not by default. It should probably, if it's not already, be set in the Wizard, and it should probably also hide more than it does today. I'm not sure I'd put all the "advanced settings" on a separate tab, but rather hide them when show advanced settings is off. There also shouldn't be any reason to have restart the application for changing this setting, it should be possible for the GUI to update/reinitialize itself. Start minimized and autostart should probably also be done in the Wizard if it's not already (don't really remember what was in the Wizard).

**Comment by SubJunk** [comment]
@Nadahar yeah I agree, an overhaul could be really beneficial. Unfortunately we inherited the GUI clutter from our predecessor and made it worse with each new feature. Maybe I should do some mockups in Photoshop to help with planning

**Comment by Sami32** [comment]
It's look like we all agree on that ;-)
We can already begin by moving some of them from the GUI into the configuration files and later reorganize the GUI ?

**Comment by Nadahar** [comment]
@Sami32 I never said I think it's a good idea to remove options from the GUI, in fact I said the opposite. What I do think is a good idea is to organize it differently and to hide settings depending on the user knowledge level. I started work on this, but never finished it. As per now, the "Logs" tab is the only one that uses [ViewLevel](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/newgui/ViewLevel.java). 

The fact is that managing layouts in Swing is a terrible hazzle. The documentation is sparse and many of the layout managers are hard to work width and/or doesn't have the needed functionality. You can get it looking good on a certain setup, and then launch it on another OS/desktop manager or resolution and it looks totally off. As I'm not going to be coding anything anytime soon, I doubt there's anyone actually willing to do this.

**Comment by Sami32** [comment]
@Nadahar My misundersting of your words, as usual...
> As I see it the resample setting shouldn't be there, there should be a uniform way to handle this across renderers that also makes sense to the users. The way it is now I doubt very many users understand the consequences of the choice they make.

Anyway, thanks for clarifying things and pointing me to this work, i never cheched that part yet, not my cup of tea though...

**Comment by SubJunk** [comment]
We have made some improvements in the upcoming v12 browser-based settings so closing this
