### ISSUE TITLE
[Enhancement] Improve New Media feature

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#626]
I propose the following ways to make the New Media feature be more user-friendly. I don't use our current New Media feature and these are the changes that would make me use it, and I suspect a lot of other users are the same.

1) Track all folders by default, instead of opt-in as it is now.
2) In regular folders (not in the New Media folder), watched videos should have thumbnail overlays. The thumbnail should be 50% darker than normal, and have the text "watched" on it. We already have the ability in the code to overlay text onto thumbnails.
3) Add a user configuration option to hide watched videos, which basically merges the functionality of New Media into every folder.

@UniversalMediaServer/developers what do you guys think?

**Comment by Nadahar** [comment]
@SubJunk I know I'm not in the target group here, and I don't know the New Media feature and what it does. I think what you suggest sounds reasonable though, but only for movies. I doubt you want to just be able to listen to a tune or watch a picture only once. Another thing I'm wondering is how much of the movie do you have to watch before it's considered "watched"? Does merely starting it count? In that case, I don't think the "hide" feature would be very useful. In 2) there should probably be an option to mark watched videos with text as well, since far from all renderers show thumbnails.

**Comment by SubJunk** [comment]
@Nadahar we have logic for detecting whether a video has been watched. I think it's marked as watched when 90% has been viewed, since that takes into account long credits for movies. I can't remember what the percentage we use is.

I agree completely that it should only be for videos.

Good point about the text. We could control that at the renderer level, so we can default to using text to be safe, but enable it on the renderers that we know use thumbnails.

**Comment by Nadahar** [comment]
@SubJunk Sounds good then, but won't this make the New Media feature redundant? Are you suggesting to remove that then? Or do you think it'd still be useful for some to only have new medias hidden in the New Media folder (if 3) is off)?

**Comment by SubJunk** [comment]
@Nadahar it might be useful for some people to have an unfiltered folder as well as the New Media one. Personally I'd like mine to be filtered. I'm happy for input and discussion about it to figure out which implementation will be the best for our users.

**Comment by Nadahar** [comment]
@SubJunk I'm just thinking of how that could be structured to make sense for the average user that doesn't know UMS in and out. Maybe it should be two options:
* A checkbox for "Tag watched videos" with a tooltip text that explains icon overlay or title text tagging depending on rendering device
* A combobox or a radio button group where you could select "New media handling":
  1. None
  2. Show new, unplayed media in a separate folder
  3. Hide watched videos when browsing

I couldn't find any good names for the options at the moment, but it's the structuring that's my point. 

One problem I see is that people might want other types of media than just videos showing up in "new media", but at the same time I doubt they'd want the other types hidden when played/watched. It's a bit hard to know how to structure this in a good way, because the functionality is so similar. If they are kept separate and controlled separatly, I'm afraid it can get very confusing. If not, I'm afraid it will be hard to give everyone their ideal functionality. 

Maybe the options should be different in "normal" and "advanced" mode, but that would require some "translation rules" between the two systems when people switch view mode.

**Comment by Nadahar** [comment]
@SubJunk Rendererconfiguration already has ```SendFolderThumbnails =``` which could be used to determine icon overlay or text. Unfortunately it defaults to true, so users on renderers without thumbnail support would probably never know about it (```DefaultRenderer.conf``` uses default).

**Comment by SubJunk** [comment]
I've started a branch for this, and a PR to discuss it https://github.com/UniversalMediaServer/UniversalMediaServer/pull/673

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/942

**Comment by SubJunk** [comment]
This issue is different to #323 and has been completed, but yes we should work on the sorting in our dynamic folders
