### ISSUE TITLE
ums.conf option "ffmpeg_mencoder_subtitles" is not used in codebase

### ISSUE THREAD

**Issue by ler0y** [UniversalMediaServer/UniversalMediaServer#638]
Next option mentioned in ums.conf is not used anymore in the codebase:

    # Defer to MEncoder when transcoding subtitles
    # --------------------------------------------
    # Whether FFmpeg should defer to MEncoder when there are subtitles that need
    # to be transcoded.
    # Both engines can handle subtitles, but MEncoder is more stable right now.
    # Default: true
    ffmpeg_mencoder_subtitles = 

I guess that maybe it should be replaced with the undocumented option :

ffmpeg_mencoder_problematic_subtitles

Thanks in advance for looking into this :)

**Comment by ExSport** [comment]
Not sure if there should be such option. It is better to use it by default as when ffmpeg itself is used, for any internal subs there is a need of subtitle extraction which takes minutes. Due to this delay file seems to user as unplayable because renderer closes connection earlier.
Due to this I expect UMS will use mencoder automatically in such cases without any confusing configuration and to avoid users to disable it by accident as they will not know consequences. Until ffmpeg internal subs support will be better, deferring to mencoder is a must from my point of view :)

**Comment by Sami32** [comment]
@SubJunk @valib Can i do a PR ? because check the code and saw the same things so your eagle's eyes are welcome ;-)

**Comment by valib** [comment]
@Sami32 feel free to do it.

**Comment by Sami32** [comment]
@valib Done.

**Comment by Sami32** [comment]
@ler0y @valib Could you closed this issue now ?
