### ISSUE TITLE
MKV movies with PS4. After server crash issue

### ISSUE THREAD

**Issue by FishMario** [UniversalMediaServer/UniversalMediaServer#652]
Hello! I think that would be searched by many, or at least be interesting and helpful for few.
Story:
I started watching movie.mkv and default lang. was eng, so i went back to folder and selected my lang.
Everything was ok till the moment, when bitrate somehow dropped to 0 and the movie stopped for few mins, then ps4 gave me some msg and closed the video, so i tried to restart server and all was ok till the moment...
Issue:
I clicked resume movie.mkv in the Recent list, and it resumed the video with Eng audio.
Then i moved back to list and choose the other file from mkv. And movie.mkv started from very begging without ANY option of FF to the point it stopped. 
That hurts. I saw there was same issues with ps3, but im not sure it was the same.

I not spec, but im sure, that the core of stop-problem is:
08-23 04:13:24  Started playing movie.mkv on your PlayStation 4
08-23 05:37:40  Stopped playing movie.mkv on your PlayStation 4
08-23 05:37:47  Sending kill -14 to the Unix process: 5191

But resuming in basic lang and FF RW problem is also pretty bad

**Comment by Sami32** [comment]
@FishMario Do you have some full trace log ? AFAIK we don't have any PS4 to test ourself so your log will be very helpful.
You can follow these simple steps:
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556

**Comment by Nadahar** [comment]
@Sami32 I don't think you'd need a trace log or a PS4 for reproduce this. It's basically that the resume file doesn't "remember" if you've chosen a particular transcode method. Its no suprise to me, I think it only stores the location in the file, not any other parameters. That is as much a feature as a bug, it means that the replay point will be the same even if settings are changed.

I think the correct solution too this issue would have been to configure that subtitle languages correctly so there were no need to use the transcode folder to pick the correct language.

**Comment by Sami32** [comment]
@Nadahar OK, i will test a little more deeply as i never get that issue.

**Comment by Sami32** [comment]
@Nadahar I never tryied with dual audio or with internal subtitles.
For me trying to download such short movie with my low connection for testing, or install software to create one, is much painful that check a full trace log...
You are good at working without log, not like me ;-) So testing will take me some time...

**Comment by Nadahar** [comment]
@Sami32 I'm sorry I was a bit to fast and thought this was about subtitles not audio. However, the situation is the same: When using the transcode folder to select language you're actually not using the system as intended. You're supposed to configure it so that UMS selects the correct language and other transcoding settings automatically. I see the transcode folder first and foremost as a "debug tool" to quickly test other configurations.

The resume function only stores where in the file you stopped watching it, not what transcode settings were used during last playback. Since resume files are not available in the transcode folder, resuming with overridden settings isn't available. Resuming a file will only work with the default/automatic transcode settings as a consequence of the way this is designed. It's not a bug, it's how it has to be unless you design the system differently.

That's why I'm saying that what should have been done to resolve this was to configure the languages for audio and subtitles correcly on the transcode tab instead. That would make the default/automatic choice select the correct audio, and using the resume file would also result in the correct audio being played.

When it comes to the missing ff/rw/seek functionality that is a known limitation when transcoding on some renderers. I don't know the exact details of why it is the way it is or if there is a solution to this, I just know that it's the way it is for now. It's therefore obvious to me that you can't use the transcode folder and then fast forward to where you left off on a renderer where fast forwarding doesn't work when transcoding. The only solution is therefore to make the configuration correct and avoid the transcode folder alltogether.

I don't know if I have such a file or what file that would be (I probably have it). But, you don't need it to demonstrate the "problem". All you need to do is to go into the transcode folder on any file and play it for some minutes with a different transcoding that what the automatic would choose. Stop it and then try to play the resume file, and you will see that the automatic settings will be used when resuming, not the settings chosen from the transcoding folder when you started playing the video.

**Comment by Sami32** [comment]
@Nadahar I didn't understood that TRANSCODE folder was used.
I'll test it tomorrow, if i can get my movie torrent download finished...
As perhaps i tried "resume" function one time i don't much about it, same for many other functions as i use it rarely and very simply, so thanks for sharing :-)

About FF/RW issue while transcoding, i think it's just because since the beginnning of UMS incorrect DLNA.ORG_OP was set; i mean it need to be 11 and not 10.

**Comment by Nadahar** [comment]
I think this can be closed. Configuring the correct languages in the transcoding settings would resolve the language issue, the FF/RW is another problem that I'm sure already have one or more open issues.

**Comment by Sami32** [comment]
**UMS don't take the audio user's language preferences in consideration**, but instead use the audio default movie preference.
That's said, you can change it from you renderer.

**Comment by Sami32** [comment]
Could be reopen when a full trace log will be given.
