### ISSUE TITLE
New Media / Cache folders fail to load past 20 items

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#653]
On my Panasonic VT60 TV, when I go into the New Media or Cache folders they load perfectly until I scroll past the 20th item in the main folder, then the whole folder goes blank.
It doesn't happen on subfolders - they work perfectly, as do all other non-New Media folders.
So it seems that something about the New Media folder is stopping the renderer from receiving the next set of 20 items.

I also tested version 3.3.0 to see if it was a recent issue but it happened with that version too.

To produce these logs I started with a clean install of the latest code, set a folder to share and include in the new media folder, went straight to the New Media folder and scrolled down, which usually loads the next 20 items:

http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656&p=17787#p17787

@SharkHunter any ideas?

**Comment by SharkHunter** [comment]
The media monitor is no special from a normal folder. Looks like there are new requests for anything but the first 20 items.
How does it look in the web (for example)?

**Comment by SubJunk** [comment]
@SharkHunter it loads perfectly on the web interface

**Comment by SubJunk** [comment]
@SharkHunter I also tested by enabling "include in the new media folder" on a folder full of videos, instead of full of folders like the the logs, and the same thing happened

**Comment by SubJunk** [comment]
This is also now happening with all monitored folders in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/673 and I'm still not sure why

**Comment by Nadahar** [comment]
@SubJunk I pulled #673 and added the whole library to "New media" (which wasn't localized by the way). I couldn't reproduce the bug on either the PS3 or the Onkyo renderers that I have available. The PS3 doesn't fetch one page at a time, so that's no big surprise, but the Onkyo does - and was still fine. It's hard to figure out what's happening when you can't reproduce it. If I were you I'd install Wireshark (if you haven't already), it's really great for tracking down such problems. Start capturing before trying to browse, reproduce the problem and stop capturing. You can then filter and do all sort of this with the packages, but what I've found easiest is to find the package with the correct browse request, rightclick it and select ```Follow TCP Stream```. That will assemble all the packages into a long "text document" with all the requests and responses after each other in the correct order. It makes it extremely easy to see what is requested and what is delivered as a response, and see where the communication is going wrong.

Btw., I did a push of #673 to crowdin, so it's registered as a separate branch there now meaning that new terms are translatable for the translators already now. It requires you to upload ```messages.properties``` into this branch whenever you make changes in it though.

**Comment by SubJunk** [comment]
I've confirmed this issue on a Panasonic ST50 as well, and confirmed it does not happen on PS3, as you found. So for now it seems specific to Panasonic TVs. I'll try using Wireshark.

**Comment by Sami32** [comment]
@subjunk Can you acces to your "cache" with _Cling Workbench_ ?

**Comment by Sami32** [comment]
@SubJunk Actually, this is a very interesting bug, not because it can also freeze, but because in the process list we can saw tsMuxeR and many FFmpeg instances running and using sometimes 100% CPU and many RAM;
@skeptical https://github.com/UniversalMediaServer/UniversalMediaServer/pull/899
The funny part, for Panasonic users, is that it is making UMS displaying many different streaming with time display 8-D
[Uploading UMS-debugSUP20ds.cache.txt…]()
[UMS-debug_SUPa20dsCache.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/332216/UMS-debug_SUPa20dsCache.txt)

**Comment by Sami32** [comment]
I guess 20 items bug limit come from `<RequestedCount>20</RequestedCount>`, after that i don't know what happen but so many renderer GET requests are not satisfact ?

WIRESHARK (ip.src==192.168.1.28 and ip.dst==192.168.1.69 and tcp.port==55000)
[Cache_images21.7z.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/339716/Cache_images21.7z.txt)

**Comment by valib** [comment]
I can confirm that. It works only for the first 20 items whose are asked by the renderer and the second browsing request which starts at 21 is not working.

**Comment by Sami32** [comment]
@valib Congratulations, you fix it ;-)

**Comment by SubJunk** [comment]
@valib I'm excited about this fix!

**Comment by valib** [comment]
@SubJunk @Sami32 not at all :-)

**Comment by SubJunk** [comment]
Unfortunately for me this isn't fixed - I tried loading the New Media folder using https://github.com/UniversalMediaServer/UniversalMediaServer/commit/e3ae18a3928ec0b9b76ebb6f8da5d0b623d8789b and the same thing happened

**Comment by valib** [comment]
@SubJunk I fixed only MediaLibraryFolder and for NewMedia it could be possibly the same. I will check it.

**Comment by Sami32** [comment]
I tried only "cache" browsing, and it was fine for me, no more 20 items limitation.

**Comment by SubJunk** [comment]
@valib you're right the same fix worked, applied in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/08243753f7a568d5d1678e3609014383f049da89
Thanks!
