### ISSUE TITLE
Latest trunk version compilation error

### ISSUE THREAD

**Issue by ykowalewski** [UniversalMediaServer/UniversalMediaServer#682]
I try to compile newst version from repository and get test errors. 
https://gist.github.com/ykowalewski/05792b26c99463ec7c85

**Comment by Nadahar** [comment]
@ykowalewski I just tried to build, and got none of those errors. But I'm building from Windows, not Linux, and I have Maven 3.3.3 instead of 3.2.1. I don't know if any of these things matter, but the test errors don't seem like "real" errors - it's mostly class not found.

I would pull/clone again to make sure all files are there. Then I would do
```
mvn clean install
```

**Comment by ykowalewski** [comment]
It's not so important because I just want to check newest version. I get error in line PMS.get() where instance is not created properly. 
I updated maven to newest version and I get the same error...

**Comment by Nadahar** [comment]
@ykowalewski Have you refreshed / redownloaded the UMS source?
