### ISSUE TITLE
not starting up UMS-5.2.3

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#683]
i installed 5.2.3 and its not starting up anymore
when i go back to 5.2.2 it starts up again
im i doing somthing wrong

**Comment by Nadahar** [comment]
@Goten87 We need some more information. What OS do you have and what version of UMS do you use (Java 6, 7 or 8)? What happens when you try to start it? What does the log file say?

**Comment by Goten87** [comment]
I use Java 7 on Windows 7 ultimate
And it just don't start up I can't see ums at all so no log file is made

**Comment by Nadahar** [comment]
@Goten87 On Windows the logfile is probably ```C:\ProgramData\UMS\debug.log```. Even though you don't see the GUI, it's probably doing something and failing, so the log file would be interesting. But, if you reinstalled 5.2.2 that logfile is probably overwritten by now.

**Comment by Nadahar** [comment]
I just tried to download and install UMS on a clean Windows machine. One of SourceForge's mirrors seemed to have a problem, I just got a installer file of around 200 KiB until I tried another mirror. That can't be the same problem however, since that file is so small it doesn't even contain the installer. You did go through the installation for 5.2.3, right?

Once I chose a different mirror, I was able to get the file and install and run UMS without any issues.

@SubJunk I don't know if you have any control over the mirrors, but it seems there's a bad image of 5.2.3 Java7 on at least on of the mirrors.

**Comment by Goten87** [comment]
my install file is 71,4 MB
just installed it again will now see what it will do

**Comment by Nadahar** [comment]
@Goten87 Can you try to find the logfile? If you press ```Windows key``` + ```r``` and then enter ```%programdata%\UMS``` in the ```Run``` dialog a window at the right location should open. It's the file called debug.log in there.

It should be possible to attach text files to github issues now, so you can attach the file to the answer here.

**Comment by Goten87** [comment]
@Nadahar like I sayed its not starting up at all its not starting Java as well
I see nothing and the log file keeps the old one from befor
It's only when I wanne use my costum profile if I do the normal one it works

**Comment by Nadahar** [comment]
Ah, ok - I didn't understand that.

**Comment by Nadahar** [comment]
@Goten87 I found the bug - it is fixed in e38c7a1.

**Comment by Nadahar** [comment]
@SubJunk This is caused by my locale changes. It only affects the profile chooser since that's called before the configuration is loaded. I don't know how critical you think it is, and if we should hurry to get the fix out or wait for 5.2.4.
