### ISSUE TITLE
Renderer config files that hopefully can be added

### ISSUE THREAD

**Issue by ler0y** [UniversalMediaServer/UniversalMediaServer#694]
Hello UMS Developers,

I just want to mention here on Github the renderer config files (profiles) that I have wrote for the 'BubbleUPnP Media Renderer-MX Player' and 'Windows Media Player Renderer' posted on the forum.
I hope they can be included into UMS.

BubbleUPnP Media Renderer-MX Player:
http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=2574&start=10#p18473

Windows Media Player Renderer:
http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=4149

They are though fully tested by me and works great :-)
All the 'Supported =  ' formats and codecs were tested with the media files that I have collected in years.
All related notes/issues can be found in the config files.

**Comment by Sami32** [comment]
@ler0y @SubJunk Since these PR https://github.com/UniversalMediaServer/UniversalMediaServer/pull/697 include it already and this recent PR https://github.com/UniversalMediaServer/UniversalMediaServer/pull/853 update the WMP renderer, could this issue be closed ?
And what about the PR https://github.com/UniversalMediaServer/UniversalMediaServer/pull/697, do you want merge as it is now ?
