### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#695]
It would be cool to get continuous integration working through GitHub. Travis might be a good option:

http://www.codeaffine.com/2014/09/01/travis-continuous-integration-for-github-projects/

**Comment by Nadahar** [comment]
@SubJunk I'm not sure I really understand what it does. 

Is it based solely on our tests? They cover a very small part only, and to be honest I think only relatively simple methods is viable for such tests, when you get into more complicated situations you have to simulate a lot to actually be able to test. This is so much work that I'd rather put it into writing robust code.

We also have a lot of warnings as it is, it doesn't help as long as nobody cares. Findbugs currently lists 305 bugs in the branch I'm working on now (#689), PMD lists hundreds of issues (although many of them aren't bugs, they mask the ones that are), Eclipse usually displays around 190 issues with the UMS code, and I've installed a trial of an analyzing tool called "ThreadSafe" lately in that gives 448 issues, many of whom are direct bugs.

In #679 I've started the daunting task of trying to resolve the locale and encoding/charset issues in Findbugs, but I've currently "fixed" 18 of of 65 listed issued related only to character encoding. I don't get any response to my questions though, which makes me want to give it up since it means an increadible amount of investigation on my part to figure out how it should be.

What I'm trying to say is that we're not using the tools we currently have, so how would another one help? Or did I misunderstand this, and continous integration is really about something completely different?

**Comment by SubJunk** [comment]
Continuous integration runs tests when you create a PR. Also I like anything that gives more visibility to testing because then it serves as a constant reminder to us to write more tests, and writing tests is a great way to identify bugs.

**Comment by Nadahar** [comment]
Sure, it doesn't look like there's much job to get it up and running so why not? But I still feel that the tests can only do so much, and that things like findbugs and other analysis tools should get more attention.

**Comment by SubJunk** [comment]
Closing this now since it's done
