### ISSUE TITLE
Losing network connection over time

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#702]
It seems like if I leave UMS running for long enough, it loses its connection to my network adapter. The dropdown stops showing the IP address, e.g. before:

![Working](http://i.imgur.com/atxrtY0.jpg)

and after:

![Broken](http://i.imgur.com/MBitxNQ.jpg)

Restarting UMS fixes it immediately. Has anyone else experienced this? @UniversalMediaServer/developers 

I'll try to get logs next time it happens, which is about every day.

**Comment by Nadahar** [comment]
@SubJunk This is strange but interesting. Are you using HTTPv2? If so, you should try v1 to see if there problem is there as well? 

As I've mentioned before I think there are some bugs in the v2/netty code in that it doesn't release resources like it should. I looked at it at one stage, but then there was something else and something else and I never got to the bottom of it. Maybe this leads to some kind of "resource exhaustion" over time and results in loss of connectivity, I don't know. But it would be interesting to see if the problem was still therer with v1.

**Comment by Optimusprimeums** [comment]
@SubJunk Haven't seen it myself and I run UMS 24hrs-7 days so i'll keep the logs and i'll keep an eye out for it

**Comment by SubJunk** [comment]
It may have something to do with the operating system going to sleep

**Comment by Sami32** [comment]
@SubJunk So do you get this issue using HTTP v1 method ?
Or the latest sleeping patch solved it already ?

**Comment by SubJunk** [comment]
Yeah I switched my network setup around so I'm not getting this anymore
