### ISSUE TITLE
Manage folder/files via web interface

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#707]
I think the best way to implement more advanced folder/file management would be to replace our current "Shared Folders" panel with a web-based one. We can do this by adding elements to our existing web interface.
This can be done in three stages. Stage 1 is to implement it with no new features, which means adding the ability to add, remove and reorder folders. We can leave the "scan all shared folders" button in the main interface maybe.

Stage 2 is adding a GUI to our existing feature of virtual folders (the virtual_folders setting) which allows fake-renaming (aliasing I guess) of folders - meaning the folder is not renamed on the hard drive but we use the custom name.

Stage 3 is new features, which for now involves the ability to mark videos as watched/unwatched.

What do you guys think @UniversalMediaServer/developers ?

**Comment by Nadahar** [comment]
@SubJunk Personally I don't like web interfaces, they are slow, unreliable and give little feedback. That said, the features you propse seems good, and having the possibility to do it from the web interface as well can't hurt - I just don't see the need to remove it from the GUI.

I do agree that the current GUI implementation is bad, but there should be no problem to make a better one. Working with Swing can be frustrating, but I don't know if html/css is any better. I guess that all depends on what one is more familiar with. If we go for Java 8 you can use that as well in the GUI if I got it right, with Java FX?

**Comment by SubJunk** [comment]
@Nadahar I'm very comfortable with HTML/CSS/JavaScript and I think it requires far fewer lines of code to achieve the same things as Swing. My day job is working with those languages/syntaxes. Our main competitor, Plex, do everything via web interface AFAIK and it has worked great for them, and I think that's a trend with all programs that will continue.

It also fits well with our "universal" philosophy since it means the settings are accessible from any device instead of just the one computer. We do already have the ability to set some settings by playing fake videos over DLNA which is awesome but that's more of a clever hack than an actual interface.

I don't see any reason why web interfaces need to be slow, unreliable or give little feedback. I think if they're done right they can be superior to non-web interfaces and certainly easier to implement IMO.

Using HTML within Java is a nice approach as long as it doesn't require too much rework - I'd rather have a really polished web interface than a mediocre web and Java interface. I'm happy for 6.0.0 to be Java 8-only if we would benefit from that.

**Comment by Nadahar** [comment]
@SubJunk

> Our main competitor, Plex, do everything via web interface AFAIK and it has worked great for them, and I think that's a trend with all programs that will continue.

When I looked at the different media servers before choosing UMS, Plex's web interface approach was my main reason for excluding Plex (together with the "Freemium" thing that I also hate). I'm not saying that it's the stance of the average user, but I don't think I'm alone at disliking webinterfaces. By all means, I have nothing against webinterfaces as a "quick and dirty" backup solution for doing some small stuff from any convenient device, but when I'm forced to use it for everything I always look elsewhere. 

I think the "trend" of moving towards web interfaces has been around for some 15 years now, and as I see it it has partly backfired. When you think of it, the "invention" of the "app" is simply a way to go back from the universal web interface to a more device specific interface. Most of the things that "apps" do on the mobile platform could just as easily have bee done in a browser, yet we see a development the other way. I think it's simply due to the fact that the experience is better when you can give direct feedback (which you need javascript to do in browsers, and that's another can of worms with it's incompatibilites and extremely slow processing) and things run under a more controlled environment. The editor I'm typing in right now is a good example, I have a 6 core i7-5820 with 15GB RAM and a GTX 970 GPU that can take anything you throw at it of new games without breaking a sweat. Still, this editor often lags and generally do "strange things". At times, I'm several characters in front of what's being displayed. I'd much rather be typing this in a real GUI.

I worked a lot with miscellaneous IT systems in the first part of the 2000's and I hated it every time anything moved away from it's native user interface to a web based one. I think I've yet to see any particular case where the web interface gave equal speed and possibilities as what they were moving away from. It was always one or more steps backwards. 

There's no doubt that the web and HTML are great for many things, I just don't agree that it's a better solution than a real GUI where that's an option. It's great for all those situations where a GUI isn't an option though, it would make no sense if I'd have to have a program installed to search on Google or look up an article in Wikipedia. I consider Java to be a compromise between the two. The GUI you can produce in Java is never as good as if it were native, yet it's way better than what a web interface can deliver. It follows from the level of generalization or abstraction if you will. The more general a solution is, the more resources and finesse will have to go since a general solution can only do what the weakest application of that generalization can deliver.

> It also fits well with our "universal" philosophy since it means the settings are accessible from any device instead of just the one computer. We do already have the ability to set some settings by playing fake videos over DLNA which is awesome but that's more of a clever hack than an actual interface.

I completely agree with you about the problem, I'm just not sure it it's the right solution. I've said several times that making the GUI a part of the media server itself is a huge design flaw made when PMS was born - although it was probably never intended to grow as it did. A server is a piece of software that should work without a GUI in my view. You connect the client (with the GUI) to the server from one or more networked devices. If UMS had a separate client, we could make a version for Android for example in addition to the "normal" client that would run on most computer platforms. iOS is not interesting in my view, since Apple forces anyone that want to develop for their platform to buy and use a mac.

> I don't see any reason why web interfaces need to be slow, unreliable or give little feedback. I think if they're done right they can be superior to non-web interfaces and certainly easier to implement IMO.

The lack of feedback is by design as I see it, it comes from HTML and how that's basicly designed from the ground up as a one-way protocol (producing output, not accepting input). PHP, JS and a lot of other addons have come along to try to mend it, but the fundamental lack of support for interactivity will probably never really become invisible. But, I don't know enough about HTML5 and the possibilities that's supposed to bring along, nor do I know enough about what you can do if you use all the band-aids that's created around HTML in an optimal way. What I know is that I'm observing that even the big web based businesses can't get it right (Facebook, Google etc). Web GUI's still aren't as responsive or good today as they were in Windows 95 20 years ago.

> Using HTML within Java is a nice approach as long as it doesn't require too much rework - I'd rather have a really polished web interface than a mediocre web and Java interface. I'm happy for 6.0.0 to be Java 8-only if we would benefit from that.

I don't see how keeping the (albeit mediocre) GUI we have hinders development of the web interface. Any improvements to the web interface is a good thing, but why does it have to go hand in hand with removing the GUI? JavaFX might just be exactly the right compromise though, I haven't looked that much into it. While it's supposed to be some JavaFX in Java 7, it's basicly not usable until Java 8 if I understand things right. Here's a desciption from Oracle:
> JavaFX Applications

> Since the JavaFX library is written as a Java API, JavaFX application code can reference APIs from any Java library. For example, JavaFX applications can use Java API libraries to access native system capabilities and connect to server-based middleware applications.

> The look and feel of JavaFX applications can be customized. Cascading Style Sheets (CSS) separate appearance and style from implementation so that developers can concentrate on coding. Graphic designers can easily customize the appearance and style of the application through the CSS. If you have a web design background, or if you would like to separate the user interface (UI) and the back-end logic, then you can develop the presentation aspects of the UI in the FXML scripting language and use Java code for the application logic. If you prefer to design UIs without writing code, then use JavaFX Scene Builder. As you design the UI, Scene Builder creates FXML markup that can be ported to an Integrated Development Environment (IDE) so that developers can add the business logic.

**Comment by taconaut** [comment]
I had wanted to have a web GUI for quite some time, but stopped thinking about it, as currently it wouldn't be possible to expose plugin configurations (this concerns plugins as well as engines like mencoder). To allow this, the external listener interfaces would have to be changed and thus break existing plugins.
I've recently rewrote the web service plugin (https://github.com/taconaut/UMS-Plugin-WebService) which allows to read/write configuration values through a SOAP web service and have made a POC with a .NET rich client (which hasn't been checked in yet).

**Comment by SubJunk** [comment]
@Nadahar @taconaut I'm not advocating replacing our entire GUI with a web-based one, at least not in 6.0.0, but making it so that the "Shared Folders" section of our Java GUI links to our web interface where we can support more complex actions than we currently can/do.

@Nadahar What are the things you don't think Facebook and Google do that native interfaces do? I don't understand what "responsive and good" means. GitHub seems very responsive and good to me.

**Comment by Nadahar** [comment]
@SubJunk I guess I've become a bit over sensitive about the whole move-to-webinterface issue after being forced to use such solutions when the native clients are dropped and experiencing that everything takes longer to do. To me the difference is so obvious, but it isn't that easy to explain. The best I can think of is comparing playing a game FPS* at 60 FPS** vs 15 FPS** (* First Person Shooter, ** Frames Per Second). You just experience that everything is lagging behind whatever you do, a bit like moving in a thick liquid. That, and the fact that it's often not completely consistent what happens if you type fast, so you have to "wait" for visual confirmation to know that everything registered. And the lack of shortcuts, and the lack ot Tab + Shift Tab navigation, and the lack of right click menu's (without the use of JS that hides the browser's rightclick menu) etc. These are all things that's not that relevant for UMS' GUI, it's not something you have to use that much after all. I guess that it all boils down to that I think that's a negative development that's been going on for many years now and I'm kinda waiting for the world to realize that. 

My point is simply: Make the web interface stuff, but don't remove it from the GUI. You can just make the UI like you want it in the webinterface, and I can try to replicate the functionality in the GUI. If I can't do it, then I agree that we just remove it from the GUI.

**Comment by SubJunk** [comment]
@Nadahar that sounds like a good solution, it will be cool to see it replicated in the GUI and I'll probably learn a bunch about how to implement interfaces in Java from you if you can :)

At the moment my focus is on ironing out the watched media functionality but this will tie in with it, since we will need the ability to "unwatch" videos before that's released.

**Comment by SubJunk** [comment]
This didn't happen, will make a new issue for new direction
