### ISSUE TITLE
why   don't  have  a generic device  dlna 1.5 ?

### ISSUE THREAD

**Issue by anthraxs** [UniversalMediaServer/UniversalMediaServer#727]
no need to  have  a lot of renderers     and no one  good 

 need  only  one    generic   DLNA 1.5    but i can't select  

for  play  audio  and video     at same   time  on capable device 

i  have  pioneer  bdp 150   and can  play  audio and  video 

 but  UMS  select  always  pioneer DMR  and  play   music only 

no  movie

**Comment by Nadahar** [comment]
@anthraxs You can enable or disable renderer profiles in "Select renderers" in the "General Configuration" tab. Disable the Pioneer DMR from there, and see if that helps. If you disable all the profiles, UMS will use "unknown renderer" which is a generic DLNA profile.

Sadly, the DLNA standard is flawed and almost no device complies fully with the standard, so simply following the standard isn't enough. That's why we, and mostly any other DLNA server software out there, have renderer profiles so that we can try to adapt to the renderers deviation from the standard so that it still works.

**Comment by anthraxs** [comment]
no sorry 
 Wild  MEDIA SERVER       have 

 DLNA Device (version 1.5, 16:9, 720x406)  and  i  use   that   for   

PIONEER  BDP 150  and  yamaha BD-S1067

**Comment by Nadahar** [comment]
@anthraxs Sorry, I don't understand what you mean. Can you try to rephrase?

**Comment by anthraxs** [comment]
i can't  find Pioneer DMR  in renderer profiles  to deselect  

  find  only  Pioneer Kuro  and can  play  mp3 only

**Comment by valib** [comment]
@anthraxs try to follow instructions at https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/faq#my-device-is-not-supported-by-ums-how-can-i-create-a-custom-rendererconf-to-make-ums-recognize-my-device
