### ISSUE TITLE
problem with correct ip

### ISSUE THREAD

**Issue by pyraylos** [UniversalMediaServer/UniversalMediaServer#732]
hi. whenever i run a virtualbox on my machine, it creates 2 network interfaces called vboxnet0 and 1. when i close the virtualbox these interfaces stay up and running. i disable them with 'sudo ifconfig vboxnet0 down' and their status is not 'up' anymore. but when i start UMS, it gets ip from these interfaces and not from the actual ethernet as shown on this log: 

18:50:08 INFO Using address /192.168.57.1 found on network interface: name:vboxnet1 (vboxnet1)
18:50:08 INFO Created socket: /192.168.57.1:5001

how can i make UMS get ip from ethernet(eth0) and not from virtualbox interfaces?

**Comment by Nadahar** [comment]
@pyraylos You can force UMS to use a certain network interface in the ```General configuration``` tab under ```Network settings```. You'll have to uncheck ```Hide advanced options``` on the same tab to be able to see this.

**Comment by Oxalin** [comment]
Just out of curiosity: what do you get when you try "ifconfig vboxnet0" (or vboxnet1) after it was brought down? (you could also try with the "ip" command. "ip a s" will list the interfaces and their details).

Also, are you launching UMS while the virtualbox is running or after it was closed and you brought down the two virtual network interfaces?

**Comment by pyraylos** [comment]
@Nadahar thanks for the solution.
@Oxalin i start ums after i close vbox, and with the above command i get this:
vboxnet0: flags=8842<BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:00 
vboxnet1: flags=8842<BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:01 
	inet 192.168.57.1 netmask 0xffffff00 broadcast 192.168.57.255

**Comment by Nadahar** [comment]
@pyraylos I take it that solved it then?

**Comment by pyraylos** [comment]
yes and thank you.

**Comment by Nadahar** [comment]
Good, closing.

**Comment by Oxalin** [comment]
@pyraylos : thank you for the details. Eventhough your issue has been closed, you may be interested in the following: as you can see, there is still an ip address associated to your vboxnet1 network interface. As such, UMS tries to use it since it thinks it is still valid.

I don't have ifconfig available on my system (ArchLinux) since it was superseded by the "ip" tool (available in the iproute2 package). With the "ip" command, you could "flush" any ip address associated to a given network interface (http://superuser.com/questions/153559/how-can-i-clear-the-ip-address-of-ethernet-interface-without-cycling-the-interfa). This should prevent UMS to select it as an active | up network interface. That is, if you don't want to specify a network interface in the UMS config as @Nadahar suggested earlier.
