### ISSUE TITLE
Playback issues with Miracast Wifi dongle

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#742]
@UniversalMediaServer/developers @SubJunk 
I tried to help @prescott66 getting playback to work on a [Miracast Wifi dongle] (http://www.ebay.com/itm/331567898036), but we hit multiple issues for which I have no idea how to fix.

First we tried to stream. The Miracast can't find UMS, so playback has to be started via bump. It does start playback, but the player panel doesn't understand it and quickly grays out anything but the play button (as if playback didn't start) so there's no way to stop or fast forward etc. In addition UMS doesn't seem to properly close player control when shutting down, resulting in the Miracast freezing. 

The log file for this session also contains some interesting errors related to renderer control:
```logtalk
DEBUG 2015-11-25 19:29:38.134 [UPNP-LOLLIPOP-1C3A18-DMR] Action failed: Error: Error reading SOAP response message. Can't transform message payload: org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 1460; An invalid XML character (Unicode: 0x2) was found in the element content of the document. (HTTP response was: 500 Internal Server Error)
```
```logtalk
INFO  2015-11-25 19:32:42.032 [cling-18] [Fatal Error] :6:3: The element type "PresetNameList" must be terminated by the matching end-tag "</PresetNameList>".
DEBUG 2015-11-25 19:32:42.032 [cling-18] Error parsing xml: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "PresetNameList" must be terminated by the matching end-tag "</PresetNameList>".
```
I'm not sure how to interpret it, it might be the Miracast that's violating the spec and thus crippeling the player control.

The full log is attached here: [streaming.debug.log.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/44237/streaming.debug.log.txt)

We then tried to transcode, which gave completely different errors. I don't understand what's happening there, but it says that it will use ```FFmpeg``` but when the transcoding is started ```MEncoder``` is used, and it throws a lot of errors. Nothing is actually played at the renderer, and when the renderer disconnects the log is flooded with errors from cling like this:
```logtalk
DEBUG 2015-11-25 19:52:18.258 [cling-190] Subscription cancelled: ConnectionManager on uuid:75307c32-02ec-dba0-ffff-ffffe14da80f: RENEWAL_FAILED
DEBUG 2015-11-25 19:52:18.315 [cling-190] Subscription cancelled: RenderingControl on uuid:75307c32-02ec-dba0-ffff-ffffe14da80f: RENEWAL_FAILED
DEBUG 2015-11-25 19:52:18.318 [cling-190] Subscription cancelled: AVTransport on uuid:75307c32-02ec-dba0-ffff-ffffe14da80f: RENEWAL_FAILED
```

This log is attached here: [transcoding.debug.log.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/44254/transcoding.debug.log.txt)

I hope some of you guys can figure out some of these issues, and in particular @skeptical on the uPnP stuff.

edit: I originally thought this was a Roku, but looking at it now it's likely that this is some chinese cheap thing that's likely to violate all standards. I still think there are things here that UMS could handle more gracefully though.

**Comment by Oxalin** [comment]
@Nadahar, about the use of mencoder over ffmpeg, could this be a clue?
TRACE 2015-11-25 19:51:10.102 [Request Handler] Switching from FFmpeg to MEncoder to transcode subtitles because the user setting is enabled.

**Comment by Nadahar** [comment]
@Oxalin Yes, I forgot to update the issue about that, but I think I figured out that. It's due to the "secret"/undocumented option ```ffmpeg_mencoder_problematic_subtitles``` which defaults to ```true```. Turning that off so that FFmpeg was used didn't make it work though.

**Comment by valib** [comment]
@Oxalin it is not documented option because it can be normally changed in the GUI at the FFmpeg config page. The option is "Defer to MEncoder when transcoding problematic subtitles".

**Comment by skeptical** [comment]
@Nadahar for malformed xml errors try [switching the cling xml processor ](http://4thline.org/projects/cling/core/manual/cling-core-manual.html#section.SwitchingXMLDescriptorBinders) (see the ```UpnpServiceImpl``` override example at the end of section 6.4, which can be implemented at [UPNPControl.java#L322](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/network/UPNPControl.java#L322)), but I don't think this itself is what causes the playback failure.

I don't know the full history here, but have you tried different files, i.e. without subtitles to see if playback works at all? Does it work with other servers?

And regarding "UMS doesn't seem to properly close player control", from the logs it seems the connection is broken (presumably closed/abandoned/frozen by the LOLLIPOP), in which case the ums controller would revert to the "not playing" state with the mostly grayed out buttons. Later the subscription renewals fail, I guess because the LOLLIPOP is no longer accessible.  It's not due to anything at our end afaict (except maybe the LOLLIPOP is bricked due to not being able to process or recover from the media stream we sent).  Or do you mean that the ums controller itself is somehow frozen?

**Comment by Nadahar** [comment]
@skeptical It's separate issues. I don't think this is in the logs, but every time UMS is closed/quit, the LOLLIPOP device freezed. I'm just presuming that it's some handoff problem, but as I said in my edit: Any bets are off for compatibility for this device.

**Comment by Nadahar** [comment]
I'm closing this as a working configuration is found (#748), and the bugs in uPnP are probably the renderer's fault.

**Comment by ExSport** [comment]
@Nadahar @valib @skeptical @SubJunk 
Making __ffmpeg_mencoder_problematic_subtitles=FALSE__ will lead to unplayable file for the first time as UMS have to export subs before file is played. On big MKV files with more than 5GB it takes minutes so every renderer will give up and disconnects. Due to this FFmpeg flaw MEncoder is used as it supports playing embeded subs immediately without waiting x minutes for subs extraction.
Not sure if latest FFmpeg with internal subs support as I read here in some posts and patches does things better (as MEncoder does) but if yes, this option should be disabled by default again :-)

**Comment by Nadahar** [comment]
@ExSport The problem here was that MEncoder wouldn't work at all (for some unknown reason).

**Comment by valib** [comment]
@ExSport I am afraid that FFmpeg only add the ```Force_style``` option but internally the ```libass``` library works like before. Unfortunately I don't have any big MKV video to test it.
