### ISSUE TITLE
Java GUI not displaying in HiDPI on Retina displays

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#764]
The text is pixelated on Retina displays so we should figure out how to make it display normally.
There are some articles about it, here's one https://bulenkov.com/2013/06/23/retina-support-in-oracle-jdk-1-7/

**Comment by Nadahar** [comment]
@SubJunk It's very hard to test for Retina as none of the developers have a Mac (as far as I know). Furthermore, I'd say that those problems are the OS' concern. The article you link to talks about intricate detection of Retina and then custom painting to avoid that the OS will scale things up. In the end, it's the OS that does the scaling, and it's the OS' job to do it properly as I see it. I can't really see that we'd go around writing custom paint routines for all the components in our GUI so that the fonts on some Mac's would render nicely.

I don't know how the JVM and OS X interacts, but I would think that font rendering was delegated to the OS in any case. Images on the other hand would get enlarged and pixelated, but for a proper solution to this Java has to change so that we can supply multiple resolution images where they are used. Alternatively that we supply a higher resolution one, and Java scales it down. In any case, I can't really see what we can do about this within reasonable effort limits.

**Comment by SubJunk** [comment]
@Nadahar I got a retina mac for work, so I can test and work on this

**Comment by Nadahar** [comment]
@SubJunk Ok, but I don't think there's much you can do about the font rendering. Maybe there's some small setting somewhere, but custom painting all components....

Java is supposed to have Retina support since 7u40, so the Java version matters. You should check the Java version in use on the computer with bad rendering.

**Comment by SubJunk** [comment]
@Nadahar it's using the latest Java 8 release, fresh install yesterday on a brand new mac

**Comment by Nadahar** [comment]
@SubJunk Ok, I know to little about how the font rendering is handled, you will have to see what you can manage, but I think this is "out of our hands" in that details that's likely going wrong is between the JVM and the OS.

Since you're here, there's a [case on the forum] (http://universalmediaserver.com/forum/viewtopic.php?f=9&t=5790) that I think you should look at. UMS fails to parse some MP4/H.265 files for reasons unclear to me.

**Comment by valib** [comment]
@Nadahar  the issue http://universalmediaserver.com/forum/viewtopic.php?f=9&t=5790 fixed in ef4e8a4

**Comment by SubJunk** [comment]
I've found a fix for this so I'll commit it soon

**Comment by Nadahar** [comment]
@SubJunk Great, excited to see what the problem was.

**Comment by SubJunk** [comment]
Well the fix is to add the following to Info.plist:

		<key>NSHighResolutionCapable</key>
		<string>True</string>

but I'm not sure if the tool we are using for bundling is capable of that, and I'm not sure if the other bundler options support the advanced commands we're using with our current bundler. I might just write a script that appends that key to the file.

**Comment by SubJunk** [comment]
Fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/f00e1031dde889a9fbcd8a5662e2f9a87e16d838

**Comment by SubJunk** [comment]
Actually I'll keep this open because even though it's now fixed for text, it's still not for images

**Comment by Optimusprimeums** [comment]
@SubJunk I've created a new project for our Appbundler here https://github.com/Optimusprimeums/Appbundler-UMS Maybe we can mod it to fix this particular issue and I'll rebuild it

**Comment by SubJunk** [comment]
The version I added is from https://bitbucket.org/infinitekind/appbundler
Is there a reason we can't just use that instead of having our own one?

**Comment by Optimusprimeums** [comment]
Actually it was forked from there but there is no reason we can't use it natively. When I first started it they only supported bundling the Java with the releases so thats why I used my modded one. Mines from back in 2013 so use the latest :)

**Comment by SubJunk** [comment]
Oh cool :)

**Comment by SubJunk** [comment]
Fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/fa7ecee1d4fd363ca66467a4c60fbba77305e3ce

**Comment by Nadahar** [comment]
@SubJunk What about renderer images? Don't they need double sizes as well?

**Comment by SubJunk** [comment]
@Nadahar yeah, we should probably add them. I don't think it's urgent but it would be good. Maybe I'll add some of the most popular ones
