### ISSUE TITLE
Don't discourage use of Linux distro packages

### ISSUE THREAD

**Issue by mcepl** [UniversalMediaServer/UniversalMediaServer#765]
> Sometimes distributors do not set important compiler options, e.g. scaling support for FFmpeg. So I recommend you to compile it from source.

This is crazy. We shouldn't discourage use of distro packages. If there are some buggy packages, then file a tickets, shame them, but the goal should be to have proper and correct packages, not "normals" being forced to build a complicated Java app on their own.

**Comment by Nadahar** [comment]
@mcepl I don't know you found that sentence, is it from som readme/install instruction, Wiki or forum? We distribute FFmpeg in the tarball, so I can't see why there would be a need to build FFmpeg.

That said, FFmpeg is not a Java application, and is probably straight forward to build.

**Comment by mcepl** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Installation

**Comment by Nadahar** [comment]
@SubJunk @Optimusprimeums 
Is [this documentation] (https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Installation#installation-and-start-of-ums-on-linux) correct? Why would there be a need to build or install FFmpeg when we distribute it in our tarball?

**Comment by SubJunk** [comment]
The Wiki isn't correct in that case

**Comment by SubJunk** [comment]
I've just updated it a bit. I think that's my first contribution to the Wiki and I haven't looked through it at all. I've been dissatisfied with this project's documentation for a long time and haven't really done anything to improve it, although I have made improvements to the documentation in DefaultRenderer.conf and UMS.conf

**Comment by Nadahar** [comment]
@SubJunk Documentation is always troublesome, nobody (or very few) really likes to write documentation. I believe there should always be a "core documentation" that's part of the source tree and that's updated whenever features that are or should be documented are changed, introduced or removed. Wiki's and forums add to that core documentation, but they should in the end be user contributed in my mind. The developers should supply the "core" documentation that others can't change.

About the change you made, this is still there:
> You can either use packages from your Linux distrubution or compile the tools by yourself. Sometimes distributors do not set important compiler options, e.g. scaling support for FFmpeg. So I recommend you to compile it from source.

Is there any need to install FFmpeg on Linux at all? Doesn't UMS use the version bundled in the tarball?

Also, when installing on Linux I've found I'd have to install MediaInfo myself. On the distros I've used it's been available through packages. I think there's something called zlib that's needed for MediaInfo to work, but that's been a dependency of MediaInfo where I've tried, even though I did find some forum post or something mentioning that it needed to be installed as well. It's probably if no packages are available and you need to compile MediaInfo yourself.

Maybe @skeptical can shed some light on the Linux installation requirements, I'm sure he's more up to date there than I am.

**Comment by mcepl** [comment]
``zlib`` is one of the most basic libraries on any Linux distro, so I guess every Linux has to have it (it's for gzip compression).

**Comment by Nadahar** [comment]
My memory played tricks on me. MediaInfo depends on ```libzen``` - not ```zlib```. I've had to install it manually on at list one distro, but I don't remember which. For the most, it's installed by the package manager when installing ```mediainfo```.

**Comment by mcepl** [comment]
Yeah, that shouldn't be that much problem either https://admin.fedoraproject.org/pkgdb/package/rpms/libzen/ and https://packages.debian.org/search?keywords=libzen seem to have it.

**Comment by SubJunk** [comment]
@Nadahar I've updated the instructions a bit more

**Comment by Sami32** [comment]
@mcepl @Nadahar Could this issue be closed ?
Since updades already done by @SubJunk and very recently by myself on _install.txt_ following your recommandations.

**Comment by mcepl** [comment]
Yeah, I would actually actively encouraged use of the distro packages, but not saying anything is I guess the best I can hope for. +1 for closing.

**Comment by SubJunk** [comment]
In my opinion Linux is awesome for some reasons, mostly philosophical - but unfortunately is a nightmare to develop *for*. It's much easier to give a consistent and stable experience on more standardized systems like OS X and Windows, where there aren't a billion different combinations of libraries that can cause our program to work differently than we intend. I've spent so many hours/weeks/months troubleshooting Linux issues just to find there's some shared library conflict, or weird distro, or the user has customized something unexpected that broke things.
Right now I would actively encourage the use of OS X or Windows over Linux. /rant

**Comment by mcepl** [comment]
Well, a good rant, but a bit misdirected. The point is that you are not supposed to do packaging and care about packaging on Linux. Somebody else should do it, and you should redirect the bug reports to her.

**Comment by Nadahar** [comment]
@mcepl That's not what's happening though. Nobody is doing the packaging, and the users submit bug reports that's caused by all kind of issues.

I really love Linux as a concept and use it for specialized tasks. But, as a general platform it's just too much trouble for me. Linux wants to and hopefully will make it as a general purpose desktop platform (OS X is already stripped for and freedom and Windows is going the same direction with huge steps for each new version). But, before that can happen I think there has to be done some serious standardization efforts, at the very least among the big distros. The package managers in particular is a big problem, it should be possible to find one commmon package manager that would work across the lot, with standardized configuration for startup scripts etc.

Personally I can't wait for this to happen, but I'm afraid there are too many "huge ego's" and pride among the different distros that they will ever agree on one way of doing things.

**Comment by mcepl** [comment]
Well, it unfortunately goes both ways. Because UMS didn't work for me, I in fact, ended up using ``minidlna``. It is far from perfect, but at least I was able to tame it to submission. Which means that there is even less chance, I would ever package it for Fedora/RHEL.

**Comment by Nadahar** [comment]
@mcepl This issue is a partial overlap of #730. As you can see there, there are ways to make UMS use what libs you want it to. The problem is that it's too hard to find the documentation for it for many people to figure it out - but it shouldn't keep anyone that wanted to package it for a Linux distro from doing just that. To my knowledge though, there hasn't exactly been a lot of people that want to maintain a package of UMS. I think PMS (the predecessor) was maintained for Debian/Ubuntu for a short while.

I'm sure anyone wanting to actually do this for a major distro would get a significant amount of goodwill when asking for tweaks to make packaging more managable, as long as it wasn't making UMS less general/less suitable to other distros and OS'es.

**Comment by mcepl** [comment]
Well, my problem is also [ffmpeg](https://admin.fedoraproject.org/pkgdb/packages/*ffmpeg*/) … I was told by many developers that it is a way more comfortable for use than GStreamer, but the advantage for the latter (and for me on Fedora/RHEL) is that ffmpeg is still kept together (or nobody did the split for Fedora), so it is completely unacceptable in Fedora. GSTreamer can be separated into free core, and patents-infested etc. plugins from the third party repos.

ANyway, also curious ... what is the meaning of your avatar. Pro-Christian or anti-Christian? ;)

**Comment by Nadahar** [comment]
Anti-religion is the intention, but since I don't know of any good general symbols for religion I chose christianity. I consider christianity to be the biggest threat anyway, since very much of the world's power is held by by christians. Since I live in a "christian country" it's also what's causing most misery to the society I live in. The ribbon (black and red) is supposed to be the atheist ribban, and the ribbon together with the circle are supposed to form at forbidden sign.

**Comment by Sami32** [comment]
@Nadahar Since everyone have his own god's conception, i will call myself more an agnostic than atheist.
That said, it's not limited to christian though, since religion was one of the first political power, i think that all monotheist religion have the hands full of blood, let's call brothers of blood. Not that bouddhism, indhuism and others don't have but much less.
What about politicians ? :-D Whatever country in which we live...Human misery come from our own selfishness, lust for power. And some of them know how to use that to their own profit. The interest of a minority at the expense of a majority. It was my evening thoughts ;-)

**Comment by Nadahar** [comment]
@Sami32 I agree, I'm against all mix of religion and power - and thus organized religion, since the purpose of organizing it ultimately is to have power. People can believe whatever they want for me, but I draw the line at wanting to influence how others should live based on their own fantasies. I don't know if it's because they are monotheistic, but I agree that the Abrahamic religions are particularly "evil". Their common roots are basicly just rotten, filled with hate, terror and inhumanity. If I was forced to pick one of the big religions, I'd go with Buddhism as it actually have some good ideas in it. To me it's still a fairytale though.

**Comment by SubJunk** [comment]
Cool to see this kind of discussion here :)

**Comment by Sami32** [comment]
@Nadahar I agree that all humans could keep their liberty of thinking, believing...what they want without judgments or discriminations.
I confess that i'm far to know about all the different religions Sikhism, Jainism..., that did came after the different spirit believes where there also some "master" controlled the people in their own interest, Buddhism, that came from indhuism, is certainly the less worst to me as well.

The political powers did not really replace them, more like a deal to me; also if the France is the more atheist country (50%) the religion lobby stay important in politic, we can sadly saw that when we make laws for the marriage of homosexual people or from child's adoption from surrogate mother, abortion...or when some movie about the Christ with Mel Gibson come to the cinema.

Concerning Abrahamic religion i would say it's a big family story.
Like you told, the golden age of humanity is not for now, but i keep hope that's will not stay a fairytale.
I believe that the love for their children and self-preservation will make humanity progress on that.
