### ISSUE TITLE
ehhh nvm

### ISSUE THREAD

**Issue by mikeparadinas** [UniversalMediaServer/UniversalMediaServer#766]
**read  Nadahar last message, is probably what happened**

_I opened the Resource Monitor, and noticed universal media server, through javaw.exe
was reading all my firefox extention data. why is this?_

**Comment by kintaro1981** [comment]
any reply about this?

**Comment by Nadahar** [comment]
I have no idea. as far as I know UMS doesn't. I don't even know where to stop looking for this, do you use Firefox to browse UMS? If not, UMS should have nothing to do with Firefox. 

How do you know that UMS is doing this, "javaw.exe" can be any Java program. Are you sure that UMS is the only Java program running? Will quitting UMS make "the reading stop"?

To get an overview over all running Java processes, you can use [VisualVM](https://visualvm.github.io/). When you start it, it will list any application including itself.

The only thing I can think of that is slightly related is that I know that UMS uses cookies when you use the web interface. However, since that browser could be on a remote computer or other unit, it would make no sense for UMS to read any Firefox files itself - it will query Firefox for the cookie and get it that way.

**Comment by kintaro1981** [comment]
@Nadahar I think we need to wait some words from @mikeparadinas because I didn't tried and I asked to prevent security issue before using... UMS it's opensource so I don't think that it can do something malicious without people notice the problem on the source code.

**Comment by Nadahar** [comment]
@kintaro1981 I doubt we will get a reply. @mikeparadinas Wrote this back in 2015, with no follow-up or further explanation. I'm very sure that this has been a case of confusing UMS with the actions of another Java application - you can't really tell them apart in the OS tools as they all run in the context of the JVM.

If this were the case, I'd think more people would have noticed as well.
