### ISSUE TITLE
Apps built on VLC for iOS sometimes don't work

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#775]
Sometimes we send the following to VLC-based iOS apps (which is most of the media player apps for iOS) when they send a browse request, and other times we send the actual numbers and it works properly:

```
   <NumberReturned>0</NumberReturned>
   <TotalMatches>0</TotalMatches>
   <UpdateID>1</UpdateID>
```

I'm looking into it

**Comment by SubJunk** [comment]
It appears to be a regression in 4.1.0. 4.0.3 does not seem to have the issue.

**Comment by SubJunk** [comment]
@skeptical my testing points to 79ea06c as the cause of this bug, any ideas?

**Comment by skeptical** [comment]
@SubJunk the diff essentially disables loading priority, i.e. potentially causes confs with lower priority to be higher in the list than higher priority counterparts.  Offhand I would say this indicates that the problem is at the conf level, i.e. some VLC-based ios apps are using different renderer confs than others, so I would start by comparing logs for a "good" app with a "bad" app to see if they're being recognized the same way and assigned to the same conf (could be different headers triggering different conf selection).

**Comment by SubJunk** [comment]
@skeptical I should've said, it's using the same renderer config before and after the diff. I tested with the VLC app itself.

**Comment by skeptical** [comment]
@SubJunk logs are easier to read than breadcrumbs or tea-leaves  :-).  The diff is only affecting the order of confs, so it's hard to see how it could be responsible if you end up with the same conf either way.

**Comment by SubJunk** [comment]
@skeptical after more testing I don't think that commit had anything to do with it. We may need to add more logging to find the cause but maybe you'll see something I didn't see though so here's a log file. This was created using a clean install of the latest master and I deleted all renderer configs except for VLC for iOS.
On line 796 is when I tried to open the "Test" folder via the VLC app.

http://www.spirton.com/uploads/UMS/logs/ums_dbg-vlc.zip

**Comment by skeptical** [comment]
@SubJunk this looks similar to my logs. What happens if you try ```CreateDLNATreeFaster=false```?

**Comment by SubJunk** [comment]
@skeptical that seems to fix it with the latest master, but I've tried it before and it didn't, maybe we have fixed a relevant bug along the way... I'll commit that change and keep this open in case that's not it. It's inconsistent so hard to pin down

**Comment by SubJunk** [comment]
This seems to be fixed now :)
