### ISSUE TITLE
Tooltip margin

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#779]
Some tooltips seem to have double margins/paddings now. For example, on the Navigation/Share Settings tab, hover over the buttons down the bottom and there's a huge padding, but it's different on the checkboxes

**Comment by Nadahar** [comment]
@SubJunk I tried reverting the tooltip border change I merged in, but it makes no difference. The tooltip rendering is horribly bugged, and should be looked at.

I suspect it could have to do with changes I did in #679 related to the ```LanguageSelection``` dialog, but I find it strange since this happens without the dialog ever being launched. I'll look closer at any changes there.

The extremely hopeless thing is that all the HTML enabled Swing components share one instance of the CSS. So, if any component make any changes to the CSS formatting, it has implications for everything else. I suspect this must be what's going on here.

**Comment by Nadahar** [comment]
What's apparant is that it's our "custom" tooltips that have the huge margin, where the standard tooltip is used the margin is normal, and the shadow is drawn.

I've seen this before, the bug isn't new I think, but it has been relatively rare. For some reason it seems to happen consistantly now.

**Comment by Nadahar** [comment]
I've confirmed that it is the stylesheet that's changed. Replacing it with an empty stylesheet removes ALL padding... :(

**Comment by SubJunk** [comment]
@Nadahar which stylesheet?

**Comment by Nadahar** [comment]
The shared stylesheet between all components that use ```HTMLEditorKit```, like ```JTextPane``` and ```JEditorPane```. I have fixed the issue locally here, but I'm considering how to best implement the changes.

**Comment by Nadahar** [comment]
@SubJunk Have you tested this?

**Comment by SubJunk** [comment]
Fixed in #780
