### ISSUE TITLE
No Coverarts on newer Onkyo Receivers (AVR after TX-NRX1X)

### ISSUE THREAD

**Issue by patrickbonner** [UniversalMediaServer/UniversalMediaServer#783]
UMS can´t show Coverarts on onkyo Receivers (like TX-NR929, TX-NR3030 and later).
Coverarts are included in (MP3 and FLAC) Files, and WMP works fine with that, but 
UMS not... sorry.

**Comment by Nadahar** [comment]
This issue is based on [this thread] (http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=5879).

I have an Onkyo TX-NR807 which has the same behaviour (I didn't even know it could show coverart since it never has with UMS), but unfortunately the DLNA card in my Onkyo has gotten a disease lately and keeps freezing and rebooting so testing is impossible. It took me more than 30 minutes to get it to show coverart from a WMP server once. If anyone knows how to fix it, great, but I can't look at it until I've fixed it. I'm assuming it's some bad caps (as are almost "standard" on Onkyos after some years), so I have to figure out what types, order and soldier in new ones before I can troubleshoot this.

**Comment by patrickbonner** [comment]
Hi Nadahar.

Any News?

**Comment by Sami32** [comment]
@Nadahar Did you finally repare your Onkyo ?
In fact, i'm more interested by your Onkyo Wireshark session :wink:

**Comment by Nadahar** [comment]
@Sami32 Yeah, it's fixed now. The "HDMI board" (with it's own tiny processor) was toast, in fact the was an extended warranty covering this - but it took a while to figure it all out.

I guess I can do some wiresharking some day, but if I forget it do remind me 😉

**Comment by Nadahar** [comment]
This is fixed by a4f79f0482d9e8eb1a72deb3d6129da7db01abd0 - whenever that is merged.

**Comment by Sami32** [comment]
Well done :+1:  i guess that you're happy.

That's said i'll never thought about that, as you told me that we don't need to care about XML parsing, as specified in the standard, as it shouldn't matter any order !
So, it seem that standard is not universal understood, and that I'm not the only one LOL

**Comment by Nadahar** [comment]
@Sami32 I didn't dream of it myself, I still consider it to be a bug in the Onkyo code. But, I guess it can't hurt to have them arranged that way, for any renderer, since Onkyo passed DLNA compliance tests with that parsing it means that any other renderers can have the same buggy parsing without failing.

**Comment by Sami32** [comment]
From what i read, as long as they paid for it, they receive testing tools and zoooo the certification.

LG BP550 have passed it as well, and you saw the result. I don't thint that the users will be able to play ATRAC3 with `audio/sonyoma`...

**Comment by patrickbonner** [comment]
ok. the new order is onkyo´s own DLNA Specification.

Nadahar- i think the issue can be closed!

Thanks

**Comment by Nadahar** [comment]
@patrickbonner It's not merged yet (the "fix" isn't in the "master" branch and a part of the next UMS). I'd prefer to leave the issue open until it's merged - so we won't forget it 😮
