### ISSUE TITLE
Not all languages are listed

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#794]
@Nadahar not all languages are listed in selection. Reported in http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=5896 I can confirm that I also don't see all of them.

**Comment by Nadahar** [comment]
It's supposed to be like that, I've also informed about that in #679. There's a minimum threshold for translation coverage that must be met for languages to show up. It's currently at mere 20%, but I think we should raise it to say 50% in the future. The idea is that languages with a very low translation coverage is more annoying than useful.

**Comment by valib** [comment]
@Nadahar something is wrong e.g. the Hungarian language is translated at 43% but is missing.

**Comment by Nadahar** [comment]
@valib We've gotten these translations after release (we've actually gotten quite a few, it seems like the information in the language selection dialog has had a great effect). At the time of release, [Hungarian was at 0 %] (https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/resources/languages.properties#L134). The next release will display Hungarian.

**Comment by valib** [comment]
@Nadahar nice. I see that you also inform user about it. Great work. :+1:

**Comment by Nadahar** [comment]
Actually, we've gotten so many translations that we should consider 5.5.1 soon simply to get all the new translations:

* Japanese: 165 new translations
* Brazilian Portuguese: 555 new translations
* Portuguese: 215
* German: 85 new translations
* Swedish: 3
* Hungarian: 456
* Italian: 173
* Danish: 28
* Dutch 65

...and the numbers keep changing all the time.

**Comment by skeptical** [comment]
> There's a minimum threshold for translation coverage that must be met for languages to show up. It's currently at mere 20%, but I think we should raise it to say 50% in the future. The idea is that languages with a very low translation coverage is more annoying than useful.

@Nadahar re our previous discussion, tooltips are skewing things too much.  For coverage threshold to be meaningful imo we should either

* measure by item (not word or phrase)
* or find a way to disregard/discount tooltips.

I just did a rough check and 14% of the items (very overlong tooltips) contain 50% of the words. A translator who skips all tooltips but translates everything else would probably only score in the thirties percentage-wise right now, but the translation would be complete enough for inclusion by any common-sense standard.

There's also the separate philosophical question of "when is a tooltip too long?" which is somewhat subjective, but I would say in general it should be closer to a hint then a  dissertation.

**Comment by Nadahar** [comment]
@skeptical I disagree about the tooltips - even though they are called tooltips, they are used as "help text" in UMS. I'm not saying that all of them are good, but I think that's a fair use of "tooltips".

So what you're actually saying as I see it is that translating the help texts doesn't matter much. If you already know what things do, I agree that they are superfluous, but help texts are generally not written for those people.

But, as I said last time, my intention was to use the number of translated strings, not words - and I'm pretty sure I checked it as well. All the statistics in ```languages.properties``` is available to UMS, so changing it is easy.

The only reason I haven't done it, is because I noticed that crowdin also uses words when they show the "translation percentage" for each language. I think using different "numbers" than what's on the crowdin page could introduce unnecessary confusion and I see my self having to explain that over and over again.

I see two ways to solve it without "breaking" with crowdins measurement: 
1) Use a very low threshold, like now.
2) Make the thresholds work with the "string percentage" while the reported number keeps the "word percentage".

All of this is easily adjustable, so it's not the amount of work that's the problem, it's simply figuring out what's the best approach.

**Comment by skeptical** [comment]
@Nadahar fair enough, I guess #2 is probably better. And I never said anything remotely implying "translating the help texts doesn't matter much", just maybe "a translation without help texts passes the threshold of usefulness".

**Comment by Nadahar** [comment]
> "a translation without help texts passes the threshold of usefulness"

@skeptical I completely agree, I wasn't thinking of raising the threshold without discussing this. The reason I set it at 20% was simply that any higher would exclude too many of the current languages, so excluding languages without tooltips has never been on my radar.

**Comment by skeptical** [comment]
> any higher would exclude too many of the current languages

Full circle: primarily because newer wordy tooltips :-)

**Comment by Nadahar** [comment]
Take a look at any of the ["old" languages in crowdin] (https://crowdin.com/translate/universalmediaserver/1/enus-ru), filter out "untranslated" and you will see that it's much more than tooltips missing. On top of that (which the statistics doesn't show), a lot of the existing "old" translations are translations for strings that have since changed its english meaning. I noticed that when I translated Norwegian, so few of the existing strings actually matched their English counterparts that I opted to start from scratch. My guess is that the same is true for many of the other languages.

**Comment by skeptical** [comment]
I don't mean to exclude other reasons, but just pointing out that the vast majority of the words are in a small minority of items, which skews the picture.  Btw to me item='one line in ```messages.properties```', possibly crowdin means this by 'phrase' as opposed to the common meaning (a coherent sentence or part thereof)?

**Comment by Nadahar** [comment]
Yes, your item is the same as a crowdin phrase.
