### ISSUE TITLE
Signing OS X program

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#796]
Has anyone had experience with signing a program on OS X? At the moment users have to go into the system preferences and disable a setting to install us. I know it costs money, I think $300, but I can possibly pay it.

**Comment by Nadahar** [comment]
I don't know anything about signing OS X in particular, but as with most such signing programs it's really just a tax by whoever enforces it. I doubt it's very complicated to do the actual signing once you have the bought the certificate, but I would think hard about the principle of paying Apple to provide free software to their platform.

My guess is that anyone with a little bit going in their top already has disabled this setting - the problem is when Apple some time in the future remove the option to disable it. But, that won't be a problem only for us.

We could add a special "Donate" button for this in the OS X version to see if the users think it's worth it. My bet is you'd have to pay some kind of a "renewal fee" to keep this certificate as well. Unless the users themselves think it's worth paying Apple for this, I'd settle for a description in the readme (or whatever way we have to reach the users during install) where to find this option.

**Comment by SubJunk** [comment]
@Nadahar it could be worth doing the self-created certificate and I can test how that works by re-enabling the security setting on my work mac. I think maybe PMS was signed with someone's personal developer code but I'm not sure, I'll check that soon and if so, see how it was done.

**Comment by taconaut** [comment]
To install on OS X you don't have to change any security settings if you launch the installer with right click open instead of double clicking it. IMO it's a pretty stupid OS X feature.

**Comment by Optimusprimeums** [comment]
@SubJunk  from when I looked into this the last time, you only needed a developer account. It could have changed since i last investigated it but it was around $100us to join the apple developer program so you can sign your apps

**Comment by SubJunk** [comment]
@taconaut oh that is weird

@Optimusprimeums looks like $149 to me, if that's all it takes I can do it, I think it would benefit the project

**Comment by Optimusprimeums** [comment]
@SubJunk sorry mate been away, but i think it would be good :) but i'll double check that we can sign them

**Comment by Optimusprimeums** [comment]
@SubJunk here's a link https://developer.apple.com/library/mac/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html

**Comment by SubJunk** [comment]
Closing this issue because it is a duplicate (even though this came first, the newer one has more conversation in it) of https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1247
