### ISSUE TITLE
Many unnecessary requests to Open Subtitles

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#844]
It seems like the first part of InfoDb.backgroundAdd() is failing; get(f) is returning null even for files that are in the InfoDB. That causes lots of lookups for me every time a folder is browsed.

Since you wrote the code, any ideas @SharkHunter ?

**Comment by SharkHunter** [comment]
After taking a hard (grumpy) stare at the code there is an obvious culprit at InfoDb line 35.
If you don't find anything at OpenSubs you'll still add the file with "null" which will make get return null, even if the filename is in the db.
What should be there is a special "null marker" which isn't null (since that means not in db) but a special version of the db object meaning "file is here but we got no data for it".

**Comment by SharkHunter** [comment]
After some thinking I have a solution. I'll add it (if that is the problem) and you can test. I'll add it tonight (CET)

**Comment by SubJunk** [comment]
@SharkHunter nice find, thanks for looking into it!

**Comment by SharkHunter** [comment]
@SubJunk - it should (tm) probably work if you restart. When the system reads in the data from file it will create an object (which will contain a bunch of empty strings just), which it doesn't when you add it from the system. Will see how I solve it....

**Comment by SharkHunter** [comment]
@SubJunk - pls tset this one https://github.com/UniversalMediaServer/UniversalMediaServer/pull/846

**Comment by SubJunk** [comment]
Fixed in #846
