### ISSUE TITLE
tsmuxer_path is not honored

### ISSUE THREAD

**Issue by set135** [UniversalMediaServer/UniversalMediaServer#873]
With some videos, I noticed terrible distortion (like digital melting) when using
tsMuxeR to render. Transcoding them worked fine. Then I noticed that UMS is always using ~/ums/linux/tsMuxeR-new instead of the one I specified in the config file. I removed tsMuxeR-new and made that a link to my newer system version of tsMuxeR (v2.6.11) and muxing worked again.
The program obviously reads the variable, because it emits this debug during startup:
DEBUG 2016-04-05 20:49:20.729 [main] Reading tsmuxer_path: "/opt/bin/tsMuxeR" (default: "linux/tsMuxeR")
Here it both ignores my setting '/opt/bin/tsMuxeR' and lies about the default;)
Obviously this is on Linux.

**Comment by SubJunk** [comment]
I just tested and it works for me. Please attach a debug zip in trace mode as per https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/CONTRIBUTING.md

**Comment by Sami32** [comment]
@set135 Did the latest UMS version solved this issue ? If not, please post your full log as told.
@SubJunk Could this issue be closed ?

**Comment by set135** [comment]
Sorry I lost track of this. Running version 6.4.0, with the same issue; that
it ignores my tsmuxer_path setting and always runs ~/ums/linux/tsMuxer-new.
Attaching logs requested.
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/391670/ums_dbg.zip)

**Comment by Sami32** [comment]
@set135 Like you told `tsmuxer_path = /opt/bin/tsMuxeR` is defined in your UMS.conf
As far as i can see, your path is correctly identified and registred.

Your `ffmpeg.webfilters` is not found.

The fact that you say 2.6.11 version solved you distorsion issue and that is a Linux issue give me think that's a problem for @SubJunk ;-)

**Comment by set135** [comment]
@Sami32 UMS *claims* to recognize tsmuxer_path, but it *does NOT use it*.
You can see this in the log, and also examining the running process.

I did not say 2.6.11 solved the distortion problem, I said that replacing the incorrectly used
tsMuxeR with my system one was required. ie. I described how I am working around the brokenness.

**Comment by Sami32** [comment]
@set135 As i said the fact that `ffmpeg.webfilters` was not found, _TsMuxeR_ use _FFmpeg_, could explain why you get distorsion.

Changing the path of TsMuxeR,  perhaps doesn't affect the TsMuxeR-new path, only my guess though since i don't have any Linux skills, so thence to guess your Linux distro...
I think i remember that UMS's TsMuxer are well tested, it's why it is an old version, to make it supported by all the main OS.
That's said you'll need Linux skilled people to help you ;-)

**Comment by Nadahar** [comment]
I don't know if I should call this a bug or not, but it's at least a strange contstruct that's impossible for users to know about. The "problem" is introduced in c170779d49a8462ae203ec699dfaf19e32da2c13. 

I haven't tested this, just looked at the code, but it seems like UMS will honor ```tsmuxer_path``` for any renderer except PS3. I'm therefore guessing that your renderer is a PS3 @set135? In the case of PS3, ```tsmuxer_new_path``` is used instead...

As far as I can see, this isn't documented anywhere except in the code where the explanation is:
```
Use the newer version of tsMuxeR on PS3 since other renderers
like Panasonic TVs don't always recognize the new output
```

**Comment by SubJunk** [comment]
Basically we had a bug on PS3 affected our older version of tsMuxeR that was fixed in a newer version, but the newer version also broke compatibility with some renderers so we put in an exception for PS3.
However that was back when we used MEncoder to send streams to tsMuxeR, while now we use FFmpeg which may mean we can just update tsMuxeR to the latest one and remove the need for the two versions.
It just needs to be tested and I think we have an issue for it somewhere.

**Comment by set135** [comment]
@SubJunk I agree tsMuxeR is flawed, but it is one of the main reasons I use UMS, as it allows watching most .mkv with no CPU load.
You can control the version of ffmpeg and tsMuxeR you ship, but if I want to use my native system tools, please correct the documentation and implementation to reflect what is actually used. Because forcing your shipped tsMuxeR against my system ffmpeg is clearly not the best;)
Actually, I would love to use UMS with my roku device, but given the default roku media player, it just hangs. Also, the PS3, while a little clunky has beautiful upscaling. (even using plex on the roku, lo-res video looks like crap.) (and plex is a bloated monster)
All that being said; thankyou all for response to this report and the effort of developing this software.

**Comment by Sami32** [comment]
@set135 He just did already ;-) You will just need to do a clean install with the latest 6.5.0 version, and modify your `tsmuxer_new_path =` as you like.
If it's fine, you can clode this issue.

**Comment by Nadahar** [comment]
@Sami32 @set135 There's no need to install a new version, only the documentation is added. ```tsmuxer_new_path``` should work for the current version as well.

Regarding tsMuxeR, there's some serious talk about open sourcing it these days, in fact I think the author has promised to do it and we're probably just waiting for him to find the time to actually do it. That opens the possibility for some bug fixing, although probably not on short term.

**Comment by Sami32** [comment]
@Nadahar I agree, my mind just stick to Windows ;-) where i think it's safer to advise  to do a clean install when issues arisen, just my opinion though...nothing set in stone :-D

Concerning TsMuxeR source code, i don't know if that could help: http://www.universalmediaserver.com/forum/viewtopic.php?f=4&t=8352 the non Github one come from the developper.

**Comment by Nadahar** [comment]
@Sami32 People are different as always. I generally dislike "reset", "reboot", "restart" and "reinstall" as a general remedy. If there's a reason to do so, fine, but I don't like the idea that doing a thing like that resolves anything in itself. It there's a bug causing a problem, any such action only contribute to mask the real problem. If you're "lucky" (unlucky) the problem won't manifest itself for a while and you might think there wasn't really a problem just some unfortunate circumstance. If not, the problem will be just the same after performing such an action, and you've just wasted time.

My idea when attacking a problem is trying to narrow it down as much as possible instead, and only when everything else has failed I'd be willing to try such general measures. Sometimes this leads me to wasting time looking for a problem that wasn't actually there, but most of the time I saves me time by reaching the core problem faster.

**Comment by Sami32** [comment]
@Nadahar Just trying to see if it could solve it's `ffmpeg.webfilters` not found, but that's perhaps not the faster or more correct ways to go though...but that will not get things worst in that case ?
Whatever, your skill and experience and superior than mine so i follow and learn ;-)

**Comment by Nadahar** [comment]
@Sami32 You're right in that the installer should install ```ffmpeg.webfilters```, but I can't see how that file could possibly affect tsMuxeR. The ```ffmpeg.webfilters``` only applies to FFmpeg when transcoding media from the internet/web. As far as I can see, the default filter *only* affects transcoding of files from ```trailers.apple.com``` using FFmpeg.

**Comment by Sami32** [comment]
@Nadahar Thanks for clarifying things. I was not sure how to deal with that.

**Comment by SubJunk** [comment]
@set135 yeah it is cool that it lets PS3 mux MKV.

We would appreciate your help with Roku support, if you want to have a play with forcing different renderer profiles on the Roku and see if any of them fix it that could be a good start.

I agree totally about PS3 upscaling, it's really the best at it. It's a very solid Blu-ray player too. If they would just release an update so it can read MKV files natively it would be so great

**Comment by set135** [comment]
@Nadahar 'installing' UMS under linux is just unpacking a tarball, so, if there is supposed to be an ffmpeg.webfilters file, it simply is not in the tarball. Unless there is an additional step that would generate that file.

**Comment by set135** [comment]
@SubJunk after I verify and close this bug report, I will open a new one regarding Roku, starting with the trace collection. (because it just hangs, I suspect a protocol error, vs. a device profile, but we will see.)

**Comment by Nadahar** [comment]
@set135 Sorry, I'm mixing up the cases and thought we were on Windows when I wrote that. You are absolutely correct that the file doesn't exist by default on Linux, and I don't think it really matters either.

@SubJunk @Sami32 Manually copying the files the Windows installer copies to the profile folder should ideally also be a part of the Linux install documentation.

**Comment by Sami32** [comment]
@Nadahar Why not, but can we do again more easy, simple for UMS users ?
http://www.universalmediaserver.com/forum/viewtopic.php?f=13&t=8459
http://www.universalmediaserver.com/forum/viewtopic.php?f=4&t=8498

I did checked the wiki, and honestly i'm again at searching a way trying to make it easily usable...

**Comment by Nadahar** [comment]
@Sami32 Not sure if I understand what you mean, but creating an installer for Linux is a nightmare because there are no standards for where things are to be placed and which scripts is used for what. Also, you can't expect to have a GUI available (I almost exclusively use SSH for Linux). Placing files and setting configuration is basicly what an installer does. I don't see any manageable way to make it any easier than to give clear instructions on what files to place where (relatively, not absolute, e.g place this file in the ```profile folder```).

**Comment by Sami32** [comment]
@Nadahar Sorry i misunderstood :-/  i was just thinking about easily import configurations files from users in UMS, since i understand only Windows installer and profile.

Only now, with your explanation, i understand what you was asking for.

Concerning Linux, that wasn't you that told me that Linux users need to be able to do that since using Linux in itself require some expertise ?
Kidding apart ;-) for what files exatlly ? because i really don't know what Linuxiens need to add or change...it's maybe not the same as you told already for `ffmpeg.webfilters`.

**Comment by Nadahar** [comment]
@Sami32 I'm still not sure what you're asking. I don't think Linux requires some expertise in itself if you use a mature and "user friendly" distro, so I doubt I said that. The problem is rather the way it works when everybody can invent their own standards. Since there are nobody owning and deciding over Linux, there are nobody to enforce any standard. And thus, we have the current situation. There's lots of strengths with that model, but the lack of standardization is imo a weakness. They should all agree on how to do some fundamental stuff, it would make the world a better place, and would probably make it much easier for developers to choose to offer their software on Linux.

Making an installer is "impossible" because there are no rules, Linux operates with "packages" instead and they are per distro. A package is basicly the same as an installer on Windows, it places the files and does the necessary configuration. The problem is that you need a person, who knows that particular distro, to do it for each distro.

If what you're asking is what the Windows installer does, take a look [here](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/external-resources/nsis/setup.nsi).

**Comment by Sami32** [comment]
@Nadahar Thanks for the link.
Do the Linux users need  this `ffmpeg.webfilters` ? because when i read you i understood that with or without it will not do any difference...perhaps it was only for this particular case ?

**Comment by Nadahar** [comment]
@Sami32 *Need* is realtive. As I see it, no users independent of platform *need* that file as the default implementation only seems to make any difference for ```trailers.apple.com``` and I honestly don't know if the change it brings is better or worse. The purpose of the file if any, is rather to be a template to use for specifying transcoding for other web feeds.

**Comment by Sami32** [comment]
@Nadahar Thanks for clarifying things ;-)

Have a look https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Install and return feedback, please.

**Comment by set135** [comment]
I have tested the tsmuxer_new_path config option, and it works with at least 6.4.0
