### ISSUE TITLE
Freezing...timeouts

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#904]
It's not the first time, but after resetting the _cache_ i get **freezing when i browse on my Panasonic Viera**, and errors with audio files with CovertArt.
My testing directories have not more than 20 files in each, but they "freeze". So nothing huge, except so oldness of my ATHLONXP 1700+ :-D

> DEBUG 2016-05-28 16:17:20.593 [New I/O worker #2] Premature end, stopping... ?

The other times i got this problem i did a clean install with 5.5.0 version Java 7 until it was working fine and never do a clean install after to install latest version, it did not necessary worked the first try.
Did something have to do with _cache_ ? or I/O ? Because on the TV it's telling that the connection failed.
It's freeze as well if i browse in the _ContentDirectory_ using _Cling Workbench_, letting me see or consult the ones already successufully opened/displayed but no news folders, just telling _Loading..._
If it's not folders indicate in _Shared Folders_ it's freeze.
[ums_dbg_Freezing.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/287769/ums_dbg_Freezing.zip.txt)

**EDIT** : I just forgot to mention that i tried with/without _cache_ enabled, and also using scan all folders before browsing.
When i use _Quit_ button before re-start UMS the _javaw.exe_ process stay in the _TaskBar_ until i kill it manually.
It's look like this issue https://github.com/UniversalMediaServer/UniversalMediaServer/issues/708 from @ExSport

**Comment by valib** [comment]
@Sami32 I think that it is an ATHLONXP 1700+ problem. When you reset the cache than during browsing all thumbnails are generated and stored in the cache and it depends on the number of media in the forlder and the PC power how long it will lasts. That is why also _Cling Workbench_ is telling _Loading..._ So next browsing must be faster because thumbnails are already stored in cache. The same must be also when scan of all folders is used.

**Comment by ExSport** [comment]
@valib 
Until this will be fixed, enabling cache and first time browsing folders will be everytime unexpectedly slow until UMS is restarted: https://github.com/UniversalMediaServer/UniversalMediaServer/issues/530
@Sami32 maybe it seems process is frozen but it should not be. If you will browse huge folder or will use SCAN button, UMS tries to finish all the planned tasks before it is closed so it seems for you javaw.exe is frozen. Maybe waiting little more....
Anyway it is true that without fixing bug mentioned above, it is quite a bad behavior that UMS rescans thumbs endlessly until UMS is restarted. In most cases new user will install UMS, enable cache, browse files or SCANs them manually and when people will feel like UMS is much slower than other DLNA/UPnP servers, they will uninstall it :(

**Comment by Sami32** [comment]
@valib I agrre that when the folders are scanned it's faster for the next browsing, but freezing with 5 files in a folder is annoying...slow always better than freezing.
I think remember that anterior version 5.2 or 5.5 was not freezing or less, i will retry and tell you back.
I tried an very basic Media server based on Netty and Cling and everything was fast, so i think it's not a CPU problem. (https://github.com/ccheneau/Holmes)
@ExSport  Waiting for hours to not be able to display a folder with 5 files it's what i was calling frozen; when i exit UMS from the TV and try again, UMS display but not his icon and nothing more is possible except restart UMS server.

**Comment by valib** [comment]
@Sami32 it isn't fair to compare UMS and Holmes. Holmes is really simple implementation doing only browsing folders and streaming media. The UMS does much much more. Especially transcoding and to decide if the media will be transcoded or streamed the deep recognition must be made. Also producing thumbnails take some time. All that is done during browsing. Nothing of that is doing Holmes so that is why is faster.

**Comment by Sami32** [comment]
@valib I not mean offence anybody here ;-), and i know UMS do much more analyses and it's what give him the power to have powerful renderers configuration that i really appreciate.
I was just thinking this reference with Netty and Cling could help...

So here my LOG with **UMS 5.5.0 that solve the freezing problem as well that errors about audio files with CoverArt**, so the 2 problem seem to be connected.
[ums_dbg_5.5.0.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/294369/ums_dbg_5.5.0.zip.txt)
I reseted and disabled the cache before installing this UMS version.

**Comment by atamariya** [comment]
Looks like a deadlock problem. When it happened to me, I changed the overly complex discovering and refreshing code. Haven't faced this issue since then.

**Comment by Nadahar** [comment]
@atamariya There are lot of concurrency "traps"/bugs around the code, but I've met a lot of resistance trying to fix it because I had to prove that a deadlock occurred for each situation I were to correct. Proving anything more than a *potential* concurrency issue, which can be done by logic alone, is very time consuming. In short I abandoned that about 6 months ago, and haven't done much after that.

**Comment by Nadahar** [comment]
I'm trying to do some testing for #1061 in WinXP 32 now, and I'm having a lot of freezing issues. It won't even do a Maven build, it freezes on ```RendererConfigurationTest```. From the debugging I've been able to do, it seems like MediaInfo is the problem. Calls to MediaInfo can suddenly hang completely it seems.

@Sami32 What was the last working version of MediaInfo for WinXP?

**Comment by Sami32** [comment]
@Nadahar I knew you didn't checked my log ;-)
0.7.81 (for XP SP3 version)

**Comment by Nadahar** [comment]
@Sami32 Actually, I did - but I didn't memorize the whole log file.

**Comment by SubJunk** [comment]
We have done a lot of work on performance and stability in the last 2 years so I'm closing this. Feel free to reopen if this isn't addressed
