### ISSUE TITLE
Audio resampling enhancement ?

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#947]
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=8360&p=27361#p27361

What do you think about that guys ?

**P.S.** I hope i was clear but if not feel free to ask.

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/588

**Comment by atamariya** [comment]
My Denon 2113, which is 7.1 system, still reports only max. 2 channels LPCM as supported. So that seems to be a sensible default. Of course, if it's mono audio, playback will fail!! Though I must confess I couldn't get LPCM to work for me.
`http-get:*:audio/L16;rate=44100;channels=1:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;rate=44100;channels=2:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;rate=48000;channels=1:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;rate=48000;channels=2:DLNA.ORG_PN=LPCM,`

**Comment by Nadahar** [comment]
On my Onkyo playback doesn't fail if channels or sample frequency is wrong, it's simply played at a wrong speed/pitch. E.g. 6 channel LPCM plays super slow/low pitch while mono is "smurf".

**Comment by Sami32** [comment]
@atamariya While i make renderer i discovered that renderers have a 2 channels limitation as UPnP/DLNA specifications, at minima, for LPCM and DSD audio format.

Did you tried 16-bit and 24-bit 2 channels and get same result ?
Did you tried with other media server like Serviio, JRiver, MediaTomb or Plex ?
Since it's certified for support it, there necessary a way to make it work :wink: 

Note: Not directly related to your issue though, but i did have problem with my Panasonic Viera and after many tries, i discovered that all informations given by ProtocolInfo was not correct.
My WAV files was playing only with audio/wave or audio/x-wav Mime type; audio/wav was given but not working: https://github.com/UniversalMediaServer/UniversalMediaServer/files/255857/UPNP_Analyse_Compilation.txt
After that, i just came to thought that the "x-" mimetype form is more widely supported.

**P.S.** Denon support informations taken from 2013 forums post: 
> Well I got a reply from Denon support just now. The answer is as expected and still strange:
> 
> "Seek can only be used with MP3 files. It is not possible to use seek with FLAC files. This cannot be fixed with a firmware update."
Update from Denon support:
The reason why this does not work is because the hardware (chipset) used in the Denon products (even the newest ones) is not capable of doing a seek with FLAC files.


@Nadahar I don't know if it can be applied to your renderer, but when looking at Denon i read this comment from a JRiver developper:
> It seems that the Denon doesn't support high precision time and doesn't return an error when we try to use it. We may just remove the high precision time for now.

> My guess is the mimetype or bitrate (there are a LOT of broken devices that expect the bitrate in a non-standard format).

**Comment by Nadahar** [comment]
@Sami32 I'm not sure what you mean. It seems to me that the problem is that UMS doesn't inform the renderer what sample frequency and channels to expect. As stated earlier though, it's a long time (7 months) since I looked at it so I don't remember the exact details.

**Comment by Sami32** [comment]
@Nadahar I taken these comments from there:
http://yabb.jriver.com/interact/index.php?topic=78074.10

Did you tried with others media server and get the same result ? 
In that case this issue could be eventually narrowed to mandatory field missing in the DIDL, as bitrate...
Testing the @atamariya beta version using the protocolInfo full Mimetype should help verify it as well, right ? but it's look like he have LPCM problem with Denon renderer, so or it's malformed LPCM, and i think i tried some, or 

**P.S.** DLNA specifications for LPCM
> 6.1.7.3
> [COMMENT]    Some  Profile  ID’s  have  parameters  like  sampling  rate,  number  of  channels  or 
> interchange format which shall be included in the MIME type exposed by the Serving Endpoint. For 
> example  the  HND  Audio  Media  Class  Mandatory  Media  Format  Profile,  LPCM,  may  have  four different  MIME  type  listings  depending  on  the  parameter  values  supported  (see  requirement 8.5.3.2):
> o  audio/L16;channels=1;rate=44100
> o  audio/L16;channels=2;rate=44100
> o  audio/L16;channels=1;rate=48000
> o  audio/L16;channels=2;rate=48000

> 8.5.3.2
> [GUIDELINE]    MIME type "audio/L16" shall be used for this Media Format Profile.
> The  "channels"  parameter  should  be  included  in  the  MIME  type  header  exposed  by  a  Serving 
> Endpoint.
> The value of the "channels" parameter directly corresponds to the number of channels of the core 
> LPCM stream, i.e. either 1 for Mono or 2 for Stereo.
> If  a  Serving  Endpoint  does  not  include  the  "channels"  parameter  in  the  MIME  typeheader,  the 
> default value assumed by the Rendering Endpoint shall be 1. If the number of channels in the core 
> LPCM stream is 2 then the Serving Endpoint shall indicate this in the MIME type header so that the 
> Rendering Endpoint is always able to correctly determine the number of channels
> The "rate" parameter shall be included in the MIME type header exposed by the Serving Endpoint.

**Comment by Nadahar** [comment]
@Sami32 If the four combinations above (1 and 2 channels, 44,1 and 48 KHz) are the only valid DLNA parameters, it explains why I couldn't get the files I tested to play properly. #729 made sure that these parameters are sent if known, which fixed the problem in some instances (where the values are within the DLNA specification). My test files have a much wider range, including 6 channel LPCM which does not work correctly, but it seems like the only way to serve such files is to transcode them to "legal" values.

I haven't tested that with other media servers as I recall it, since I'm always trying narrow down a problem instead of adding unknown variables (I don't know what the other media servers is doing when serving the files). Neither have I tested this with @atamariya's version since I'm not really working with this atm :wink: This isn't something I've given full attention at any time, but something I've tinkered with while dealing with other issues - and thus I've never really gotten to the bottom of it.

**Comment by Nadahar** [comment]
@Sami32 What it comes to the original request in this issue, it's been my view that the whole "transcode to 44,1 or 48 KHz" setting is a mess that shouldn't be there. My guess is that the reason for this strange construct is that the PS3 can be configured to expect *either* 44,1 KHz or 48 KHz, and this UMS (PMS) setting is supposed to match the configuration made on the PS3. It doesn't make any sense for other renderers though, so the best thing would probably be to limit the whole "resample audio" function to the PS3 if it should be kept at all.

When it comes to the number of channels it could easily be changed to preserve the number of channels from the source (1 -> 1, >= 2 -> 2). Any changes to this should probably be seen together with the wider issue of DLNA only supporting 1 or 2 channels for LPCM which means the any files with more than 2 channels need to be transcoded down to 2 channels for LPCM regardless of the "audio resample" setting.

**Comment by Sami32** [comment]
@Nadahar Yes and no :wink: 
I mean that's DLNA mandatory specifications, leaving the possibility to some manufacturers to implement wider support, like 6/8 channels LPCM or 22050 bitrate.

I didn't saw that it was specific to PS3 ?, only to audio transcoding while using MediaInfo.

1- First possibility:
Transcoding everything superior to 2 channels by default, but leave a choice to user outpass that, as for now it's not automatic transcoding.
If a such non mandatory DLNA implementation was done the  protocolInfo will reflect it so the @atamariya work could be automatically used.

2- Second possibility:
LPCM is the only audio mandatory in DLNA specification, so fast and well supported transcoding to WAV should probably satisfact most users in the case of 6/8 channels LPCM.
IMO, @atamariya work should use the prefered transcoding option based on protocolInfo and not the first one supported, as renderers could have a better support for some kind of format.

**Note**: AFAIK, 6 or 8 channels LPCM is implemented on some renderers but usable only over HDMI.
But very few, like Vizio Smart, have also a such DLNA implementation: http://yabb.jriver.com/interact/index.php?topic=75975.35

**P.S.** Some omitted part of LPCM DLNA specification.
> 8.5.1.2
> [GUIDELINE]   This audio format specification shall follow profiling of IETF RFC 3555, which defines 
> the MIME encapsulation for the LPCM DLNA Media Format and uses the "L16" audio Media Format 
> defined  by  IETF RFC 3551.   "L16"  denotes  uncompressed  audio  data,  using  16 bit  signed 
> representation in two's-complement notation and network byte order.
> There are the following parameter constraints to "L16" as defined by DLNA.
> Sampling rates:
>  44,1 kHz
>  48 kHz
> Content audio channel modes:
> A bitstream conformant with this Media Format Profile may contain the following formats
>  Mono (1)
>  Stereo (2)
> Quantization:
>  16 bit

...

> This  guideline specifies that  a Serving  Endpoint shall expose  only the  MIME types  of the partial 
> parameter sets  it supports  in the CMS.SourceProtocolInfo  instance state  variable, see  guideline 
> 6.1.7.3. If, for example the Serving Endpoint supports mono LCPM at sampling rates of 44,1 kHz 
> and stereo at 48 kHz then it needs tolist only the following information in the protocolInfo :
> http-get:*: audio/L16;channels=1;rate=44100:DLNA.ORG_PN=LPCM
> http-get:*: audio/L16;channels=2;rate=48000:DLNA.ORG_PN=LPCM

**EDIT**: I retrieved trace of that work done in 2011 by Tomeko: http://www.ps3mediaserver.org/forum/viewtopic.php?f=11&t=9684

**Comment by Sami32** [comment]
I read that 2 channels LPCM use 1.4Mbit/s maximum bandwidth and 8 channels LPCM use 6.144Mbit/s maximum bandwidth.
http://www.mpeg.org/MPEG/DVD/Book_B/Audio.html

**Comment by Nadahar** [comment]
@Sami32 I'm not sure that only the channels are different in those numbers. There's also the sample rate and bit depth that varies. Since we're talking about L16, bit depths above 16 are irrelevant. I don't know if L20 and L24 is implemented in any renderers or relevant to care about. That said, 6 Mbps is no match for a wired network.

**Comment by Sami32** [comment]
@Nadahar The point was to have a better idea of the bandwidth necessary :wink: 
6.144Mbit/s ==> stereo 24bit/96khz or stereo 16bit/192khz
As the bandwidth limit is 6.144Mbit/s, you cannot have some combinations like 24bit/192Khz, 20bit/192khz, 24bit/96khz and 8 channels. or 24bit/96khz and 6 channels...

The coding part related to DVD audio stream conformance to a maximum bandwidth of 9.8Mbit/s is not our concern in that case, but only for DVD maker; it's why you find a HD sound track for main language and a SD sound tracks for other languages or better compliance with low end renderers, because they need to respect his limitation (6.1+1.4+1.4=8.9Mbit/s)

https://wiki.multimedia.cx/?title=PCM
EAC-3 support 15 channels and have also a maximum bandwidth of 6.144Mbit/s
https://en.wikipedia.org/wiki/Dolby_Digital_Plus
I think L24 is implemented in Naim Unity, not too popular though...

https://tools.ietf.org/html/rfc3190
http://www.iana.org/assignments/media-types/audio/L24
http://www.iana.org/assignments/media-types/audio/L20

**Comment by Nadahar** [comment]
@Sami32 I understand everything except who dictates these upper limits (6.144 Mbps and 9.8 Mbps). Why does 6.144 Mbps apply to us, and is this a per track limit or a combined limit? I've been thinking about per track/audio stream the entire time, but when you start talking about combining streams to keep the 9.8 Mbps limit I get really confused. I always though they did that just because of the physical storage limit on the DVD medium (that they preferred extra video bandwidth instead of secondary audio bandwidth) and/or because they didn't bother mixing the secondary audio into the surround setup. 

Personally I've never cared that they reduce the secondary audio, I hate dubbing so I always use the original track nomather what language it is as long as I can get subtitles that I understand (English, Norwegian, Swedish or Danish).

**Comment by Sami32** [comment]
@Nadahar They come from an old Compact Disc Digital Audio (CDDA) standard that is called "Red Book" (https://fr.wikipedia.org/wiki/Red_Book_%28norme_CD_audio%29), IEC 60908, and DVD-video standard (https://en.wikipedia.org/wiki/DVD-Video)
https://en.wikipedia.org/wiki/Compact_Disc_Digital_Audio
If you don't want read the 276 pages you can have a resume here:
https://www.custcenter.com/app/answers/detail/a_id/2718/~/red-book-standard-for-cds
      bit rate = sample rate x bit depth x channels
      44,100 x 16 x 2 = 1,411.2 Kbit/s
      48,000 x 16 x 8 = 6,144 Mbit/s
      48,000 x 24 x 8 = 9,216 Mbit/s

As told 6.144Mbit/s is per track, don't bother for 9.8Mbit/s that is combined but specific to DVD maker.
6.144Mbits/s limitation apply to us in the way that they are implicite in the DLNA standard and devices as well.  
The subjet was LPCM 6 and 8 channels support, so i thought that giving the bandwidth was good to make users remember that they need to have a good network as well if it was used.

P.S. Yes, i remember that you haaaate the dubbing but i love it :stuck_out_tongue_winking_eye: as i don't have to miss some part of the movie while reading the subtitle...

**Comment by Nadahar** [comment]
@Sami32 Ok, thank you for clearing that up. Still we probably don't have to do anything in particular regarding these limits, I guess that responsibility is on whoever encodes the audio track or the transcoder.

Regarding the dubbing/Off topic: That's just because your read speed is too low/you're not used to it :stuck_out_tongue:  I don't miss anything because of the subtitles unless they very rarely cover up something important. I don't even remember reading them, it's fully automated :wink: It probably just takes some getting used to. I even prefer subtitles when the audio is in Norwegian because I don't have to have the audio volume high enough to hear everything. They mix all kind of other noise (music, shooting, fighting, engine sounds etc) in with the audio often making the voices hard to hear imo, meaning that I often have to have the audio volume too high for comfort during "dramatic scenes" to properly hear the voices in other parts. This is especially true for surround sound.

**Comment by Sami32** [comment]
@Nadahar Everything fine, we don't have option for 24 bit yet but few users will need it for now i guess.
The point was that it's used without informing the users of the 16 bit and 2 channels transcoding status. So i was just asking if i could modify this message property, adding "(2 channels)", but i guess no answer mean yes ?
I think using _protocolInfo_ for transcoding is a good idea, with a manual fallback possibility just in case...

Off topic: Your are right, too slow, it's not that easy to read the dictionary in the dark  :stuck_out_tongue: just kidding ;-)
I guess that you are viewing too much CAM ;-) I haaaate them.
I like more wait a little more and get a DVD rip with good audio track.

**Comment by Sami32** [comment]
@Nadahar I tried to look more at the code and i could be wrong, but it's look like the LPCM mimetype is send as 2 channels but i didn't saw any channels parameter defined in FFmpeg command, or for any other audio.
So i guess i missed something.

Do you see any audio channels parameter somewhere ?

**P.S.** Btw, i looked at the code and understand that core numbers will be the threads number by default, multithreading parameters could be changed manually, but i could be wrong though.

**Comment by Nadahar** [comment]
@Sami32 I know nothing about FFmpeg or any other transcoding engine parameters. My guess is that the transcoded stream will have the same number of channels as the source if the destination format supports it, or that it will be reduced to the closest match. E.g 6 channel WAV file -> 2 channel MP3; 1 channel WAV file -> 1 channel MP3. Again this is guessing on my part, and it probably varies between the transcoders. We'd probably need the specify some parameters to reduce a 6 channel audio file 2 channels or reduce the bit depth or sample rate, I simply don't remember. 

I don't want to dig into this now as I don't have the time to finish it anyway, so I'll just provide any information or thoughts I can caugh up without studying the code and/or testing. 

When it comes to changing the information to the users, I doubt anybody would mind (although I always prefer PRs) as long as the new information is correct. As long as we're not 100% sure how this works, trying to inform others might not be the best idea.

Off topic: I think I've actually watched one CAM in my whole life. I'm normally not in a hurry to see things, and I want quality if I should be bothered. I don't even watch SD anymore unless the material is too old to exist in HD. That said, I'm so fed up with the crap Hollywood spews out that I generally don't watch movies anymore - and haven't for 12-13 years. I mostly just watch some crap that runs on TV if I watch something, but I generally prefer doing other things instead. There are some exceptions of course, like (old) Top Gear, Mash and The Big Bang Theory :wink: I do like documentaries though, but the people making them are generally more intelligent than the Hollywood people and don't drown speach "because it's cool".

When I refer to voices being hard to hear, I'm referring to full quality surround. Hollywood in their quest to exaggerate everything typically play "action sounds" very load (for dramatic effect) which means that if you don't want to scare your pets or wife during the "action sequences" you have to lower the volume to a level where speach is often hard to hear. I've bumped the center speaker a couple of notches to counter this, but it's still annoying me. I do have "night listening mode" and similar functions to reduce the difference, but I'm generally against manipulating the source in any way so I tend to stay away from such functions if I can. I just prefer subtitles because then I can adjust the audio volume to where it's pleasant and still follow whatever is happening.

Regarding ambiguous acronyms I guess you have to apply context to solve it :wink:

**Comment by Sami32** [comment]
@Nada It's why i ask to more skilled people and put that as issue.

About this specific issue, LPCM resampling, since it's without header and send with the 2 channels MimeType it need to get 2 channels output (99.99% sure ;-))

But concerning the other audio, i thought like you but i now it's incorrect since it need to have the parameter taken in the configuration file and i don't see them, so i know i missed something.
So if you find before me, don't forget to share ;-)

Off-topic: I didn't even know about ATM meaning, except for withdrawing money, it's why i did make some searches about that and learned :wink: 

N.C.I.S. and _Peaky Blinders_ series are more in my taste :-)
I agree for Hollywood brainwashing bloody staff and definitively go for documentaries.

**Comment by Sami32** [comment]
As it's Linear PCM (s16be), meaning raw and 2 channels only, this issue can be closed.

Telling that it's strickly DLNA standard compliant (LPCM, 16 bit, signed and Big Endian), implicitely mean 2 channels, as per specifications. So maybe write later. Anyway i get my answer :-)

**Comment by Nadahar** [comment]
@Sami32 I've never heard of Peaky Blinders so I guess they don't send it here, but I did watch N.C.I.S earlier (not following it but watching random episodes by coincidence). However I reached my saturatioin point several years ago, it's just too much of the same for me, and frankly it's too Hollywood. When they start doing the typical things like making intrigues between the characters as the main focus and spawning spin-ofs (N.C.I.S New Orleans is shit imo, L.A is barely tolerable) my bullshit filter quickly fills up. And, it never was the same after they killed of Kate...
